### PR TITLE
Fix PNI related product blur bug

### LINKED ISSUE #5973: PNI: bug with 18+ blur in Related Products
Feature is working as expect on the homepage but the blur isn't correct on product detail pages.

### Todo
- [ ] Blur Related Products that are rated 18+
- [ ] Remove blur for Related Products that are not rated 18+ (when on a 18+ Product Detail page)

### Example from staging of a regular product page
Sony WH-1000XM4 has the +18 icon which is good but the Product photo should be blurred

Screen Shot 2021-01-06 at 9 16 17 AM

### Example from staging of an 18+ product page
When on a product detail page of an 18+ product, the Related Products that aren't 18+ should not be blurred

Screen Shot 2021-01-06 at 9 16 23 AM

### PR DESCRIPTION
**Pull request by mmmavis**
Closes #5973 

Test page: https://foundation-s-issue-5973-5vgfkk.herokuapp.com/en/privacynotincluded/than-check-husband-smile-figure-mind-else/

---

I also fixed the unbalanced padding from 
image
to
image

### CODE REVIEW

**Review by kristinashu — APPROVED** [review]
Looks good! 

The fake data generator is doing some weird things but I think it will be fine with our real data. 
image

**Comment by mmmavis** [comment]
@kristinashu yea I think it's just the fake data generator doesn't add fake product images anymore. I had to upload them manually to set up the test page.

**Review by KalobTaulien — APPROVED** [review]

**Comment by KalobTaulien** [comment]
@mmmavis There's a strange thing happening in Percy. 

image

Can you confirm this is working normally on your end?

**Comment by mmmavis** [comment]
Looks like it was a false positive flag raised by Percy. [Review app page](https://foundation-s-issue-5973-5vgfkk.herokuapp.com/en/campaigns/regrets-reporter/) looks fine and updating this PR makes Percy flag go away. I think this might be an intermittent issue on the Percy side.

**Pull request merged**
