### PR TITLE
Type fixes for publication page & article page

### LINKED ISSUE #5782: Publications heading subtitle
Publications heading subtitle: 20px/30px to be body-large size (currently 28px/36px). Currently it's too big. 

Example link: http://localhost:8000/en/publication-page-with-chapter-pages/
Target area:

Criteria:
- [x] Font size 20px, line-height 30px. Should be the body-large size.

### LINKED ISSUE #5787: Use nunito light for Article Page body
Article Page: Article body override to Nunito Light similar to how blog-body is lighter for long form reading but this will stay at 18px (italic looks lighter weight already see 'trustworth AI' in paragraph below)

Target Area: 

Criteria:
- [x] Font should be Nunito Light, not Nunito Regular (and should look the same as the blog)

### LINKED ISSUE #5815: Add publication page and article page to Percy

### PR DESCRIPTION
**Pull request by mmmavis**
Closes #5782
Closes #5787

Will assign code reviewer once this passes design review.

- https://foundation-s-issue-5815-wzrrrp.herokuapp.com/en/publication-page-with-chapter-pages/
- https://foundation-s-issue-5815-wzrrrp.herokuapp.com/en/publication-page-with-chapter-pages/time-us-several-compare-especially/ahead-toward-choice-alone-visit-down-even-beautiful/

### CODE REVIEW

**Review by sabrinang — COMMENTED** [review]
The type weight looks good for article pages! For the publication/publication child pages will the "notes" streamfield block also be in nunito light? (there was no dummy text to tell)

**Comment by mmmavis** [comment]
@sabrinang do you mind you logging into the CMS and add/edit the "notes" block? I can't find the "notes" option.

image

**Comment by mmmavis** [comment]
@sabrinang Did you mean the "Notes" field on the Publication Page? If so, my PR doesn't cover that fix as it's not mentioned in the two tickets this PR addresses. I can add that additional fix in if we'd like the "notes" to appear in Nunito Sans Light.

**Comment by sabrinang** [comment]
@mmmavis Yeah I meant the notes field because I thought they were sharing same styles and yes it would be good to update the notes too as that body copy should be a similar reading experience as the article body copy

**Comment by mmmavis** [comment]
@sabrinang PR updated!

**Review by sabrinang — APPROVED** [review]
Great thanks for adjusting the copy to light for body copy on pub notes and article page!

**Review by KalobTaulien — APPROVED** [review]

**Pull request merged**
