### PR TITLE
Remove related mss

### PR DESCRIPTION
**Pull request by Pomax**
Closes https://github.com/mozilla/foundation.mozilla.org/issues/5608

Removes the MSS badge from the related products "card", and removes the MSS badge graphics files and seal_of_approval fragment.

image

review URL: https://foundation-s-remove-rel-tghojm.herokuapp.com/en/privacynotincluded/products/percy-cypress/

### CODE REVIEW

**Comment by Pomax** [comment]
This will also require a follow-up investigation to see whether we can remove all the `seal-of-approval` mixin/class code in our SCSS now too, or whether we reused that for the privacy ding, without renaming it.

**Comment by Pomax** [comment]
we probably need to keep the seal-of-approval file here, and only swap out the MSS for ding..

**Review by kristinashu — CHANGES_REQUESTED** [review]
Seems to be working as expected but can you please reduce the icon size from 30px to 25px so it is the same size as on the homepage.

**Comment by Pomax** [comment]
@kristinashu updated to 25px

**Review by kristinashu — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
