### PR TITLE
Update some font sizes

### PR DESCRIPTION
**Pull request by mmmavis**
Related to #4158

Please use review app, [review app's style guide](https://foundation-s-issue-4158-y4vzhx.herokuapp.com/en/styleguide/), and Percy tests to verify the font changes look good.

### CODE REVIEW

**Comment by sabrinang** [comment]
What style is the body in the happening now feed? 
image

I think it's still 16px but shouldn't all body copy be 18px now or is it cause its a wagtail component  thing?

**Comment by mmmavis** [comment]
@sabrinang nice catch! The issue you found is actually tied to something else. I don't have to bandwidth to fix it now so I filed a follow-up instead: https://github.com/mozilla/foundation.mozilla.org/issues/4287

If anything else looks good, can you R+ this PR 😉 ?

**Comment by sabrinang** [comment]
Thanks @mmmavis for filing that issue separately

**Comment by mmmavis** [comment]
omg I forgot to merge this PR 😂

**Pull request merged**
