### PR TITLE
7389 section hrs

### LINKED ISSUE #7389: [PNI] Product page - add horizontal rules between "end of page" sections
- [x] add horizontal rules between the "end of page" sections
  - note new styling on these hr

Relevant part of the updated product page comp:

image

Comps on figma: https://www.figma.com/proto/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?page-id=548%3A72128&node-id=611%3A77813&viewport=283%2C48%2C0.08&scaling=min-zoom&starting-point-node-id=611%3A77813

### PR DESCRIPTION
**Pull request by danielfmiranda**
Closes #7389 
Related PRs/issues: This PR depends on #7390. Please don't merge until that PR has been merged in.

**Link to sample test page**: https://foundation-s-7389-secti-c8kqgs.herokuapp.com/en/privacynotincluded/fine-close-tv-build-radio-end/

**Steps to test**

1. Visit the link above
2. Scroll to the "News" section, note there are now new dividers in between the requested sections.
3. If everything appears correctly, testing is complete!

### CODE REVIEW

**Comment by Pomax** [comment]
@danielfmiranda this will need a rebase before it can be reviewed

**Review by Pomax — CHANGES_REQUESTED** [review]
rebase required

**Comment by danielfmiranda** [comment]
Hi @Pomax! Rebased and ready for re-review :D

**Review by Pomax — APPROVED** [review]
code looks good to me

**Review by sabrinang — CHANGES_REQUESTED** [review]
The space after News heading should be similar to Related products (_currently looking a bit far from the content beneath)_
image

**Comment by danielfmiranda** [comment]
Hi @sabrinang! thank you for the feedback, the spacing has now been updated and is ready for re-review

**Review by sabrinang — APPROVED** [review]
Great thanks for the adjustment Daniel, looks good! 👍

**Pull request merged**
