### PR TITLE
[FE/BE] - Mozfest Hero updates

### PR DESCRIPTION
**Pull request by b-ggs**
Related PRs/issues #7432

## Implementation Checklist

- [X] Editor can add a heading
- [X] Editor can specify 3 (no more, no less) subheadings each with their own heading, plain-text copy, and associated image
- [X]  Editor can specify an embedded YouTube video OR video in Wagtail

### Of note

* Bumps `wagtailmedia` to `0.8.0` to use `VideoChooserBlock`
* The new hero will only show up once `Banner Carousel` has been populated with data. If there are no `Banner Carousel` items, (e.g. when this is first deployed to production) the previous version of the hero will be displayed. See the relevant screenshot below.

## Screenshots

MozFest Homepage

Screen Shot 2021-10-14 at 3 51 03 AM

Wagtail Admin editor showing the `Banner Carousel` and `Banner Video`

Screen Shot 2021-10-14 at 3 51 46 AM

`Banner Video` can use a video uploaded on Wagtail or an embedded external video (e.g. from YouTube or Vimeo)

Screen Shot 2021-10-14 at 3 51 57 AM

Original hero will still be displayed if `Banner Carousel` is empty

image

## Checklist

**Changes in Models:**
- [X] Did I update or add new fake data?
- [X] Did I squash my migration?
- [X] [Are my changes backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

### CODE REVIEW

**Comment by jamilasnell** [comment]
Is this PR still needed @b-ggs ?

**Comment by b-ggs** [comment]
Hey @sabrinang and @Pomax! We've got the changes ready for the Hero. Would you mind checking it out whenever it's convenient? Thanks!

**Comment by b-ggs** [comment]
All relevant tests should be passing now. I still can't seem to replicate Sabrina's issue with mp4s locally unfortunately. @Pomax, is there a way Steve and I can log into a testing instance so we can test these out?

**Comment by Pomax** [comment]
The review app credentials are listed in the review app channel, but we're going to have to see if there's some way to get you access to that. For now it might require Marni as intermediary.

**Comment by b-ggs** [comment]
@Pomax, I've made the changes that you've requested. Would you mind checking this out whenever it's convenient? Thanks!

**Pull request merged**
