### PR TITLE
Make the primary page banner cms-controllable

### PR DESCRIPTION
**Pull request by Pomax**
Initial stab: this makes the primary page banner a real image element rather than a CSS pseudo-element. From what I can tell this still looks the same, but that needs confirmation.

Related PRs/issues https://github.com/mozilla/foundation.mozilla.org/issues/2661

### CODE REVIEW

**Comment by alanmoo** [comment]
Can Percy tell us if it's the same?

**Comment by Pomax** [comment]
I've tested this by comparing the PR's `about` page with the https://foundation.mozilla.org/en/about page at various breakpoint sizes, and there is marginal different in image scaling at the min-width breakpoint, but nothing that would seem to be so different as to qualify as "needs to be redone".

If you agree, then I can add the actual background-from-CMS functionality on top of this.

**Comment by Pomax** [comment]
@alanmoo it'll at least be able to tell us what's different, let me add an "about page" screenshot to the percy battery

**Comment by Pomax** [comment]
@alanmoo added a test, but because it's a first-time test it won't help us in this specific case, and we still need the visual confirmation that things look "the same enough".

**Comment by kristinashu** [comment]
Sorry but I'm not too sure what and how to test...

1. About https://foundation.mozilla.org/en/about/
Looks good but I don't see where to update the banner image in the cms.

2. Initiatives & Participate https://foundation-mofostaging-pr-2765.herokuapp.com/en/initiatives/ & https://foundation-mofostaging-pr-2765.herokuapp.com/en/participate/
Should not be affected by this update, their banners should be unique (do they look different because of the review app?).

3. Where can I test the new multi-page campaign page https://foundation.mozilla.org/cms/pages/331/view_draft/?

**Comment by Pomax** [comment]
@kristina there is no new functionality yet in this pr, all it does is change the html+css so that the banner is still hardcoded, just not as a CSS `:before` pseudo element, but as a real `` element that we can swap the image source of in immediate follow-up.

1. it should look the same as before. if it doesn't, that's bad.
2. initiatives being empty is due to the load_fake_data process for the review app.  the participate page is definitely also the load_fake_data process but looks like a completely different page, so that's probably use never having updated what the content for that should be. I've filed that as https://github.com/mozilla/foundation.mozilla.org/issues/2767
3. not in this PR

**Comment by kristinashu** [comment]
We might need to clarify what we mean by "primary page banner" because it is confusing. It's anything with this style banner is considered "primary page banner" (even if it isn't in the main nav).

https://redpen.io/hx70e9eb24e0534b72

image

**Comment by Pomax** [comment]
The definition I'm working with is the one that maps to our `class PrimaryPage` model, which defines the data for anything that is page of type "Primary Page" in the CMS, which includes the following top level pages:

- the about page
- the fellowships page
- internet heath
- mozilla awards

image

**Comment by kristinashu** [comment]
Ah got it! Then this all looks and sounds good to me. About page banner looks good and I'll trust you two that there aren't any unexpected side effects.

**Comment by Pomax** [comment]
As far as I can tell, all those pages marked as "primary page" have that same header, so I'm pretty sure we're talking about the same thing, but this PR is not "the work to replace the banner image", this is scaffolding work that needs to happen _before_ the banner image can be made replacable, so all those pages should still look the same as before, even though I had to change the underlying code to make it possible for us to start writing code that lets the banner image be CMS-controllable.

**Pull request merged**
