### PR TITLE
remove "npm install" from the start command

### PR DESCRIPTION
**Pull request by Pomax**
Closes https://github.com/mozilla/foundation.mozilla.org/issues/2608

Everyone tagged for signoff mostly because it's a change to how to install and run the foundation site.

### CODE REVIEW

**Comment by alanmoo** [comment]
There isn't anything that's assuming `npm i` gets run with `npm start` in the deployment flow, is there?

**Comment by cadecairos** [comment]
> There isn't anything that's assuming `npm i` gets run with `npm start` in the deployment flow, is there?

There isn't, the Heroku buildpack for node projectsdoesn't call `npm start`, it's only used in a dev context.

**Comment by mmmavis** [comment]
> There isn't, the Heroku buildpack for node projectsdoesn't call `npm start`, it's only used in a dev context.

Ah cool that was my only concern.

**Comment by mmmavis** [comment]
Ah one note -
Now that `npm install` is not part of the dev flow, we need to find a way to ensure `package-lock.json` is always up-to-date.

**Comment by Pomax** [comment]
If you need npm installs, `inv catch-up` still has you covered. updating package-lock.json when there's _actually_ a change (e.g. dependabot) is perfectly fine.

**Pull request merged**
