### PR TITLE
#9415 Sync translations for featured hero article (and other related article fields)

### PR DESCRIPTION
**Pull request by tbrlpld**
# Description

This PR sets the different fields on the Buyer's Guide homepage to be synchronized with the original version of the page. 
Actually, we would prefer them to be translated (which means they would always point to the translated version of an object automatically). 
But, there are two bugs in Wagtail Localize that prevent this. 
Specifically: 
* https://github.com/wagtail/wagtail-localize/issues/430, and
* https://github.com/wagtail/wagtail-localize/issues/640

As a workaround, we can use synchronized fields. The caveat is that we need to make sure that we still point to the translated/localized version of the articles in the frontend. 
To handle this, I have added/adjusted the getter methods for the different field. 

To test that the synchronization works:
1. Login to the admin
2. Navigate to the edit view of the **french** version of the buyer's guide homepage. 
3. Click the "translate this page" button.
4. Check the "french" locale tickbox and click the "submit" button.
1. Open the **french** version of the buyer's guide homepage: http://localhost:8000/fr/privacynotincluded/
4. See the titles of the different featured articles (hero, hero supporting, advice, popular)
5. Navigate to the edit view of the **english** version of the buyer's guide homepage. 
6. Pick different pages for the related links and publish the **english** page.
7. Synchronize the buyer's guide homepage translation (in the tree view click the "more" button)  Screen Shot 2022-11-04 at 17 01 567. 
8. Synchronize and publish the translations.8. 
9. Reload the **french** version of the buyer's guide homepage: http://localhost:8000/fr/privacynotincluded/
10. Observe that the featured articles should be updated according to the changes you have made.

Test that the localization works: 
1. Open the translated version of the buyer's guide homepage: http://localhost:8000/fr/privacynotincluded/
2. Follow the related articles links and notice that the active locale is still the translated one (you can notice this in the URL -- if you started with `http://localhost:8000/fr/privacynotincluded/` you should still see the `fr/` bit in the URL.

Link to sample test page: http://localhost:8000/fr/privacynotincluded/
Related PRs/issues: #9415

# Checklist

**Tests**
- [x] Is the code I'm adding covered by tests?

**Changes in Models:**
- [ ] ~~Did I update or add new fake data?~~
- [ ] ~~Did I squash my migration?~~ No migrations.
- [x] Are my changes [backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- [x] Is my code documented? Through tests.
- [ ] ~~Did I update the READMEs or wagtail documentation?~~

### CODE REVIEW

**Review by kevinhowbrook — COMMENTED** [review]
Thanks Tibor, 

Locally testing this when I do the 'translate page' step I receive a TypeError:

https://user-images.githubusercontent.com/2128707/200301689-8d8643a1-0c10-48b2-b399-b9ebc028efd6.mp4

**Review by TheoChevalier — APPROVED** [review]
Thanks @tbrlpld I was able to test successfully!
I wonder if the issue you’re seeing is due to specific data in the test DB @kevinhowbrook I’ll try to reproduce (I’ve never seen such error message, fwiw)

**Comment by tbrlpld** [comment]
@kevinhowbrook What are the exact steps that lead to the error? Which database are you using? 

I just trie the following way: 

```console
git switch main 
inv new-db
git switch 9415-sync-translations-w-featured-hero
docker compose up
```

followed by the outlined steps from the description.

**Comment by tbrlpld** [comment]
@kevinhowbrook I have also updated the testing steps. I had initially missed to first translation set up. You need to first translate the page before the "sync" option becomes available.

**Review by danielfmiranda — APPROVED** [review]
Hey Tibor,

Thanks for the easy-to-follow instructions for testing this PR, after giving it a look and testing, I can confirm that everything is working as expected. 

Approved and great work! 👍

**Pull request merged**
