### PR TITLE
Revised Pulse Project Component

### PR DESCRIPTION
**Pull request by gvn**
Related issue: #1639

### CODE REVIEW

**Comment by gvn** [comment]
@taisdesouzalessa if you want to try this out in the CMS you can go to https://foundation-mofostaging-pr-1668.herokuapp.com/cms/

**Comment by gvn** [comment]
Made changes where possible.

**Comment by taisdesouzalessa** [comment]
Design review: 💯

**Comment by gvn** [comment]
@Pomax I'm trying to determine if this component schema change is safe or going to blow things up again. It's mostly additive FWIW...

Worst case I can leave the existing `PulseProjectList` intact and move these tweaks to a new `PulseProjectList2`.

**Comment by Pomax** [comment]
Styling looks a bit odd in my FF, but codewise this should be safe. We're redeclaring newest_first but the data in it stays "the same" so pages that had it set to `True` or `False` stay set to that as far as I can tell.

FF screenshot:

image

**Pull request merged**
