### PR TITLE
8367 - Sticky Nav P1

### LINKED ISSUE #8367: Sticky Nav P1

### PR DESCRIPTION
**Pull request by fessehaye**
Closes #8367 

Example without child publications: https://foundation-s-8367-nav-uemec8hb.mofostaging.net/en/publication-page-with-chapter-pages/produce-need-leg-can-kind-compare-individual-close-idea-us-outside-hard-kind/fixed-title-article-page/

Example of just article: https://foundation-s-8367-nav-uemec8hb.mofostaging.net/en/no-publication-included/

Example of publication with child publication: https://foundation-s-8367-nav-uemec8hb.mofostaging.net/en/publication-page-with-chapter-pages/child-publication-nav-test/

### CODE REVIEW

**Review by beccaklam — CHANGES_REQUESTED** [review]
Hi Simon! The menu is looking and working great for the most part 💯 Thank you for your hard work on this! Most of my requests are style changes but there's a few functionality questions at the end. Thank you!

Change requests:

## Style Changes

### Sticky Nav H2 Anchor Header Title and Menu Content Alignment
- [ ] In general, the H2 anchor titles should align with the menu content below. I think increasing the space between the H2 anchor titles and the drop down arrow will help. This will also allow more space for the H2 anchor titles to display, at least on larger screen sizes.

**Current example:**
Screen Shot 2022-03-31 at 11 00 16 AM

**Change to:**

Screen Shot 2022-03-31 at 11 00 07 AM


### Child Publications
- [x] The color of the gray bar should be gray-05 not gray-20
- [x] Font-size should be 12px
- [ ] The back arrow in the gray bar and the text in the above purple bar should align

**Current:**

Screen Shot 2022-03-31 at 10 50 37 AM

**Change to:**

Screen Shot 2022-03-31 at 10 52 44 AM


### Accordion alignment
- [x] Accordions should be aligned. I've only included desktop screen shots but this applies for mobile as well. The only difference being the padding right and left on large screens should be 48px and on small screens it should be 16px. My thinking when I designed the menu items is that they would have a set template size so if a title was longer it would simply move to two lines instead of being on one line. Therefore alignments would remain the same. Does that make sense? I've included a screen shot of the Figma component to see if that helps. But the set width would differ from large to small screens.
Screen Shot 2022-03-31 at 11 32 04 AM


**Current:** 
Screenshot 2022-03-31 at 10-04-51 Fixed title article page

**Change to:**

Screen Shot 2022-03-31 at 10 08 53 AM


## Functionality
### Thumbnails
- [ ] 😅 Sorry, I know I said not to render when no image is selected but I think it looks strange if some menu items have thumbnails and some do not. Can we revert to the old rules where the thumbnail will default to a blank square when no image is chosen?

### Mobile
- [ ] Not sure if this is only an inspect thing but the main nav appears cut off when I scroll up?
Screen Shot 2022-03-31 at 10 12 42 AM

## Accordions
- [ ] I didn't see an example of this so I just wanted to note: when an Article doesn't have H2 headings, the accordion icon should not render. Is that currently true?

### Menu Positioning
- [ ] Sorry, I think I forgot to put this in the design to dev checklist, but I was thinking that when a user opens the menu, the menu would show where the user currently is in the content. Would this be easy to implement? If not, we can leave this for now and I can make it a ticket for a later sprint.

**Review by beccaklam — DISMISSED** [review]
Also, sorry, one more thing! I noticed that the spacing between elements in menu items look a little off so I've tagged you in a couple comments in the Figma file to show you where you can find the proper spacing:
Screen Shot 2022-03-31 at 11 47 05 AM

Please let me know if you have any questions!

**Review by beccaklam — DISMISSED** [review]
Hi Simon! The changes are looking really good! 💯 Just three things:

## General:
- [x] Now that I'm seeing this live, can we change the padding-top and bottom for the Table of Contents section to 1.4rem instead of 2rem? Just so the menu items aren't pushed down so much.
- [x] The 'x' is cool but closing the accordions should actually be a minus icon! Sorry, here's the asset: 
minus-circle
Here are the other ones as well, in case you need them:
plus-circle
arrow-right-circle
Screen Shot 2022-04-04 at 11 14 54 AM

## Medium Sized Screens
- [x] The alignment is looking wonky for medium (tablet) sized screens?
Screen Shot 2022-04-04 at 10 53 14 AM

Thanks again Simon, we're almost there!

**Review by beccaklam — COMMENTED** [review]
Hi @fessehaye this looks almost good to go! 

- [ ] Sorry one little thing, for medium screen sizes (so between large and small) can we make the padding left and right 3.5rem? I think it gives it more breathing space plus it's more consistent with what the large screen size menu looks like. 
Screen Shot 2022-04-06 at 6 40 30 AM

**Comment by beccaklam** [comment]
- [ ] Also, on medium screen sizes the menu is still going full height? Can we fix that to be auto-height like how it does on desktop?

**Review by beccaklam — APPROVED** [review]
@fessehaye Thank you for all the changes! This is ready to go from design! 🚢 🥳 🙌

**Review by danielfmiranda — APPROVED** [review]
Hey Simon thanks for taking this on! it looks great, I have taken a look at the example and at the code and am approving! 👍

**Pull request merged**
