### PR TITLE
Fixes so a narrow campaign page doesn't look horrible if it ever happ…

### PR DESCRIPTION
**Pull request by ScottDowne**
Fixes https://github.com/mozilla/foundation.mozilla.org/issues/1564

### CODE REVIEW

**Comment by kristinashu** [comment]
I'm not sure how to check this? It looks good on https://foundation-mofostaging-pr-1562.herokuapp.com/campaigns/single-page/ but it looked good last time too. I need a way to see it as though the "Narrowed page content" is checked off. @alanmoo any suggestions?

**Comment by ScottDowne** [comment]
@kristinashu I logged into it and made that page narrow, now looks like this https://foundation-mofostaging-pr-1562.herokuapp.com/campaigns/single-page/

**Comment by kristinashu** [comment]
Thanks! https://foundation-mofostaging-pr-1562.herokuapp.com/campaigns/single-page/ and https://foundation-mofostaging-pr-1562.herokuapp.com/campaigns/multi-page/ both look less broken now. It it isn't ideal but definitely a better fallback than what we had. 

Here's the longer-term solution https://github.com/mozilla/foundation.mozilla.org/issues/1476

**Comment by alanmoo** [comment]
@cadecairos @patjouk There may be a bit more need for variable campaign pages.

@Pomax Handing this to you for review because you know the structure here. Might there be a need for simplification of the template complexities?

**Comment by alanmoo** [comment]
@gvn too for visibility because you may have thoughts on templates

**Comment by kristinashu** [comment]
Taís made these a little while ago to show the different template rules:

[Campaign Page (2 templates)](https://mozilla.invisionapp.com/share/6PH6YDCKSUT#/292486894_Campaign_Template)
[Opportunity Page (2 templates)](https://mozilla.invisionapp.com/share/SEH6YI72GKW#/292486895_Opportunitiy_Page_Template)

What isn't represented here is that /campaign should also be able to look like Opportunity pages (aka the url says `campaign` but it looks like an opportunity page - no petition form).

**Comment by ScottDowne** [comment]
I noticed there might have been a bit of a bug in some of the offset usage on narrow pages, which once fixed, allowed me to remove some of my changes. Testing now but I did push up the changes already.

**Comment by ScottDowne** [comment]
No wait that probably won't work, or isn't what I thought it looked like.

**Comment by ScottDowne** [comment]
@kristinashu question, in narrow content set pages, what should happen with the screen is 1200px+ wide? Should it stay narrow or just go large? I ask because the code seems to imply both, and it's kinda conflicting from what I can tell.

**Comment by ScottDowne** [comment]
I'm going to drop my changes, it's clear this is more of a mess than just applying some css.

**Comment by ScottDowne** [comment]
For any devs reading this, the conflict I'm seeing is here: `offset-md-2 col-lg-12` in mini_site_name_space.html offset-md-2 looks to apply a left margin offset on medium and above widths, which we then also say on lg and above make everything 12 wide. Meaning on large and above we have a total 14 units usage wide, which seems kinda busted from my understanding of bootstrap?

So I guess we can either remove the col-lg-12 and replace it with something that ends up as 8, meaning on large widths we're still narrow. Or stop enforcing narrow on 1200px wide screens by adding offset-lg-0.

If that's not making sense, think of it this way, col-lg-12 is implying we don't want to be narrow on large and up, and offset-md-2 is implying we do want to be narrow on medium and up. Am I reading this correctly?

**Pull request closed without merging**
