### PR TITLE
remove pillow dependency

### PR DESCRIPTION
**Pull request by Pomax**
While wagtail relies on pillow, we don't explicitly use it ourselves, and so we don't need it in our our pipfile

### CODE REVIEW

**Comment by cadecairos** [comment]
@Pomax can you rebase and fix the conflict so we can merge this?

**Comment by Pomax** [comment]
I can't really get the pip lock file to only update the pillow part and the master hash, a new venv ends up bumping some things automatically.

**Comment by Pomax** [comment]
Aparently, no rebasing/respinning I can do on my windows machine seems to fix this piplock issue.

**Comment by Pomax** [comment]
Redid the PR on current master.

**Comment by Pomax** [comment]
@cadecairos @patjouk just reset you for review, just to make sure we had eyes on it before merge =)

**Pull request merged**
