### PR TITLE
Added margin-bottom to CMS ul

### PR DESCRIPTION
**Pull request by youriwims**
Closes #2449 

The original PR #2443 referencing issue #1550 removed the site-wide `ul` reset rules whereas only the CMS `ul` needed to be updated with `margin-bottom`. So, this is a follow-up on PR #2449 which reverted the changes made in PR #2443 and updated the `margin-bottom` on CMS `ul` tags only.

cc: @mmmavis

### CODE REVIEW

**Comment by mmmavis** [comment]
Yea, will do after my morning meetings!

**Comment by mmmavis** [comment]
Ummm I took a look at the codebase and realized not all CMS generated content is wrapped in a `.cms` wrapper, so adding a rule for `.cms` won't cover everything. I will create a ticket to discuss whether or not we wanna keep the `.cms` class.

Since we wanna align CMS generated`ul` and `ol`'s styling, I think the prefer way of doing it is to

1.  remove `ul`'s reset rules in `resets.scss`
2. search through all `ul` elements in `*.html, *.js, *.jsx, *.py` in the codebase and modify their classname/SCSS rules where appropriate.

This way we don't have reset/override rules just for `ul` and not `ol`.

I'll create a PR just to show you what I meant. @youriwims let's chat tomorrow and see if you wanna pick up my to-be-filed PR or start a new PR on your own.

**Comment by Pomax** [comment]
Also note that the `.cms` class is for all CMS streamfield content. Not for any template code outside of that.

**Comment by youriwims** [comment]
Ref #2455

**Comment by youriwims** [comment]
Resolved in PR #2455

**Pull request closed without merging**
