### PR TITLE
7624 - Subcategories front-end styling for mobile

### LINKED ISSUE #7624: [PNI] - Subcategories -[PNI] - Subcategories - front-end styling for mobile
builds on https://github.com/mozilla/foundation.mozilla.org/issues/7623

- [x] hide category title
- [x] make "pill ribbon" h-scrollable
- [x] make selected category "be in view"
  - [x] if loading a page with subcat preselected, make sure that ends up in view
  - [x] if a user clicks a pill that's only partially on screen, move things so that it's 100% in view

> image

Figma comps: https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/Privacy-Not-Included-Website?node-id=1581%3A126777
prototype: https://www.figma.com/proto/GwdoUiY4fzVyeLfXsAJGPq/Privacy-Not-Included-Website?page-id=632%3A86321&node-id=1581%3A126777&viewport=241%2C48%2C0.54&scaling=scale-down&starting-point-node-id=1581%3A126777&show-proto-sidebar=1

### PR DESCRIPTION
**Pull request by fessehaye**
Includes front end stylings for mobile
Closes #7624 
Related PRs/issues #7746 

You do need to create subcategories on the test site via the admin account in order to test

### CODE REVIEW

**Review by sabrinang — CHANGES_REQUESTED** [review]
**Mobile**
- If the creep-o-meter face is relocating and we do not have a heading, can we reduce the gap above the checkbox so it is more balanced on mobile
- Subcategories scroll on mobile so it works but when I click on one, the search becomes active and my keyboard is triggered each time and the creep face gets pushed up too which makes it hard to browse products. See video:
https://user-images.githubusercontent.com/2492510/140180489-41ac3e12-0e09-42c4-b239-3f980f9ba827.mp4

**Desktop (narrow viewports)**
- the subcategories get cut off on some narrower viewports 
- not able to scroll sideways on desktop narrow viewports
BmONFDqCkG

**Review by sabrinang — CHANGES_REQUESTED** [review]
**Spacing**
- The mobile spacing looks good now but we lost the spacing above creep-o-meter that was added for desktop previously in https://github.com/mozilla/foundation.mozilla.org/pull/7712#pullrequestreview-794601034
image

**Hide Scrollbar?**
The scrolling works now but a big scroll appears now on...
narrow viewports:
image
and mobile:
https://user-images.githubusercontent.com/2492510/140402658-16ef9d7f-92e8-4c36-992d-8375ec652abe.mp4
- Is it possible to hide it while keeping the side scroll functionality?
- on narrow viewports, is it possible for the subcategories to extend to the edge of the page instead of being cut off at the container?

Thanks for fixing the keyboard trigger issue on mobile, it works way better!

**Review by sabrinang — APPROVED** [review]
Thanks for fixing the cut off issue and hiding the scrollbar! 👍 

I'll file a separate QA to be able to drag to scroll the subcategories to improve usability

**Comment by sabrinang** [comment]
I filed the QA drag to scroll issue here: https://github.com/mozilla/foundation.mozilla.org/issues/7787

**Review by danielfmiranda — COMMENTED** [review]
Hey Simon! Thanks for tagging me on this:

I took a look at the code and everything looks good to me, I did find one minor thing however I am not sure if it is by design: 

At the medium breakpoint the subcategories seem to get unaligned with the large category at the top: 
image

If this is to be expected, please let me know and I will approve the changes, thanks!

**Review by danielfmiranda — APPROVED** [review]
Hey Simon! Thanks for answering my questions, approved!

**Pull request merged**
