### PR TITLE
Disable applications

### PR DESCRIPTION
**Pull request by alanmoo**
Quick fix to disable applications until we can get a subscribe component up.

### CODE REVIEW

**Comment by alanmoo** [comment]
https://foundation-mofostaging-pr-1441.herokuapp.com/fellowships to review

**Comment by ScottDowne** [comment]
Only thing I can think of is on the main fellowship page, it says "Applications are open" and an "apply here" button which takes you to the page where it says "applications are closed" this might be an issue.

**Comment by alanmoo** [comment]
Great catch. Updated.

**Comment by taisdesouzalessa** [comment]
@auremoser the "not quick" version is being discussed on this thread here: https://github.com/mozilla/foundation.mozilla.org/issues/1135#issuecomment-381813446 :)

**Comment by auremoser** [comment]
Thanks for sharing! I'm sorry I should have checked the logs before asking.

**Comment by taisdesouzalessa** [comment]
No need to say sorry @auremoser :) I just know this issue exists because I wrote that ticket...haha!

**Pull request merged**
