### PR TITLE
Adding pulse-project-list component

### PR DESCRIPTION
**Pull request by gvn**
Related issue: #1191

### CODE REVIEW

**Comment by gvn** [comment]
@kristinashu for design review you can see the component here:

https://foundation-mofostaging-pr-1218.herokuapp.com/style-guide/

(Under *.pulse-project-list(for="QUERY")*)

Note: This is a query for "mozfest" and some projects have no thumbs and/or attribution.

**Comment by kristinashu** [comment]
Looks good to me @gvn!

**Comment by kristinashu** [comment]
Oh except what Abby just said about showing all the projects with that tag, not just 6.

**Comment by gvn** [comment]
Ok, there will be a lot, but I removed the default limit to 6.

There's probably going to be weird/bad data on staging because it's just staging data and not vetted very carefully.

**Pull request merged**
