### PR TITLE
Fixes to petition layout.

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by mmmavis** [comment]
The code change here will also increase the input field width on 1-column petition page from

screenshot-2018-2-14 mozilla foundation some water rate 1

to

screenshot-2018-2-14 mozilla foundation some water rate

I'd like to get designer's okay on making this styling changes here. /cc @kristinashu

**Comment by kristinashu** [comment]
Hmm the short field would be better here but if there's no way around it then the long fields are ok.

**Comment by ScottDowne** [comment]
Looking into it.

**Comment by xmatthewx** [comment]
good catch @mmmavis!!! those are some long input fields!! i tested on mobile, but didn't think of 1-column layout. i guess you can only do bootstrap relative to screen-size, not container size.

**Comment by ScottDowne** [comment]
I'm trying a fix where I make the container a bit smaller on the 1 column layout, to roughly match what it was agfter my change. This has the side effect of also making the checkbox labels line wrap if they are really long (but part of me thinks long checkbox input text is actually kinda not great either, so maybe two wins here?)

**Comment by ScottDowne** [comment]
My above solution makes 1 column layout terrible on mobile though.

I think I need help from Mavis to get this working in a bootstrapy way.

**Comment by ScottDowne** [comment]
Think I figured it out.

**Comment by mmmavis** [comment]
Since DOM elements in this codebase are super nested... I think a more future proof solution would be making the input fields as wide as their container. If we want fields look narrower, make the container narrower.

My suggestion would be changing the `col-md-6` class we applied to petition `<input>` to `w-100`.

screenshot-2018-2-14 mozilla foundation some water rate
screenshot-2018-2-14 mozilla foundation choose industry republican

**Pull request merged**
