### PR TITLE
fixing component width and icon size

### LINKED ISSUE #2726: Image Text Mini should be full width
Sorry I didn't catch this during QA but looks like this component isn't filling the container width. It looks good a narrower widths but isn't quite wide enough at the widest one.

Example https://foundation.mozilla.org/en/fellowships/apply/

image

cc @youriwims @Pomax @alanmoo

### PR DESCRIPTION
**Pull request by youriwims**
Closes #2726
Related PRs/issues #2694, #2722 

To test component:

1.  Visit this [link](https://foundation-mofostaging-pr-2728.herokuapp.com/en/opportunity/image-text-mini-test/).
2. Edit code in browser dev tools and wrap components code block below.

```
<div class="container cms">
       <div class="row my-1 d-flex align-items-center">
           <div class="col-md-8 offset-md-2">
                [components here] <----
          </div>
      </div>
</div>
```
3. Edit code _again_ in browser dev tools and wrap components in 2nd code block below.

```
<div class="container">
  <div class="row">
    <div class="py-5 col-md-3 mb-3 hidden-sm-down"></div>
    <div class="py-4 py-md-5 col-md-9">
       [components here] <----
     </div>
   </div>
</div>
```
*_This testing is to replicate the component's [use cases](https://github.com/mozilla/foundation.mozilla.org/issues/2693#issuecomment-467218857)._

### CODE REVIEW

**Comment by Pomax** [comment]
any STR that lets me set up a test?

**Comment by youriwims** [comment]
@Pomax , just updated the initial comment with testing instructions.

**Comment by Pomax** [comment]
nice, that looks pretty good to me.

**Comment by youriwims** [comment]
Just added a second use case, @Pomax can you check that one also to be sure really quick? Thanks!

**Comment by Pomax** [comment]
@youri can you make sure to make me as "review required" again in cases like these? That way it shows up in my work queue (https://github.com/pulls/review-requested) rather than getting lost in a comment.

**Comment by youriwims** [comment]
sure can.

**Pull request merged**
