### PR TITLE
Updated donate banner image and button link

### PR DESCRIPTION
**Pull request by danielfmiranda**
# Description

Related PRs/issues: #9824 

# Screenshots

### (XL)
Screenshot 2022-12-14 at 2 29 36 PM

### (L)
Screenshot 2022-12-14 at 2 29 51 PM

### (M)
Screenshot 2022-12-14 at 2 30 03 PM

### (SM)
Screenshot 2022-12-14 at 2 30 12 PM

### (XS) 
Screenshot 2022-12-14 at 2 30 22 PM

### CODE REVIEW

**Comment by danielfmiranda** [comment]
Hi @kristinashu! 

Following the request of ticket #9824, I have updated the donate banner to look similar to the one on https://www-demo4.allizom.org/en-US/ 

I was wondering if you or someone from design can please take a look at the screenshots above, and let me know if you would like any changes?

Thank you very much!

**Comment by kristinashu** [comment]
Looks good to me! The only thing that feels a little off are the three sentences as three separate paragraphs. Perhaps the first two could be grouped so it's:

>We're proudly nonprofit, working to keep the web healthy. Your contributions help build a safe and open internet.

> Can you donate today?

This way it will take up a little less vertical space as well since it seems like the banner is getting pretty tall.

**Comment by danielfmiranda** [comment]
Thanks, @kristinashu! I have updated the text and posted the updated screenshots in this ticket's description

**Review by mmmavis — APPROVED** [review]
Looks good!

**Comment by danielfmiranda** [comment]
Hi @kristinashu @mtdenton! 

This change has been pushed to staging and is ready for review at https://foundation.mofostaging.net/en/.

Thanks!

**Pull request merged**
