### PR TITLE
Fixing missing page titles

### LINKED ISSUE #2367: Subpage titles are missing in title tag
**Repro:** Go to any subpage and look at the title. It shows `Mozilla Foundation - `.
**Expected:** Add the subpage title after the hyphen.

screen shot 2018-12-19 at 10 40 54 am

### PR DESCRIPTION
**Pull request by youriwims**
Closes #2367 
Related PRs/issues #1262

View the app, to test.

### CODE REVIEW

**Comment by youriwims** [comment]
By changing title to `{{page.title}}`, all seems to be fixed. However there's still this [line](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/models.py#L151) in models. Do we want to remove that or rewrite it so that we're able to use `page.meta_title` instead?
cc: @Pomax @mmmavis

**Comment by mmmavis** [comment]
I don't know enough to confidently answer your q, @youriwims. @Pomax 👀 ?

**Comment by Pomax** [comment]
We should use the meta title, if it exists.

**Comment by youriwims** [comment]
@Pomax ,worked with Gideon on this yesterday and the fix worked. Any clue why it may not be working now?

**Comment by Pomax** [comment]
This seems to work fine, though, where are you seeing it not work?

**Comment by youriwims** [comment]
Title also appears on 404 page now as well. @Pomax 

Screen Shot 2019-04-02 at 1 44 03 PM

**Pull request merged**
