### PR TITLE
removed the custom GA event when adding clipboard functionality

### PR DESCRIPTION
**Pull request by Pomax**
Closes https://github.com/mozilla/foundation.mozilla.org/issues/4589

### CODE REVIEW

**Comment by mmmavis** [comment]
Ummm I still see double click handlers being attached: 
image

**Comment by Pomax** [comment]
@mavis that's very strange... are you sure you rebuilt the bg-main.js and have cache disabled?

**Comment by Pomax** [comment]
@mmmavis remember to "prettify" the source: line 26 is a few million characters long, but after prettifying, we see this:

image

One is the click handler for the clipboard copy, the other is the GA click handler =)

**Comment by mmmavis** [comment]
Heh! Good point! R+

**Pull request merged**
