### PR TITLE
[7435] add tito ticket complete webhook

### LINKED ISSUE #7435: Epic: Mozfest ticket purchaser opt in for subscriber email
### Describe the feature request
We have not yet estimated this feature. This is not MVP for the tito embed widget for mozfest.

Per Marc:
This is to address data collection for MozFest, and one of the problems we’re trying to solve together is firing off a double opt-in email to those that want to subscribe to the MozFest / Mozilla newsletter when purchasing a ticket.
Would it be possible to look into using the functionality we’re building into the site with TiTo’s widget to call the basket API and add the user details to a list, if they’ve opted in to really solidify the sign up process? 

### Additional context
From Jackie who heads the data team:
the CRM + data team is currently exploring a number of technical pathways to supporting the near term need of having Tito sign-ups trigger the sending of the double-opt-in email via Basket to Acoustic.

I was chatting with Marc about another issue, and along the way I realized that there is front-end dev work happening to embed ti.to on the MozFest site, and suggested that we explore this as another implementation option that we can all consider.  the scope of this would be to only post to the Basket newsletter API based on the person selecting a checkbox that they would want to sign-up for email marketing.

in the medium term, MoFo should start consolidating data about how people interact with us across various front-end platforms, in the data model that is in Cinchy, so we can start building out that elusive “cross-org” or “customer 360" view of how people interact and engage with us (aka movement metrics).   however, in order to do that, we would need to build a more robust data integration across these platforms, but at our current level of resourcing / backlog, that is not feasible to even consider doing before MozFest sign-ups open.

### PR DESCRIPTION
**Pull request by richbrennan**
Closes #7435 

**Link to sample test page**: https://mozfest-foundation-s-7435-featu-ixc3yh.mofostaging.net/en/tickets/

Steps to test:

1. Go to page, click Get Tickets and fill out payment form
2. Choose to allocate ticket and click the checkbox for "_Check the box below to be added to our Mozilla Festival list and be the first to know about the latest news and updates from the festival. You'll also be joining our Mozilla news list to stay informed in the fight for a better internet for all._"
3. Submit the form and check email for "Action Required: final step" email. I think it'll only be sent once per email address. See screenshot below for example.

Caveats:

1. Due to time constraints this PR does not include tests, documentation or logging. Also, the J[S](https://github.com/mozilla/foundation.mozilla.org/pull/7938/files) added for the previous Tito ticket needs to be removed. If this PR is approved I'll create a separate ticket for this.
2. Ideally the code would be refactored with less coupling, and include error handling for the Basket API call.
3. This covers the use case where the user completes a ticket and signs-up for the newsletter. It does not cover the potential use case where someone edits their ticket and unchecks the sign-up.
4. It only caters for one Tito event at a time, and assumes there is only one field for signing up to a newsletter. Support for multiple Tito events will require more work.

## Checklist

**Tests**
- [ ] Is the code I'm adding covered by tests?

**Documentation:**
- [ ] Is my code documented?
- [ ] Did I update the READMEs or wagtail documentation?

Screenshot from 2021-12-06 19-57-11

### CODE REVIEW

**Comment by Pomax** [comment]
I used the URL as indicated in your comment, clicked the button, ordered a virtual ticket, accepted the terms, filled in the necessary information, but did not see any checkbox with "_Check the box below to be added to our Mozilla Festival list and be the first to know [...]_" - finalizing the ticket then took me to https://www.mozillafestival.org/en/tickets/thank-you/ rather than the review app, so I'm unable to confirm this flow works as intended, even if the code looks good.

**Review by Pomax — CHANGES_REQUESTED** [review]
the code looks pretty solid, but I can't seem to run through the indicated workflow to manually test it.

**Comment by marcwalsh** [comment]
Just tested this out with two email addresses on two different orders, one where I opted-in to the newsletter and one where I didn’t. Both worked for me as expected. 

I received the double opt-in email only when I checked the box. 🎉

**Review by marcwalsh — APPROVED** [review]
This works for me. I tested with two different emails, one where I opted-in and another where I didn’t check the consent box. Both times worked as expected, and only received the double opt-in email after checking the newsletter box.

**Comment by richbrennan** [comment]
The Tito widget can be tested with the following credit card details:
Number: 4242 4242 4242 4242
Expiry: 06/22
CVC: 123
ZIP: 32003

**Review by fessehaye — APPROVED** [review]

**Pull request merged**
