### PR TITLE
8311 research hub library search

### LINKED ISSUE #8311: [RH] 3 - Library page - basic search
Implement a simple search feature for the research hub on the "research library" page. We can start with a simple implementation that updates the search results with a full page load. 

See also:
- [Research hub models](https://docs.google.com/document/d/19WoZxJvisMsHnXqA4GDX3Te6t9JnqAI2NG5jE9J4LP4/edit#)
- [Designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration)

***

**Acceptance criteria**

- [x] List all "research detail pages" when loading page without search query
- [x] Allow sorting 
  - [x] newest first
  - [x] oldest first
  - [x] alphabetically (a-z) 
  - [x] alphabetically reversed (z-a)
- [ ] When a search keyword is entered into the search input box, the list of displayed "research detail pages" is filtered down to the pages that include the search term. 
- [x] Only pages of the same locale as the locale of the request (current locale) are displayed. This makes sure that the search results would also be accessible via browsing on the page. 
- [x] When search filter is used, show total number of results for the search term.

### PR DESCRIPTION
**Pull request by tbrlpld**
Closes #8311
Related PRs/issues #

**Link to sample test page**: https://foundation-s-8311-resea-mkwg56.herokuapp.com/en/research/library/?search=rate&sort=alphabetical-reversed

## Checklist

_Remove unnecessary checks_

**Tests**
- [x] Is the code I'm adding covered by tests? -> Yes

**Changes in Models:**
- [x] Did I update or add new fake data? -> No. Existing data should be enough.
- [x] Did I squash my migration? -> No migrations added.
- [x] [Are my changes backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team? -> Yes.

**Documentation:**
- [x] Is my code documented? -> No.
- [x] Did I update the READMEs or wagtail documentation? -> No.

### CODE REVIEW

**Review by danielfmiranda — DISMISSED** [review]
Hi Tibor! Things are looking great, after taking a look at the acceptance criteria, I find that the page currently passes all but one:

**Acceptance criteria**

- [x] List all "research detail pages" when loading page without search query
- [x] Allow sorting 
  - [x] newest first
  - [x] oldest first
  - [x] alphabetically (a-z) 
  - [x] alphabetically reversed (z-a)
- [ ] When a search keyword is entered into the search input box, the list of displayed "research detail pages" is filtered down to the pages that include the search term. 
- [x] Only pages of the same locale as the locale of the request (current locale) are displayed. This makes sure that the search results would also be accessible via browsing on the page. 
- [x] When search filter is used, show total number of results for the search term.


For example, on the test page that you linked in the PR, there is a page called "Type Fill Hand Game". 

However when I enter the term 'type' in the search bar and click search, nothing appears to show up.


Other than that however, everything looks good to go front end and code wise. Great job!

**Comment by tbrlpld** [comment]
> For example, on the test page that you linked in the PR, there is a page called "Type Fill Hand Game".
> 
> However when I enter the term 'type' in the search bar and click search, nothing appears to show up.

That is so weird. There are a bunch of tests that should cover this and that do work.

**Comment by tbrlpld** [comment]
@danielfmiranda Not sure what went wrong before in the review app, but the newly deployed one works as intended: https://foundation-s-8311-resea-mkwg56.herokuapp.com/en/research/library/?search=rate&sort=alphabetical-reversed

**Review by danielfmiranda — APPROVED** [review]
Thanks for the update Tibor! Just gave it a second look and everything is working as expected. approved 👍

**Pull request merged**
