### PR TITLE
Localize creepiness labels in context

### PR DESCRIPTION
**Pull request by TheoChevalier**
Follow-up for #9881 by localizing the exclamation mark concatenated in the slider.

Interpolating the string with a placeable here allows to fully translate the string. This may seem over-engineered, but for example, Spanish will want to add `¡` before the label, French will want to add a non-breaking space before the exclamation mark.

### CODE REVIEW

**Review by mmmavis — APPROVED** [review]
Thanks for sharing your expertise and submitting this PR @TheoChevalier . Code looks good to me. I just have one question regarding if we should include a hardcoded punctuation `!` on line 123. Would love to hear what you think.

I'm going to merge this PR as is now because we are entering code freeze tmr for Wagtail version upgrade to take place. If you think this PR needs any further polish, please submit a PR and assign me as reviewer. Thank you!

**Comment by TheoChevalier** [comment]
Thanks for the review, @mmmavis! We do have a hardcoded `!` in `"%(label)s!"`, the gettext variable in just %(label)s. This is also because both are so close and it’s not easy to tell whether the ! is part of the variable or not that I’ve mentioned it in the comment for translators ;)

**Comment by mmmavis** [comment]
@TheoChevalier ah sorry I formed my sentence a bit weirdly.

>  I just have one question regarding if we should include a hardcoded punctuation ! on line 123. Would love to hear what you think.

I meant I was curious if including a hardcoded `!` was an ideal approach. I don't know much about localization and am curious if all languages are using `!` as the exclamation mark like what we use it for in English.

**Comment by TheoChevalier** [comment]
Ah, sorry! I get it now, let me start again.

Exclamation marks should always be part of a string (so, translatable) because there are indeed changes that will happen in some locales. Spanish for instance will want to add `¡` at the beginning of the sentence (e.g `¡Una frase!`), French will want to add a non-breaking space before the exclamation mark (e.g `Une phrase !`). These are the most obvious changes I’m aware, but translators could also decide to replace the exclamation mark with a period if they need to “tune down” the tone a bit so it feels more appropriate in their language, depending on the context.

**Comment by mmmavis** [comment]
@TheoChevalier thanks for the detailed explanation! 

> translators could also decide to replace the exclamation mark with a period if they need to “tune down” the tone a bit so it feels more appropriate in their language, depending on the context.

With `"%(label)s!"`, I'm curious how translators will be able to replace the hardcoded `!` with other punctuation marks. I assume they can only decide what string they want to show for the named interpolation "label"? I'm trying to wrap my head around our localization setup with Django. Thanks for having the patience to walk me through this.

**Comment by tbrlpld** [comment]
Is there an argument against moving the `!` into the strings? It seems like that would be more flexible and easier to reason about. 
 https://github.com/mozilla/foundation.mozilla.org/blob/1b0298d1a23c78f9696fc5e315627cb90f041c35/source/js/buyers-guide/components/creepiness-labels.js#L6-L12

**Comment by TheoChevalier** [comment]
> @TheoChevalier thanks for the detailed explanation!
> 
> > translators could also decide to replace the exclamation mark with a period if they need to “tune down” the tone a bit so it feels more appropriate in their language, depending on the context.
> 
> With `"%(label)s!"`, I'm curious how translators will be able to replace the hardcoded `!` with other punctuation marks. I assume they can only decide what string they want to show for the named interpolation "label"? I'm trying to wrap my head around our localization setup with Django. Thanks for having the patience to walk me through this.

They have access to everything between the quotes, here’s how it looks on the translation workbench where I was able to add a non-breaking space in the French translation:
Capture d’écran 2023-02-16 à 17 39 41

> Is there an argument against moving the ! into the strings? It seems like that would be more flexible and easier to reason about.

If if was the only context using these strings, no (it would be even preferable) but the strings are used in other places: https://github.com/mozilla/foundation.mozilla.org/search?q=CREEPINESS_LABELS

**Pull request merged**
