### PR TITLE
Related mini seals

### PR DESCRIPTION
**Pull request by Pomax**
Closes https://github.com/mozilla/foundation.mozilla.org/issues/2236 by adding the "seal of approval" to the related product images at the bottom of a product page.

### CODE REVIEW

**Comment by kristinashu** [comment]
This should be the mini seal like on the homepage, not the full seal. 

Screen cap from pr
image

**Comment by kristinashu** [comment]
Sorry, I should have caught this on the first round but I'm worried the product images will be really small. Could you make the padding less at narrower widths? Because most products have a gray background in their top left corner, it's ok if the seal overlaps the image a little.

image

**Comment by Pomax** [comment]
Does this look better?

image

**Comment by kristinashu** [comment]
Yes, looks better!

**Pull request merged**
