### PR TITLE
Add more PNI GA events

### LINKED ISSUE #5427: PNI - implement analytics for PNI homepage
Implement what's been defined in #5426

### PR DESCRIPTION
**Pull request by mmmavis**
Closes #5427

Implemented GA events listed in https://github.com/mozilla/foundation.mozilla.org/issues/5426#issuecomment-715572072. Note that we've been using `og:title` as the page title sent to GA (same text for all pages, `*Privacy Not Included: A Buyer's Guide for Connected Products`) and this PR changes it to using `<title>` (`*privacy not included - [category name/product name/about]`).

https://foundation-s-issue-5427-rryft3.herokuapp.com/en/privacynotincluded/

### CODE REVIEW

**Review by Pomax — APPROVED** [review]
R+ if we're fine with repeated clicks generating repeated GA events (which I think we already do anyway?)

**Review by taisdesouzalessa — CHANGES_REQUESTED** [review]
• For the "All" tap event (row 20 of [this spreadsheet](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit?usp=sharing)) it seems we are capturing what people are typing in the event label and I guess we don't want that, right? It seems too far on tracking...wonder what you think, Mavis.

image

• For the focus on search, I found 2 issues: 
1. if I type searching for 3 products it triggers 4 events (I think it is because it is focused 4 times, right? It is okay to keep as is if it is too difficult to track the exact amount of times people searched, just want to understand the limitations).
PNI-ga



2. If I click on the magnifying glass multiple times it triggers the event
PNI-ga-2

**Comment by mmmavis** [comment]
@taisdesouzalessa thanks for the review.

> For the "All" tap event (row 20 of this spreadsheet) it seems we are capturing what people are typing in the event label and I guess we don't want that, right? It seems too far on tracking...wonder what you think, Mavis.

image

This works as expected. In the sheet we specified that we wanna track the search query. We can change label to something else, depending on if we care more about the "not found" search query OR whether or not people use the All link.

> focus event gets fired multiple times

I'll look into this more. Is the primary goal to track whether or not people use the search box?

**Comment by mmmavis** [comment]
PR updated! Instead of tracking focus in search box, we tracks only on the **first keydown in search box** in the current session.

**Review by taisdesouzalessa — APPROVED** [review]
It is working for me. We are now tracking if users use the search box AT LEAST one time per session. Thanks, Mavis.

**Review by Pomax — APPROVED** [review]

**Pull request merged**
