### PR TITLE
Feature/8382 profile snippet

### LINKED ISSUE #8382: [RH] 1.1 - Rename and extend "content author" snippet
Change the existing “content author” model to be more generic and extend with more fields (currently only name and image). 
See also: https://docs.google.com/document/d/1lLWyF6-FgmoREokVY_zsymcpzFS1ElgAwW_wtQUV0go/edit

- Profile (snippet)
  - Fields
      - Name
      - Image
      - Tagline (e.g. for job description etc.)
      - Intro
          - Plain text (500 char)

**Acceptance criteria**

- [ ] The existing "content author" snippet is renamed to "profile"
- [ ] Previously existing "content author" snippets remain existing (with the new model name)
- [ ] All uses of the snippet are updated to the new name
- [ ] The factories are updated 
- [ ] Profiles are created automatically when new environment is setup
- [ ] Profile has all the necessary fields and all fields can be edited in the admin

### PR DESCRIPTION
**Pull request by tbrlpld**
This PR renames the existing `ContentAuthor` model to `Profile` and extends it. 

During testing we want to ensure two things:

1. Exiting instances of the "content author" model and relations to it remain in place during the migrations

    * Checkout out the `main` branch
    * Download the staging database `inv copy-stage-db`
    * Start the containers `docker compose up`
    * Navigate to a blog page on the frontend, also open the same page in the Wagtail admin
    * Stop the container <kbd>CTRL</kbd> + <kbd>C</kbd>
    * Checkout the feature branch `feature/8382-profile-snippet`
    * Start the container `docker compose up`
    * Run the migrations `inv migrate`. This should pass without errors. 
    * Reload the blog page in frontend and admin. Check that the previously linked author is still linked to the page. In the admin you will see the button text has changed from "content author" to "profile". 
    * Try editing a profile.
    * That should be working without issue

2. When setting up a new environment, the "profile" model instances are populated correctly. 

    * Keep the feature branch checked out.
    * Stop the container if running (<kbd>CTRL</kbd> + <kbd>C</kbd>)
    * Create a new database with fake data `inv new-db`. This should pass without error. 
    * Start the server `docker compose up`
    * Check the "profile" snippets in the Wagtail admin. For each profile, the "name", "tagline" and "introduction" field should be populated. 

***

The migration here might be backward incompatible. I am actually not sure. There is a special migration type `RenameModel`. But yea... I guess code that is referencing the old model name will break. @Pomax I am interested in your take here.

***

Closes #8382
Related PRs/issues #

**Link to sample test page**: https://foundation-s-feature-83-ffxzqj.herokuapp.com/cms/snippets/wagtailpages/profile/edit/1/

## Checklist

_Remove unnecessary checks_

**Tests**
- [x] Is the code I'm adding covered by tests? -> No

**Changes in Models:**
- [x] Did I update or add new fake data? -> Yes
- [x] Did I squash my migration? -> No. Because of the renaming, it feels safer to keep the rename and the extra fields in different migrations with a proper migration dependency definition.
- [ ] [Are my changes backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team? 

**Documentation:**
- [x] Is my code documented? -> No
- [x] Did I update the READMEs or wagtail documentation? -> No

### CODE REVIEW

**Review by Pomax — APPROVED** [review]
This looks pretty good to me - the lack of a rollback isn't all that important, given how often we need to roll back database schema changes (namely: unless prod catches fires, never).

**Review by Pomax — CHANGES_REQUESTED** [review]
ah, this will need a quick migration/dep renumber because of the fix to related blog posts introducing a 0005 migration

**Comment by tbrlpld** [comment]
> ah, this will need a quick migration/dep renumber because of the fix to related blog posts introducing a 0005 migration

I have updated the migration names to reflect this

**Review by Pomax — APPROVED** [review]
lgtm!

**Pull request merged**
