### PR TITLE
8493 - Update Article Page Summary Box Styling

### LINKED ISSUE #8493: [Interactive Report] Update Article Page Summary Box Styling
Update styling of the summary box on Article pages to show columns more clearly and hopefully encourage the proper reading direction of first column top to bottom --> second column top to bottom.

## Design to Dev Checklist
Original design ticket: #8445
[Redpen](https://redpen.io/p/ktf15c22e58d8530be) - Design 5
[Figma file](https://www.figma.com/file/P06Q7hWuILgc9g19AXcP39/Publications-template?node-id=526%3A25849)

- [ ] Update summary box backgorund to white with a Gray 20 stroke of 1px
- [ ] Padding for large and medium screens should be: padding top and bottom: 32px, padding right and left: 48px | Mobile padding should remain: padding: 32px 30px;
- [ ] Add divider of 1px in Gray 20 in the middle of the summary box, the height should match the content of the summary box. The padding on either side of the divider should be 48px for large and medium screens
- [ ] Keep two column split functionality (where if content items are over 5, split the items into two columns on large and medium screens) | Mobile should remain one column

### PR DESCRIPTION
**Pull request by fessehaye**
Closes #8493 

https://foundation-s-8493-summa-hmumcg.herokuapp.com/en/publication-page-with-chapter-pages/fixed-title-chapter-page/fixed-title-article-page

### CODE REVIEW

**Review by beccaklam — DISMISSED** [review]
This looks good to go! Just one little change:

- [ ] Change hover state to dark blue

**Review by danielfmiranda — DISMISSED** [review]
Hi @fessehaye! This looks great and almost ready to go, there was only one small thing that I found where I was wondering if we would be able to update before merging this in:

- I noticed that in some screen sizes, some of the list items bleed over into the other column of the two column layout. In the screenshot below, its the title "History onto second prepare reduce short". 

Screen Shot 2022-03-31 at 1 38 56 PM

Besides that, everything is looking great and ready for approval!

**Review by beccaklam — CHANGES_REQUESTED** [review]
Hi Simon!

Aside from Daniel's bug (the titles spilling over) the changes you've implemented look good. One really small nit picky thing:

- [x] Can we remove the underline on the hover state? I think it was there because the text didn't change color before, but since it turns blue now I think we no longer need it. Thank you and sorry for not mentioning it the first time!

**Review by beccaklam — APPROVED** [review]
Hi Simon! Thanks for removing the underline and the title spilling into the next column is fixed! This is good to go! 🚢

**Review by danielfmiranda — APPROVED** [review]
Hey Simon thanks for tagging me in this! After taking a look at the code and the review site, everything looks great. Approving! 👍

**Pull request merged**
