### PR TITLE
Update .body-small and .h6-heading colours to $gray-60

### LINKED ISSUE #4136: Update body-small and H6-heading colour
Update body-small and H6-heading colour so it has better contrast for reading. From $gray-40 `#999999` to $gray-60 `#666666`

- See design ticket: https://github.com/MozillaFoundation/Design/issues/422#issuecomment-573912124
- Sketch library type styles have been updated and merged in Abstract

### PR DESCRIPTION
**Pull request by mmmavis**
Closes #4136 

- see updated [styleguide](https://foundation-s-issue-4136-k4dakf.herokuapp.com/en/styleguide/)
- use Percy to see these style changes in context (in dummy pages)

### CODE REVIEW

**Comment by Pomax** [comment]
It looks like this change also affected the coloring of text in the footer, making it much harder to see. Was that supposed to happen? /cc @kristinashu

**Comment by Pomax** [comment]
ex: the consent text below the sign up form, and the right column footer text

Screen Shot 2020-02-18 at 9 43 33 AM

**Comment by mmmavis** [comment]
@sabrinang can you help address @Pomax 's comment?

**Comment by sabrinang** [comment]
From https://github.com/MozillaFoundation/Design/issues/422#issuecomment-573912124
h6-heading dark-theme and body-small dark theme (`#999999`) to keep contrast as it was previously

**Pull request merged**
