### PR TITLE
Regrets Reporter Extension landing bottom half 

### LINKED ISSUE #7794: Create the 3 column "bottom half" of the page
Depends on #7792
This landing page has two main sections, the bottom half houses:

- [x] Control your recommendations text
- [x] Avoid harmful content text
- [x] Help solve the problem text 
- [x] Content is wrapped in {% trans %} and {% blocktrans %} tags

These 3 sections should be evenly spaced, and be responsive at multiple breakpoints. 

Figma design can be found here: https://www.figma.com/file/A0TYlvLzKxnQLZr3unohQy/YouTube-RegretsReporter---product-page-test?node-id=232%3A1216
To see how this page should format in desktop/tablet/mobile breakpoints.

### PR DESCRIPTION
**Pull request by danielfmiranda**
Closes #7794 
Related PRs/issues: Depends on #7832 

**Link to sample test page**: https://foundation-s-yt-regrets-hbwxss.herokuapp.com/en/youtube/regretsreporter/

**Steps to test**: 

1. Please visit the test link above, which should take you to the landing page for the regrets reporter extension
2. At the moment, the page should just display the 3 column text content, which then turns into 2 columns from large -> small breakpoints, then to 1 column on mobile.
3. If the text and the formatting looks OK, testing is complete! 

Link to figma comp for comparison: https://www.figma.com/file/A0TYlvLzKxnQLZr3unohQy/YouTube-RegretsReporter---product-page-test?node-id=232%3A1216

### CODE REVIEW

**Comment by danielfmiranda** [comment]
Hi @kristinashu! I have a quick question regarding the links for this page.

According to the figma comp, there are two links on the page, and I was not sure where they were supposed to link to so I made my best guess:

The text "**Research powered by Mozilla’s RegretsReporter has revealed**" links to: https://foundation-s-yt-regrets-hbwxss.herokuapp.com/campaigns/regrets-reporter/findings

and the text "**in September 2020**" links to: https://foundation-s-yt-regrets-hbwxss.herokuapp.com/campaigns/regrets-reporter



Is this correct? If not, please let me know and I can update them with the correct URLs. Thank you!

**Comment by kristinashu** [comment]
Hi @danielfmiranda, sorry but I'm not sure about those links (I think the urls will be updated). @beccaklam will be back on Monday and can review this then. Will this text be update-able in the CMS?

**Review by fessehaye — APPROVED** [review]

**Review by beccaklam — CHANGES_REQUESTED** [review]
Hi @danielfmiranda! Thanks for flagging about the links and sorry I didn't provide those earlier. The "**Research powered by Mozilla’s RegretsReporter has revealed**" link is correct but the "**in September 2020**" link should go to https://foundation.mozilla.org/blog/mozilla-crowdsourcing-research-youtube-recommendations/ I also added a link to the copy doc in the [hand off doc](https://docs.google.com/document/d/1thbfPHqK6Nn0aZ9WdQqGPMRs32scqA2ED9c4NCQbrEw/edit#) (under the figma link) for future reference if it's needed. Otherwise the text formatting looks good to me!

**Comment by danielfmiranda** [comment]
Hi @beccaklam thank you for your feedback! 

I have updated the links with the links that you sent me and rerequested review 😄, however, I did want to note that since it is linking to a blog page that was creating on the live foundation site, my review site will return a 404. However, on the foundation site, it will link correctly. Thanks!

**Review by beccaklam — APPROVED** [review]
The link looks good to me! Thanks @danielfmiranda!

**Pull request merged**
