### PR TITLE
updated/reordered CMS fields, removed price field, removed hint text

### LINKED ISSUE #7614: [PNI] Update naming in CMS
Based on https://github.com/mozilla/foundation.mozilla.org/issues/7578

We've audited and aligned the titles in spreadsheet so they match the front-end of the site and now the CMS needs to be update to align as well.

- [x] Remove hint text (for easy scanability) 
- [x] Update titles so they match the [spreadsheet](https://docs.google.com/spreadsheets/d/1LBEYx6DrYClG0pFkfwLdCZN3KzHRuMgMTjZBqPGD2sg/edit#gid=1764292170) 
- [ ] Zoom call with a designer to review any inconsistencies or questions

### PR DESCRIPTION
**Pull request by danielfmiranda**
Closes #7614 

In this PR I did the following: 
- [x] Remove hint text (for easy scanability) 
- [x] Update titles so they match the [spreadsheet](https://docs.google.com/spreadsheets/d/1LBEYx6DrYClG0pFkfwLdCZN3KzHRuMgMTjZBqPGD2sg/edit#gid=1764292170) 
- [x] Remove Price field from CMS 
- [x] Use 'Yes' for Thumbs Up, 'No' for Thumbs Down, and 'Unknown' for Thumb Sideways
- [x] Reordered the CMS fields to align with the data entry sheet

### Test Pages:
**Link to test General Product Page in the CMS:**https://foundation-s-7614-updat-nn3k3e.herokuapp.com/cms/pages/73/edit/
**Link to test Software Product Page in the CMS:**https://foundation-s-7614-updat-nn3k3e.herokuapp.com/cms/pages/74/edit/

**Steps to test:**

1. Using the credentials in the #mofo-ra-foundation channel, please visit both pages linked above to view the updated names and order in the CMS.
2. The order of the fields should now match the order in https://docs.google.com/spreadsheets/d/1LBEYx6DrYClG0pFkfwLdCZN3KzHRuMgMTjZBqPGD2sg/edit#gid=1764292170.
3. If everything looks as expected, testing is complete!

### CODE REVIEW

**Comment by danielfmiranda** [comment]
Hi @kristinashu! 

Wanted to mention that ":" are appended by wagtail, so we are unable to remove them, unless the field name is ending with a "?", in which wagtail will display it in the CMS as a question

**Comment by kristinashu** [comment]
WOW I just entered a product using real content and it was so much easier and way way way faster! Even just having the category higher up on the page helped a bunch. 

I've only noticed a couple things:

You added a character limit to the blurbs. I did list a recommended max character count for those but that was guidance for Jen, which she has gone way over on so unfortunately we can't have a firm character limit in the cms or that will be a big blocker for content entry.
- [ ] Remove character limit from blurbs 

You did match "Time spend on research" to the spreadsheet but I actually think it should be hire up in the CMS to better reflect the front-end design (I can ask Jen to move it up in the spreadsheet to match the design as well).
- [ ] Move "Time spend on research"  up to to it's just above "Mozilla says"

That's it! Thank you, this will make content entry so much smoother!

**Review by sabrinang — CHANGES_REQUESTED** [review]
**Mozilla Says:**
Should the dropdown labels be `Thumbs Up`, `Thumbs Down`, `Thumb Sideways` directly instead of in the help text?

**Ai is untrustworthy helptext:**
I don't see this as a row on the spreadsheet, is it needed as a field in the CMS?

**Validation Error**
For example, I've been getting _"Ensure this value has at most 700 characters (it has 3260)."_ Many of the contents for `What could happen if something goes wrong?` goes over quite a bit when I use real content from the sheet. Some `Intro Blurb:` contents are also exceeding to cause the validation error. +1 to what Kristina said to removing it to accommodate Jen’s content

**re: what Kristina said about aligning with front-end design**
+1 to spreadsheet/field order to reflect front-end design top-down so things in the `General Product Details` can be reordered … ding, adult content, image, review date, mozilla says, wifi, bluetooth etc.

**Software Product Page**
It has different fields than the spreadsheet so I wasn’t sure if there is another spreadsheet I should refer to to review the Software Product pages. Are they still intentionally different?

Overall, this improves the content entry process and experience so much! I'm excited for this update to make things smoother and more efficient too!

**Comment by kristinashu** [comment]
Thank you so much Sabs!


### Mozilla Says:
> Should the dropdown labels be `Thumbs Up`, `Thumbs Down`, `Thumb Sideways` directly instead of in the help text?

This is a big lift so we need to just use the help text.


### Ai is untrustworthy helptext:
> I don't see this as a row on the spreadsheet, is it needed as a field in the CMS?

Good point! I think "General AI description" and "Ai is untrustworthy help text" are redundant
- [ ] Remove "Ai is untrustworthy helptext:" field


### Validation Error
> For example, I've been getting _"Ensure this value has at most 700 characters (it has 3260)."_ Many of the contents for `What could happen if something goes wrong?` goes over quite a bit when I use real content from the sheet. Some `Intro Blurb:` contents are also exceeding to cause the validation error. +1 to what Kristina said to removing it to accommodate Jen’s content

+1 this is the same as the remove max char limit


### re: what Kristina said about aligning with front-end design
> +1 to spreadsheet/field order to reflect front-end design top-down so things in the `General Product Details` can be reordered … ding, adult content, image, review date, mozilla says, wifi, bluetooth etc.


### Software Product Page
> It has different fields than the spreadsheet so I wasn’t sure if there is another spreadsheet I should refer to to review the Software Product pages. Are they still intentionally different?

The Software Product pages are no longer used and will be removed so we I think we can ignore it now

**Comment by danielfmiranda** [comment]
Hi @kristinashu @sabrinang thank you for the kind feedback! I have implemented the requests found in the comments and re-requested review 😄

**Review by kristinashu — APPROVED** [review]
Looks good! Thank you Daniel! Really hoping this can land in time for the big content entry push tomorrow. It really will make things so much faster for us.

**Review by sabrinang — APPROVED** [review]
👍 Thanks for the updates Daniel!

**Review by Pomax — CHANGES_REQUESTED** [review]
Looks good, but this will need migrations renumbered before final approval

**Review by Pomax — APPROVED** [review]

**Pull request merged**
