### PR TITLE
Updated fellowships homepage content and layout again

### LINKED ISSUE #1120: [Fellowship mini site] new 'homepage' content implementation
@mmmavis - this page is ready to ship! 

InVision file: https://invis.io/ZJ9YTAGEA#/281947967_v2-FellowshipsUI_-_Overview
Doc file: [this doc](https://docs.google.com/document/d/1irQDK5IrRRuBa_Bq4sVOkaD9iHIYxD-cPyUGY_UOuY8/edit?usp=sharing)

here are the assets:
1. Group picture has changed dimensions "Why become a Fellow" (it was a square, now it is a rectangle to accommodate new content). [Link to the asset](https://drive.google.com/open?id=1KzgPJDJoAYnDvkd7KhB0Qqz85q3dvvAJ)
2. All svgs used in this page [are here](https://drive.google.com/open?id=178x7FtDEX3y_plm2irftituGaQTfdbGS). Names of the files: "illustration-personal-data.svg", "illustration-open-scientific-research.svg", "illustration-connect-unconnected.svg" and "illustration-artificial-intelligence.svg"
3. [Sketch file](https://drive.google.com/open?id=15st_Yd-GS4nAFgqqp-ci8QU1g4pWLdWr): please notice that the copy of the grey box "Applications are open" changed (as per Jesse's suggestion)
 
NOTE: for mobile view, let's keep as we have it in the live version: illustration on top of copy.
Also please notice the titles follow the pattern of the "[Support the Program](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/support/)" page

image

### PR DESCRIPTION
**Pull request by mmmavis**
Fixed #1120 , #1124

### CODE REVIEW

**Comment by mmmavis** [comment]
@taisdesouzalessa 👀 ? https://foundation-mofostaging-pr-1122.herokuapp.com/fellowships mobile mockup is outdated so I updated things based on my own judgement. Let me know if anything needs adjustment.

**Comment by taisdesouzalessa** [comment]
@mmmavis all good on the design end.
The only things that are missing are the links on the section "why become a fellow" - the links are in this doc: https://docs.google.com/document/d/1irQDK5IrRRuBa_Bq4sVOkaD9iHIYxD-cPyUGY_UOuY8/edit?usp=sharing

The link "Meet the Mozilla Fellows" links to our directory page.

**Comment by mmmavis** [comment]
@taisdesouzalessa kk thanks for spotting bugs!

**Comment by mmmavis** [comment]
@gvn I fixed the bug @taisdesouzalessa mentioned. Passing this to you for code review now.

**Pull request merged**
