### PR TITLE
updated article callout fields

### PR DESCRIPTION
**Pull request by danielfmiranda**
# Description
Related PRs/issues: #9987

This PR updates the fields available for use in the Article Page's "Callout" block to include the following:

- Italic
- Bold
- H2
- H3
- H4
- Numbered list
- Bullet list
- Links

This PR also includes the necessary migration file for these changes to take place.

# Screenshot
**Block on the frontend:**
Screenshot 2023-02-07 at 11-43-17 Fixed title article page

**Fields in the CMS:**
Screenshot 2023-02-07 at 10-41-30 Wagtail - Editing Article page Fixed title article page

### CODE REVIEW

**Comment by kristinashu** [comment]
Thank you @danielfmiranda for doing this so quickly! Feel free to do this as a follow up ticket but would it be possible for the text in the numbered and bulleted lists to be the same font size as the rest of the text in the call out? The text in the lists look a little smaller in the screen cap than the body above and below.

**Comment by danielfmiranda** [comment]
Hi @kristinashu! 
No problem, I have updated the font size to be the same as the rest. Here are some screenshots to show the difference:
 
**(After Update ):**
Screenshot 2023-02-07 at 11-43-17 Fixed title article page

** (Before Update):**
Screenshot 2023-02-07 at 10-38-30 Fixed title article page

**Comment by kristinashu** [comment]
Looks good, thank you Daniel!

**Review by mmmavis — APPROVED** [review]
✨

**Pull request merged**
