### PR TITLE
7374 - Added Category Bubbles

### LINKED ISSUE #7374: [PNI] Product page - header updates: add category bubbles
- [ ] Add category tags to the `product_page.html` template, linking to their respective category URLs (same ones as used in the nav)
- [ ] Styling: same style as `.body-small` _(body small = H6 lowercase)_

Relevant part of the product page comp:

image

Comps on figma: https://www.figma.com/proto/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?page-id=548%3A72128&node-id=611%3A77813&viewport=283%2C48%2C0.08&scaling=min-zoom&starting-point-node-id=611%3A77813

### PR DESCRIPTION
**Pull request by fessehaye**
Closes #7374 
Screen Shot 2021-09-16 at 2 36 17 PM

### CODE REVIEW

**Review by danielfmiranda — APPROVED** [review]
Hey Simon! Just tested this out on the staging app and can confirm that everything seems to be working correctly. The categories pop up, and they also link to their respective category pages. 

Approved! 👍

**Review by sabrinang — COMMENTED** [review]
@fessehaye Do you have the specific sample test page URL I should review? When I go to https://foundation-s-7374-bubbl-qhykcf.herokuapp.com/en/privacynotincluded/ and click on a product it is `Bad Request (400)` for me.

**Review by sabrinang — CHANGES_REQUESTED** [review]
Reviewed: https://foundation-s-7374-bubbl-qhykcf.herokuapp.com/en/privacynotincluded/turn-author-defense-evidence-perform/

- the category bubble is a bit close to the title, can we add margin-bottom: 1 rem ?

**Review by sabrinang — APPROVED** [review]
👍 Great, thanks for adding the space between

**Pull request merged**
