### PR TITLE
update wagtail to 2.14.1

### PR DESCRIPTION
**Pull request by Pomax**
Closes https://github.com/mozilla/foundation.mozilla.org/issues/7503

STR:
- checkout main
- run `inv new-env`
- checkout this branch
- run `inv catchup` (which will uplift the local testing db)
- run `inv test-python` to verify there are no errors

STR part 2:
- checkout main
- run `inv new-env`
- set up your local db to be a copy of the staging or production database
- checkout this branch
- run `inv catchup` (which will now apply to "real" data)
- run `docker-compose up` and poke around the CMS and pages a bit to make sure nothing broke

@TheoChevalier I've added you as reviewer mostly for the localize-ness, I had to updated wagtail-localize-git to 0.10.0 but as far as I can tell that should have been fine.

### CODE REVIEW

**Comment by TheoChevalier** [comment]
> @TheoChevalier I've added you as reviewer mostly for the localize-ness, I had to updated wagtail-localize-git to 0.10.0 but as far as I can tell that should have been fine.
Yup, 0.10.0 is only about supporting 2.14, very limited risk here. I’ve already played with 2.14.1 quickly locally, but will do more thorough testing tomorrow, with actual data too. I expect everything to work better, but you never know!

**Comment by danielfmiranda** [comment]
Hi Pomax, I tried to take a look at this PR and test it out, but an issue I am experiencing with the inv copy-stage-data command (documented in ticket #7522) is preventing me from testing this fully!

**Review by TheoChevalier — APPROVED** [review]
Couldn’t find any issue!

**Review by danielfmiranda — APPROVED** [review]
Hi @Pomax just tested and can confirm that everything is working. Approved!

**Pull request merged**
