### PR TITLE
Ensure unclassed headings have the proper fonts

### LINKED ISSUE #1329: Wagtail QA: Heading Styles
From @kristinashu  in #1325 

- will [this](https://github.com/mozilla/foundation.mozilla.org/pull/1324#issuecomment-380906497
) fix the heading styles here too?

### PR DESCRIPTION
**Pull request by alanmoo**
I think this fixes #1329

### CODE REVIEW

**Comment by gvn** [comment]
Fine with me as long as these are the defaults that Design wants to roll with...

**Comment by alanmoo** [comment]
@kristinashu @taisdesouzalessa Does this make sense? The richtext field outputs raw `h2, h3, h4` etc so these are the styles that will be applied to those elements when used in those fields.

**Comment by kristinashu** [comment]
@alanmoo sorry, what do you mean? What does raw `h2, h3, h4` end up looking like on the site?

**Comment by kristinashu** [comment]
Ideally a user would be able to chose a heading or paragraph style in the editor and then it would look like one of these on the site:

image

The names don't have to align. For example it could just be `h3` in the editor but on the site it should look like `.h3-heading` style.

**Pull request merged**
