### PR TITLE
Download links

### LINKED ISSUE #6999: [YouTube Regrets 2021] Insert missing links
We need to add links to files. 

The link we want to use is this one: https://assets.mofoprod.net/network/documents/Mozilla_YouTube_Regrets_Report.pdf

## Acceptance criteria:
- [ ]  
the hero CTA needs a link to the pdf. 
- [ ]  
The footer (subfooter?) CTA needs a link to the pdf.

### PR DESCRIPTION
**Pull request by KalobTaulien**
Closes #6999 

**Link to sample test page**: https://foundation-s-6999-inser-1yhlbj.herokuapp.com/youtube-regrets-2021/

### CODE REVIEW

**Comment by KalobTaulien** [comment]
@danielfmiranda Can you code review this?
@kristinashu Can you make sure the red "Download" buttons (one at the top of the page one at the bottom of the page) are linking to the _correct_ file?

**Comment by kristinashu** [comment]
It is linking to the correct PDF!

However there is a in body link to the PDF as well at the end of the recommendations sections that currently links out to something else. 

image

**Review by danielfmiranda — APPROVED** [review]
Hi Kalob! Just tested and confirmed that it links to the correct URL, I also gave the code a look through and everything looks good to go! 

Approving 👍

**Comment by KalobTaulien** [comment]
@kristinashu Thank you for catching that! I'm not as familiar with the content. I've updated that link in the body [visible here](https://github.com/mozilla/foundation.mozilla.org/pull/7001/files#diff-f0b687e6b5dc2d16416627d1ead084c5662c8c7593474d1ad0f71dce76718c66R13)

**Review by kristinashu — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
