### PR TITLE
add table block to streamfield, contingent on ENABLE_TABLE_BLOCK

### PR DESCRIPTION
**Pull request by Pomax**
Addresses https://github.com/mozilla/foundation.mozilla.org/issues/2660 - I couldn't find a way to change row/col count using the keyboard, but right click with a mouse offers some options there.

Example of page with a table: https://foundation-mofostaging-pr-2662.herokuapp.com/en/campaigns/action-lose-treatment/

Edit route (please see the mofo-review channel for the admin password for app 2662): https://foundation-mofostaging-pr-2662.herokuapp.com/cms/pages/16/edit/

### CODE REVIEW

**Comment by Pomax** [comment]
There is a CI error about migrations, and I'm not sure where it's coming from, given that the PR includes the necessary migration as far as `inv makemigrations` can tell.

**Comment by patjouk** [comment]
```
  …/code/network  nix-shell     table-block  inv manage makemigrations                                    1 ↵
Loading .env environment variables…
Migrations for 'wagtailpages':
  network-api/networkapi/wagtailpages/migrations/0045_auto_20190215_1003.py
    - Alter field body on modularpage
    - Alter field body_de on modularpage
    - Alter field body_en on modularpage
    - Alter field body_es on modularpage
    - Alter field body_fr on modularpage
    - Alter field body_pl on modularpage
    - Alter field body_pt on modularpage
    - Alter field body on primarypage
    - Alter field body_de on primarypage
    - Alter field body_en on primarypage
    - Alter field body_es on primarypage
    - Alter field body_fr on primarypage
    - Alter field body_pl on primarypage
    - Alter field body_pt on primarypage
```
Seems like it's missing a migration. Can you try running `inv makemigrations` again?

**Comment by Pomax** [comment]
If I run it locally it tells me there are no changes.

The weird thing is that https://github.com/mozilla/foundation.mozilla.org/blob/table-block/network-api/networkapi/wagtailpages/migrations/0044_auto_20190214_1003.py indeed exists, it's in this branch, and its dependency is the also existing https://github.com/mozilla/foundation.mozilla.org/blob/table-block/network-api/networkapi/wagtailpages/migrations/0043_auto_20190108_2000.py so Django _should_ be able to discover it as being part of the migrations chain.

**Comment by Pomax** [comment]
I did a database wipe, removed the migration that was on this branch, migrated a clean db, then ran `migrate` to regenerate that 0044, hopefully this time it gets recognised?

**Comment by Pomax** [comment]
The only thing different I can see is that rebuilding it updated the Django timestamp so I'm not sure this'll do much... if this fails I'll probably try to redo this in a new branch. https://github.com/mozilla/foundation.mozilla.org/commit/e6c9e5d86fb99d61a18adcea5e1541031045b038

**Comment by Pomax** [comment]
Yeah I think the width is some weird built-in-default-styling aspect of `th` elements inside a table. We're probably going to want to play around a little with what kind of presentation mode tables should actually use.

**Comment by Pomax** [comment]
Closing this PR, as it turns out airtable embeds work perfectly fine, and are infinitely more expressive than the table component would be.

**Pull request closed without merging**
