### PR TITLE
7830 - Width is broken on mobile product pages

### LINKED ISSUE #7830: [PNI QA] Width is broken on mobile product pages
### Describe the bug
Something is breaking the layout on mobile. The content shifts sideways and I see a black bar in some sections.

### To Reproduce
1. Go to any product page https://foundation.mozilla.org/en/privacynotincluded/threema/
3. Scroll down
4. See error: content will also scroll horizontally. 

### Expected behavior
Context should scroll vertically.

### Screenshots
image

### Smartphone
 - Device: iPhone 12 mini
 - OS: iOS 15.1
 - Browser: both Safari & Chrome

### PR DESCRIPTION
**Pull request by fessehaye**
Closes #7830

### CODE REVIEW

**Comment by kristinashu** [comment]
Product pages no long break out of the phone width but it seems like the content is now too narrow and looks a little cutoff. Is it possible to have the wider content but not break out?

Screen cap of PR with too narrow content:
image


Screen cap of product with the nicer wide content:
image

**Comment by kristinashu** [comment]
Hey, so the width of the tabs looks good now but there is now a black bar the whole way down.

Screen cap of PR on iPhone:
image

The top also seems a little off now. I think it's because there shouldn't be that white cutout box on mobile. 

Screen cap of PR on iPhone:
image

**Comment by kristinashu** [comment]
So the padding looks good again but I'm still seeing that black bar on the right side. I'm looking at https://foundation-s-7830-width-q38cta.herokuapp.com/privacynotincluded. 

image

**Comment by kristinashu** [comment]
So close! The extra sidebar is gone! The width of the creep-o-meter and the tabs themselves are looking good too. The only thing I see now is that the content within the tabs is narrower than before. If fixing that means breaking other things than I'm ok with the narrower content but if it is _easily_ fixed then please go for it.

Screen cap from PR

image

**Review by kristinashu — APPROVED** [review]
Yes, this looks good now! Thank you for your perseverance on this 😅. Ready for code review.

**Review by danielfmiranda — COMMENTED** [review]
Looks great Simon! Approved

**Pull request merged**
