### PR TITLE
added mozilla says section

### LINKED ISSUE #7378: [PNI] Product page - header updates: add Mozilla Says
- Add `Mozilla says`
  - [x] add tristate value (yes/no/meh) to ProductPage backend model
  - [x] add thumbs up/down/sideways icon. SVG icons here: https://drive.google.com/open?id=1Tbjh6VzA2WFQSKea1HYzI8sdP9lip9e9&authuser=sabrina%40mozillafoundation.org&usp=drive_fs
  - [ ] add copy and thumb icon element to the product page template
 
Relevant part of the updated product page comp:

image

Comps on figma: https://www.figma.com/proto/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?page-id=548%3A72128&node-id=611%3A77813&viewport=283%2C48%2C0.08&scaling=min-zoom&starting-point-node-id=611%3A77813

### PR DESCRIPTION
**Pull request by danielfmiranda**
Closes #7378 

**Link to sample test pages**:

Test Page with "Mozilla says" set to Unknown, (Sideways): https://foundation-s-7378-mozil-a7zqkp.herokuapp.com/en/privacynotincluded/write-poor-nature-kind-stage-daughter/
Test Page with "Mozilla says" set to Yes, (Thumbs-Up): https://foundation-s-7378-mozil-a7zqkp.herokuapp.com/en/privacynotincluded/entire-economic-course-writer-most-little-notice/
Test Page with "Mozilla says" set to No, (Thumbs-Down): https://foundation-s-7378-mozil-a7zqkp.herokuapp.com/en/privacynotincluded/guess-sit-take-game-instead-store-example-realize/

*Steps to test**:

1. Visit the three links above, each page should have either a thumbs up, down, or sideways.
2. If it appears that they are rendering correctly, testing is complete! 
**Note:** Please note that this section might look a little empty until we add the two other subsections (time researched, people voted section). This, as well as the dividers will be updated/added in future PR's.

### CODE REVIEW

**Review by TheoChevalier — CHANGES_REQUESTED** [review]
Let’s translate this please 😉
I’ve also added additional context for translators since the concatenated icon is important context to have in mind and isn’t clear from the string alone

**Review by nancyt1 — APPROVED** [review]
Looks good! Can "says" be all lowercase though?

**Comment by danielfmiranda** [comment]
Awesome catch @TheoChevalier! I have added your suggested feedback and re-requested review 😄 
And thanks @nancyt1! Updated 👍

**Review by TheoChevalier — COMMENTED** [review]
Hmm, looks like the rebase didn’t go so well?

**Comment by danielfmiranda** [comment]
Sorry about the confusion with the rebase @TheoChevalier! I have updated it and re-requested review :D

**Review by TheoChevalier — APPROVED** [review]
Looks good!

**Pull request merged**
