### PR TITLE
Fellowship Directory Updates Mashup

### LINKED ISSUE #3000: Fellowships directory h6-heading bug
**Describe the bug**
The h6-heading text switches between uppercase and lowercase.

**To Reproduce**
1. Go to https://foundation.mozilla.org/en/fellowships/meet-our-fellows/ and you will see h6 in lowercase (screen cap from PR)
Screen Shot 2019-04-10 at 1 43 21 PM

2. Click on a different year and you will see h6 in uppercase (screen cap from PR)
Screen Shot 2019-04-10 at 1 43 48 PM

3. Refresh the page, and h6 will go back to lowercase

**Expected behavior**
Case style should be consistent (I believe h6-heading should always be uppercase based on the [style guide](https://foundation.mozilla.org/en/style-guide/)).

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.3
 - Browser: FF
 - Version: 66.2

### LINKED ISSUE #3001: Fellowships Directory layout at tablet width
@sabrinang has suggested a better card layout for the browser width of around 760-980px. Instead of the bio copy being really narrow, the copy should go below the pic (like on mobile).

Comp: https://redpen.io/ge7f4beac4f1723042

Medium (≥768px) @2x

Screen cap from prod:
image

cc @youriwims

### PR DESCRIPTION
**Pull request by youriwims**
## This pr contains the following: 
- Type update for the fellow's profile card location (_Issue 1_)
- LinkedIn link typo fix (_Issue 2_)
- Updating the profile cards layout at table view to match what's on mobile (_Issue 3_)

[Test Page](https://foundation-mofostaging-pr-3027.herokuapp.com/en/directory-location---type-test/) (all changes can be viewed here).

More detail 👇 if you'd like to keep reading 📖 

---

### **Issue 1**

Closes #3000
Related PRs/issues #2803 , #2810

_Investigation/Discovery :alien:_
...attempted to track down 🛤 what happened here, but can't seem to find 🔍 exactly where and how this bug 🐛 happened. Originally, when the component was built 🔨 , it was using the older type styles for `.h6-heading`, but this was all fixed in the type clean up 🍃 in #2810 and reestablished as `.body-small`. Somehow 👀 this work reverted back to `.h6-heading` which resulted in it taking on the newly established `.h6-heading` styles reflected in the updated [style guide](https://foundation.mozilla.org/en/style-guide/). 🙃 

_Fix_
[Commit](https://github.com/mozilla/foundation.mozilla.org/pull/3027/commits/bf45bfcc69077eb698b5d3476e76984eb3fa3b9d): Reverted styles back to `.body-small` based on finalized [Redpen design](https://redpen.io/me6c690075cd81cd6f).

---

### **Issue 2**

LinkedIn link not working once you click to another year on the filter bar. 
[Comment Reference](https://github.com/mozilla/foundation.mozilla.org/pull/3027#issuecomment-484164632)

_Fix_
[Commit](https://github.com/mozilla/foundation.mozilla.org/pull/3027/commits/563fb3a0972a189f85fba8484c99a5b0daa7e8da) 

--- 

### **Issue 3**

Closes #3001 
Related PRs/issues #2685 

_Fix_
[Commit](https://github.com/mozilla/foundation.mozilla.org/pull/3027/commits/97e760c6fc7c9ca2d16d7fb4926b91e445578331): Updated layout between 768px and 992px.

### CODE REVIEW

**Comment by youriwims** [comment]
@kristinashu , I updated the styles based on the final Redpen design. But, let me know if you would like to keep the `.h6-heading`/uppercase typography for the fellow's location—it's a simple fix 😊

**Comment by kristinashu** [comment]
Looks good! Type style looks good and it's no longer switching between uppercase and lowercase! 

BUT I've noticed a new bug that is here and on prod. LinkedIn link works on first page load but then doesn't work if I click on a different year. I feel like this bug keeps coming up!

**Comment by youriwims** [comment]
The devs have talked about this already (will insert link to discussion once I find it 🙃 ). The directory is being loaded via two files and every time we make an update to it, we have to remember to update both files. I'll go ahead and fix that now, thanks for pointing this out.

**Comment by kristinashu** [comment]
It's working well!

**Comment by youriwims** [comment]
Pulse headshots have been cropped already, so the updates in Issue 3 of this pr should be uniform across all profile cards. ([Reference](https://github.com/mozilla/foundation.mozilla.org/issues/3001#issuecomment-484218443))

**Pull request merged**
