### PR TITLE
Source client side Sentry configuration from environment.json

### PR DESCRIPTION
**Pull request by cadecairos**
This will make pipeline promotions work once again, now that environment specific variables aren't built into the webpack build.

### CODE REVIEW

**Comment by cadecairos** [comment]
> R+ with a little `if` check

`if` check where?

**Comment by cadecairos** [comment]
@Pomax hey can you explain that ancient review comment? :)

**Comment by Pomax** [comment]
I think it was about the fact that you only test for one value, then assign from three.

**Comment by cadecairos** [comment]
I see what you mean. If the DSN was set, we should expect the other values as well, but if they're unset it doesn't break the initialization.

**Pull request merged**
