### PR TITLE
Added links, copy and translation strings

### LINKED ISSUE #7002: [YouTube Regrets 2021] Cleanup todos and misc. translations
Look for "#TODO" in the youtube regrets 2021 code, and update the links in the translation tags. 

If we find any other strings that need translation, feel free to put those changes in this PR as well.

### PR DESCRIPTION
**Pull request by KalobTaulien**
Closes #7002 

**Link to sample test page**: https://foundation-s-7002-youtu-v5uk4p.herokuapp.com/youtube-regrets-2021/

## Acceptance criteria:
- [x] Copy should match our Google Doc 
- [x] Links should be free from /en/ links 
- [x] Links should all match the Google Doc

### CODE REVIEW

**Comment by KalobTaulien** [comment]
@danielfmiranda Could you code-review this? 
@kristinashu Could you double check the links that used to be "TODO" are now going to the right place?

**Comment by kristinashu** [comment]
@KalobTaulien marni has pointed out a lot of the link updates in the [QA doc](https://docs.google.com/document/d/1iW4yyjqDJ_sX43kFA0I8C99hVh1KoZT1CYBw9R7DlgU/edit#heading=h.q9ynb1nb77bt), would this be the ticket to do those updates? 

In general it seems like a lot of the link have /en in them which I feel we should leave out.

**Comment by KalobTaulien** [comment]
@kristinashu Good catch! I removed the /en/ and also made all the copy updates from our Google Doc. Mind taking another look? (Maybe give it 10 minutes to update the testing link)

**Comment by kristinashu** [comment]
I've reviewed all the links and copy and it all looks good!

I ignored the links from https://github.com/mozilla/foundation.mozilla.org/pull/7001

Marni pointed this out but I'm assuming that's will be done in a different ticket.

image

**Review by kristinashu — APPROVED** [review]
Thank you!!!

**Review by danielfmiranda — APPROVED** [review]
Hi Kalob, 

Just gave the code a look, and I can see that you have updated the links that were filled with #todos and also updated some other text on the site. 

Looks good to me!  Approving

**Pull request merged**
