### PR TITLE
Article Page - side share buttons and layout fixes

### LINKED ISSUE #6207: [Publications] Upper Social Media Buttons
- The upper social media buttons appear only when h2/summary is present on the page
- When a full width image is present at the top it also covers this a bit
image

Could the upper social media buttons be present by default and would we be able to include a checkbox to hide them?

### PR DESCRIPTION
**Pull request by mmmavis**
Closes #6207 

Added "Show side share buttons " toggle.

### With summary block
- page: https://foundation-s-issue-6207-klyhir.herokuapp.com/en/publication-page-with-child-article-pages/fixed-title-article-page/
- edit: https://foundation-s-issue-6207-klyhir.herokuapp.com/cms/pages/55/edit/

### Without summary block
- page: https://foundation-s-issue-6207-klyhir.herokuapp.com/en/publication-page-with-child-article-pages/manage-short-message-up/
- edit: https://foundation-s-issue-6207-klyhir.herokuapp.com/cms/pages/56/edit/

### CODE REVIEW

**Review by KalobTaulien — APPROVED** [review]
LGTM. I'm diggin' the new checkbox option to disable social sharing.

**Review by sabrinang — COMMENTED** [review]
The check box works great!

When the summary box isn't present, the alignment of the social buttons feel quite high. Is it possible to align this to the the content or should I file this as a separate issue?
image

**Comment by mmmavis** [comment]
image

PR updated!

**Review by sabrinang — APPROVED** [review]
Great thanks for adjusting that alignment Mavis!

**Pull request merged**
