### PR TITLE
updated key and english text for footer call to action

### LINKED ISSUE #6831: Improve newsletter sign-up text
Will has identified and requested that we improve the sign-up text in our newsletter sections to include more specific asks.

### Links
[Airtable link is here](https://airtable.com/tbljPmOCkK9JShaTS/viw9sdUJiIjCYpn0Y/recV78f369QS1vLPW?blocks=hide)

---

For now we're just doing a quick fix of updating the text to what Will has suggested:

> Help shape the future of the web for the public good. 

> Join our Mozilla News email list to get action alerts & internet tips right to your inbox.

### Todo
- [x] Identify all the places on the site where it would need to be updates
- [x] Make sure new copy will work
- [x] Give Theo a heads up that this is coming
- [x] Ping design for QA of PR
- [ ] Ping design once on prod (including updated CMS editable pages)
- [ ] Have this text translated by Theo
- [ ] Let stakeholders know it's done

### PR DESCRIPTION
**Pull request by danielfmiranda**
Closes #6831 

**Link to sample test page**: [link](https://foundation-s-updated-fo-rr6uec.herokuapp.com/en/)
**Link to Percy Side-by-Side comparison**: [link](https://percy.io/Mozilla-Foundation/foundation.mozilla.org/builds/11172800/changed/627402429?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280)

## Checklist

**Changes in Models:**
- [x] [Are my changes backward-compatible]

### CODE REVIEW

**Comment by danielfmiranda** [comment]
Hi @kristinashu, I have made the requested updates to the footer text from:

```
Protect the internet as a global public resource

Join our Mozilla News email list to take action and stay updated! 
```

to 

```
Help shape the future of the web for the public good. 

Join our Mozilla News email list to get action alerts & internet tips right to your inbox.
```

I was wondering if you could please take a look and let me know if everything looks as requested, or if you could point me to the best point of contact for this ticket? 

Thank you!

**Comment by danielfmiranda** [comment]
Hi @TheoChevalier! 

 I have made the requested updates to the footer text from:

```
Protect the internet as a global public resource

Join our Mozilla News email list to take action and stay updated! 

```
to

```
Help shape the future of the web for the public good. 

Join our Mozilla News email list to get action alerts & internet tips right to your inbox.
```

By updating the key in **join.jsx**, and then updating the key and text for English / just the key for the other languages in **locale-strings.jsx**.

I was wondering if there was anything else that I needed to do before the other languages could be translated by you? Thanks in advance!

**Review by kristinashu — APPROVED** [review]
Looks good Daniel!

**Comment by TheoChevalier** [comment]
Hey @danielfmiranda, thanks for the ping, we’re all set!  I’ve just merged the French, German & Portuguese translations, you can go ahead and merge this PR, I’ll make a follow up PR for Spanish & Polish when they are ready.

**Review by TheoChevalier — APPROVED** [review]

**Comment by danielfmiranda** [comment]
Awesome! Thanks @TheoChevalier

**Pull request merged**
