### PR TITLE
Fade effect and updating spacing

### PR DESCRIPTION
**Pull request by danielfmiranda**
# Description

**Note:** This PR builds off of #9999, please do not merge until that PR is also merged.
Related PRs/issues: #9871

This PR updates the Subcategory nav bar to have a fade effect coming from the right if there are more subcategories to scroll through. Once the user scrolls to the last category, there is no fade effect shown.

This PR also makes some minor updates to the "Sort By" dropdown, in order to have the spacing reflect the designs from figma, linked in the original ticket.

# Screenshots:

**Desktop with long text:**

Screenshot 2023-01-23 at 17-26-01 Privacy Not Included A Buyer’s Guide for Connected Products

**Desktop with short text:**

Screenshot 2023-01-23 at 17-26-09 Privacy Not Included A Buyer’s Guide for Connected Products

**Desktop with dropdown expanded:**

Screenshot 2023-01-23 at 17-26-16 Privacy Not Included A Buyer’s Guide for Connected Products

**Mobile with long text:**

206596143-62e265e7-45be-444e-acf8-c050dc5e0e7a

**Mobile with short text:**

206596143-62e265e7-45be-444e-acf8-c050dc5e0e7a

**Mobile with dropdown expanded:**

206596143-62e265e7-45be-444e-acf8-c050dc5e0e7a

### CODE REVIEW

**Comment by danielfmiranda** [comment]
Looks like this might have some merge conflicts with #9870, going to coordinate with Simon!

**Comment by danielfmiranda** [comment]
Hi @nancyt1! This ticket is ready for review, I was wondering if you can please take a look at the screenshots above and let me know if everything is looking OK to you?


I also had a quick question regarding the request to have the "Sort By" label and the dropdown wrap if the text was too long:

What do you think about having the two stacked on the XS breakpoint by default? My reasoning being: with the different lengths between the choices, the dropdown would "jump" up and down based on which option you chose.

For example:

Here is the location of the dropdown with a shorter choice:

206596143-62e265e7-45be-444e-acf8-c050dc5e0e7a

Expanded:

206596143-62e265e7-45be-444e-acf8-c050dc5e0e7a

And then here is the location with a longer choice that does not fit:

206596143-62e265e7-45be-444e-acf8-c050dc5e0e7a

Expanded: 

206596143-62e265e7-45be-444e-acf8-c050dc5e0e7a


Beyond the XS breakpoint, we have more than enough room to have them side-by-side even with the longer locales, so this would not be an issue. 


Thanks!

**Comment by nancyt1** [comment]
@danielfmiranda Screenshots looks good and I agree with the XS breakpoint! Does that apply to all locales or in the cases where wrapping is needed?

**Comment by danielfmiranda** [comment]
Hi @nancyt1 this change would apply to all locales! 

Here are a couple of screenshots of what this would look like with a shorter locale, such as English:

Default State:
206596143-62e265e7-45be-444e-acf8-c050dc5e0e7a

Expanded:
206596143-62e265e7-45be-444e-acf8-c050dc5e0e7a





In regards to the second question, it appears that the spacing between the title and the category tags are 2rem or 32px.

206596143-62e265e7-45be-444e-acf8-c050dc5e0e7a

**Comment by danielfmiranda** [comment]
Hi @nancyt1, here is a screen recording on how the dropdown behaves if the div is set to wrap the text. The screen is set to the width of a Iphone 12 Mini.

https://user-images.githubusercontent.com/18314510/214450733-1a01a874-386d-4163-a1d7-96908775ba24.mov



On phones with wider screens such as the iphone 13 Pro Max, it looks like the dropdown does not need to wrap:

Screenshot 2023-01-24 at 4 14 35 PM

And then on shorter locales such as English, it appears that both fit on the same line even on the iphone 12 mini:

Screenshot 2023-01-24 at 4 14 35 PM

**Comment by danielfmiranda** [comment]
Closing this PR as #10091 takes its place!

**Pull request closed without merging**
