### PR TITLE
Make product mailto: a conditional

### LINKED ISSUE #3816: PNI mailto: issue
**Describe the bug**
On the PNI site, some of the links on the product pages under "How to contact the company: Email section" direct to a mailto: when it should just lead to the company website with their contact information. e.g. The [Nintendo Switch page](https://foundation.mozilla.org/en/privacynotincluded/products/nintendo-switch/). 

**To Reproduce**
1. Go to https://foundation.mozilla.org/en/privacynotincluded/products/nintendo-switch/
2. Scroll to "How to contact the company"
3. Under the Email Section, click the link

**Expected behavior**
A mailto: can happen if we have the company email directly listed on our site, but if it is a site link that directs to a product's company about page, we need it to change to direct to the new site in a new tab.

**Screenshots**
Screen Shot 2019-10-26 at 11 29 01 AM

Screen Shot 2019-10-26 at 11 29 09 AM

### PR DESCRIPTION
**Pull request by youriwims**
Closes #3816

## Checklist

**Changes in Models:**
- [x] Did I squash my migration?

### CODE REVIEW

**Comment by Pomax** [comment]
Hm, I don't think we need a migration here, we should be able to check whether `email` contains `@` or not. If it does, the template can add the `mailto:` and if it doesn't, we don't add that?

```
<a href="{% if 'http' not in product.email %}mailto:{% endif%}{{ product.email }}"...>...</a>
```

**Comment by youriwims** [comment]
good idea 🤦‍♀

**Comment by youriwims** [comment]
So, @kristinashu @natalieworth, no need for Jen to go back and update all the products' email with the 'email verification' checkbox. That should be taken care of automatically now—if not, let me know :) 👍

**Comment by kristinashu** [comment]
Amazing!

**Comment by kristinashu** [comment]
Can you please check it once it's on staging? Example of products that have an email are:
- Ecobee Smart Thermostat with Voice
- Instant Pot Smart WiFi
- Huawei Band 3 Pro
- Petcube Bites 2

**Comment by youriwims** [comment]
@kristinashu most def!

**Pull request merged**
