### PR TITLE
Various search bar styling fixes

### LINKED ISSUE #5559: PNI - adjust search bar width
Adjust search bar's width so it aligns better with mobile category nav (refer to design on the right and ignore the one on the left)

For more context see See https://github.com/mozilla/foundation.mozilla.org/pull/5551#issuecomment-720788496

### PR DESCRIPTION
**Pull request by mmmavis**
Closes #5559

https://foundation-s-issue-5559-7unhuh.herokuapp.com/en/privacynotincluded/

### CODE REVIEW

**Review by sabrinang — CHANGES_REQUESTED** [review]
The margin below the checkbox reduces when it gets into tablet, it should be same as mobile so it doesn't shift:

pni_spacing

**Comment by mmmavis** [comment]
I can't reproduce the issue and also wondering why the creepy face was missing in your gif @sabrinang  🤔

**Comment by sabrinang** [comment]
I think I may have scrolled down a bit, made the face stick to the bottom, and revisited the search bar area so the face isn't centre there

**Comment by Pomax** [comment]
I see that margin gap in Chrome in MacOS, it feels like it's a small/medium breakpoint mismatch.

**Comment by Pomax** [comment]
yeah, turns out it was setting heights using a `max-width` cascade, rather than the `min-width` overrides that all our code relies on, so I refactored that and made it use the correct height for tablet.

**Review by sabrinang — CHANGES_REQUESTED** [review]
The mobile and tablet spacing is consistent now however on desktop search bar margins have become tall and the spacing shifts when I click on/off of the search bar:
pni_search-bar-heights

**Review by sabrinang — APPROVED** [review]
Thanks the margins on desktop are consistent now

**Pull request merged**
