### PR TITLE
New Initiatives Page (Take 2)

### PR DESCRIPTION
**Pull request by alanmoo**
Related: #1648

@gvn we had to roll this back yesterday. Opening this up again to roll forward, but there's a bug that needs fixing

- [x] #1714 Secondary Nav

### CODE REVIEW

**Comment by beccaklam** [comment]
@gvn Also ... wondering if we could change the initiatives paragraph div styling to:
<div class="col-12 col-md-5 px-4 py-5 px-md-0 px-lg-3 align-self-center></div>
and the image div to:
<div class="col-12 col-md-5 offset-md-1"></div>
We can also chat about this over vidyo just to make sure it looks right before pushing the commit.

**Comment by alanmoo** [comment]
@beccaklam Please file that in another ticket to make it easier to address individually, and edit the original comment in this ticket to add that number if it's a launch blocker.

**Comment by gvn** [comment]
@alanmoo A fix for #1714 should be in here now

**Comment by gvn** [comment]
AFAIK this is good to merge but I'll hold off until we get the missing content, which is:

- [ ] What highlights are featured?
- [ ] Copy for "Sub H3", which is lorem ipsum in the comp. We can also leave this blank.

**Comment by alanmoo** [comment]
They can be created on the live site if they don't already exist there, as the highlights model already exists there. That way, once the Initiatves page makes it live, someone just has to point to those highlights to hook them up.

https://foundation.mozilla.org/cms/highlights/highlight/

**Comment by beccaklam** [comment]
Sydette has provided all the content we need in the aforementioned doc!

**Comment by gvn** [comment]
Awesome. I'm merging this and I'll also put the initial content in the CMS this time around.

We'll plan to do a prod push Monday. 🎉

**Pull request merged**
