### PR TITLE
9553 - Fix Search on Desktop

### PR DESCRIPTION
**Pull request by fessehaye**
# Description

Search bar on desktop should now be working on non-product search pages. Just needed to add similar JS that allows the mobile search bar to work globally.

Link to sample test page: go to /privacynotincluded and click on a page or article
Related PRs/issues: #9553

### CODE REVIEW

**Review by tbrlpld — COMMENTED** [review]
@fessehaye I am confused, the PR is supposed to be for the desktop search but all the changes address the mobile search? Am I missing something here?

**Comment by fessehaye** [comment]
@tbrlpld before, the search bar logic outside of product review pages only worked on the mobile-visible search bar. Since I added the regular search bar references I just renamed the existing mobile variables so it is easier to understand which are being used for each case!

**Comment by tbrlpld** [comment]
@fessehaye I am still confused where the changes regarding the desktop search are. All the changes are in `/mobile-search-bar.js`

**Review by tbrlpld — COMMENTED** [review]
See above

**Review by tbrlpld — COMMENTED** [review]
@fessehaye Sorry, I still don't understand why are copying the mobile search functionality instead of creating a generic search bar that works regardless of the viewport sizes / location of the search bar. Can you add some context to that decision?

**Comment by fessehaye** [comment]
> @fessehaye Sorry, I still don't understand why are copying the mobile search functionality instead of creating a generic search bar that works regardless of the viewport sizes / location of the search bar. Can you add some context to that decision?

@tbrlpld Are you referring to the the js files being different or the html elements?

**Comment by tbrlpld** [comment]
> @tbrlpld Are you referring to the the js files being different or the html elements?

I was referring to the JS files, because that's what is updated in this PR. 

But, if there are two HTML templates I am also wondering why we have that twice. It seems to me that the search bar elements would be the same only with different widths (which could be limited by the wrapping element). But that's not something we need to address in this PR.

**Comment by fessehaye** [comment]
> > @tbrlpld Are you referring to the the js files being different or the html elements?
> 
> I was referring to the JS files, because that's what is updated in this PR.
> 
> But, if there are two HTML templates I am also wondering why we have that twice. It seems to me that the search bar elements would be the same only with different widths (which could be limited by the wrapping element). But that's not something we need to address in this PR.

Okay, `mobile-search-bar.js` does have unique logic related to toggling the mobile search bar visibility that should not be included in a generic search bar js file. If that is the case, do we want to create a generic search bar js file and add that to the desktop/mobile js files?

**Comment by tbrlpld** [comment]
> Okay, `mobile-search-bar.js L2-16` does have unique logic related to toggling the mobile search bar visibility that should not be included in a generic search bar js file. If that is the case, do we want to create a generic search bar js file and add that to the desktop/mobile js files?

Is the desktop search module needed if this is basically only the generic search? If you think it's valuable for some setup code we could do that. 

If there is no extra file needed for the setup code of the search, we could also just have a search module and one for the search visibility toggle.

**Review by tbrlpld — COMMENTED** [review]
@fessehaye Sorry I am confused, I don't seem to see the generic search module you mentioned.

**Comment by fessehaye** [comment]
Hey @tbrlpld, I think there is some confusion about what needs to be split into modules and what not. Can we just make a ticket to document this discussion/suggested changes, so this ticket can be pushed to production if there isn't other problems related to this task?

**Comment by tbrlpld** [comment]
@fessehaye I weary of the tech debt we are accumulating within PNI already. I don't think it we should keep adding things to do in The Refactor™️ because no one knows if it ever comes. And in this case we always have to remember to duplicate all the functionality in both files. 

And it appeared like we were on the same page since you mentioned this: 

> Okay, mobile-search-bar.js L2-16 does have unique logic related to toggling the mobile search bar visibility that should not be included in a generic search bar js file. If that is the case, do we want to create a generic search bar js file and add that to the desktop/mobile js files?

From which I assumed we would put all the shared logic into the `search-bar.js` and then use that functionality in `desktop-search-bar.js` and `mobile-search-bar.js`. Additionally `mobile-search-bar.js` would have some extra logic for the toggling of the visibility. 

I was imagining something where `desktop-search-bar.js` and `mobile-search-bar.js` import something like `setupSearchBar()` from `search-bar.js` and pass in the `id`, `class`, object or what ever is that is different between the two.

**Review by tbrlpld — COMMENTED** [review]
@fessehaye See last comment

**Review by tbrlpld — COMMENTED** [review]
Thanks @fessehaye. This feels a lot cleaner to me. 

And I just realized where some of the confusion has come from. I have been assuming that the search bar is a template fragment itself that is included in two locations. But it turns out that this the markup is included directly in two separate locations and slightly different. 

I was wondering what you think about turning this into a template fragment that we can reused in both locations? Of course the width is different, but that could be solved by making the fragment fill 100% width and having a wrapper around the include that constrains the size/width. 

Something like 
```html+django
<div class="tw-w-96">
  {% include "fragments/buyersguide/search_bar.html" %}
</div>
```

If we need to, we could pass some id into the include as well.

**Comment by tbrlpld** [comment]
Ah, looks like the tablet version does have another difference by having this inner content wrapper that restricts that width. 

image

**Review by tbrlpld — APPROVED** [review]
Moving forward as is, but I think we should follow up with a refactor of the search/filter code for the buyer's guide (#8015).

**Pull request merged**
