### PR TITLE
autopep8 all the things

### PR DESCRIPTION
**Pull request by easherma**
Closes #
Related PRs/issues #5099 

For your consideration...

I ran into some auto-linting problems in recent work, and it took a bit of effort to backtrack. The thing is, the changes were not significant, and this sort of problem is likely to occur in the future without an agreed on set of codestyling (and it's happened to @KalobTaulien too in the past).

There is definitely a whole conversation that could be had around linting and code styling and I'm sure we're all aware of the pros and cons. I thought about opening an issue to discuss (and still could), but in that same couple minutes I just decided to create this PR instead. 

This PR takes an approach inbetween having no convention and something super opinionated like black, and just uses autopep8 to make sure indentation and whitespaces follow generally agreed-on rules. 

## Checklist

_Remove unnecessary checks_

**Tests**
- [ ] Is the code I'm adding covered by tests?

**Changes in Models:**
- [ ] Did I update or add new fake data?
- [ ] Did I squash my migration?
- [ ] [Are my changes backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/master/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- [ ] Is my code documented?
- [ ] Did I update the READMEs or wagtail documentation?

### CODE REVIEW

**Comment by Pomax** [comment]
Remember to file an issue for the current milestone, assigned to yourself, tagged as "engineering", "backend" and specific to this case, "unplanned", with an effort estimate. No orphan PRs, please =)

**Comment by KalobTaulien** [comment]
I dont know for sure this is the case already, but I wonder if we can add linting to CI and fail pipelines that import unused imports.

**Comment by easherma** [comment]
At the moment, flake8 is run on CI, so it will warn if there are problems with the code styling, but not fix them.

That is, to some extent, a separate problem. The flake8 config for this repo is pretty minimal, but there are other PEP8 recommended styling that it would be nice to conform to in absence of a different standard. But having those diffs from code linting in other PRs makes them hard to review, hence this PR.

**Comment by easherma** [comment]
Once homepage is merged we can revisit this and probably run Autopep8 again, rebase, and then consider for merging.

**Comment by Pomax** [comment]
Closing for now, we can discuss in https://github.com/mozilla/foundation.mozilla.org/issues/5099 and remake a PR when we've figured out our exact needs.

**Pull request closed without merging**
