### PR TITLE
Filter tweak

### PR DESCRIPTION
**Pull request by Pomax**
Closes https://github.com/mozilla/foundation.mozilla.org/issues/2183 by having the rectangular filter style kick in at small rather than medium width, and having it go from transitioning to immediate, with a full screen "overlay".

### CODE REVIEW

**Comment by kristinashu** [comment]
Hmm yeah I see what you mean. It looks good a small widths. 

It also looks good at around 582px with the edges cutoff. Screen cap from PR:
screen shot 2018-11-19 at 5 24 06 pm

But at around 430px it feels a little too blank. Screen cap from PR:
image

If possible, I think the edges could be cutoff more. Maybe as much as like this (430px):
screen shot 2018-11-19 at 5 22 28 pm

Hope that makes sense.

**Comment by Pomax** [comment]
I'll see if that's a built in bootstrap value - if not adding a sass var to represent (effectively) "extra small" should be relatively straight forward

**Comment by mmmavis** [comment]
Not sure which PR gets merged first but there will be code conflicts with this PR ["Added product name to homepage & thumbnail sizing"](https://github.com/mozilla/foundation.mozilla.org/pull/2232) (which extends the filter popup to full width). Just fyi

**Comment by Pomax** [comment]
As a larger PR, let's land yours first.

Blocked by https://github.com/mozilla/foundation.mozilla.org/pull/2232

**Comment by mmmavis** [comment]
@Pomax Thanks! 

lol I just realized that PR accidentally addressed 70% what we are trying to fix here (I made some DOM elements full width so that might be why). We need to fix the height of the filter bubble on mobile and probably other tweaks. https://foundation-mofostaging-pr-2232.herokuapp.com/en/privacynotincluded/

**Comment by Pomax** [comment]
Yeah, I'm more than happy to just see what needs doing after yours lands.

**Pull request merged**
