### PR TITLE
Set video embed aspect ratio to 16:9

### PR DESCRIPTION
**Pull request by mmmavis**
Related to #1376

YouTube and Vimeo videos are all in 16x9 so I think we are good to just force that ratio on the embed too.

### CODE REVIEW

**Comment by gvn** [comment]
@ScottDowne ... ignore this...just for demo purposes

**Comment by gvn** [comment]
@mmmavis does this need design review?

**Comment by mmmavis** [comment]
just realized this fix doesn't really work... i'll assign reviewers once i get this fixed.

**Comment by mmmavis** [comment]
@kristinashu please see screencaps of a test page below

# Desktop
screenshot-2018-5-3 test

# Mobile - Without fix
screenshot-2018-5-3 test 2

# Mobile - With fix

screenshot-2018-5-3 test 1

**Pull request merged**
