### PR TITLE
6977 - [YouTube RegretsReporter] Add links to report

### LINKED ISSUE #6977: [YouTube RegretsReporter] Add links to report
Based on design ticket https://github.com/mozilla/foundation.mozilla.org/issues/6893

Two updates to https://foundation.mozilla.org/campaigns/regrets-reporter/ that will link out to https://foundation.mozilla.org/campaigns/regrets-reporter/findings 

Comp is here https://redpen.io/fa26299c025ec47a4a

### To do
- [x] Add button below the hero section (button should match existing style and have the text `[Read Our Findings](https://foundation.mozilla.org/campaigns/regrets-reporter/findings )`)
- [x] Add new item to the timeline (see text below)

> July 2021
> Using data contributed by 37,380 RegretsReporter users, Mozilla releases first [findings](https://foundation.mozilla.org/campaigns/regrets-reporter/findings) into YouTube's recommendations. 

cc @benhohner

### PR DESCRIPTION
**Pull request by fessehaye**
Closes #6977

### CODE REVIEW

**Review by KalobTaulien — APPROVED** [review]

**Comment by KalobTaulien** [comment]
Hey @kristinashu - we need a quick little design review here. Here's the demo link: https://foundation-s-6977-fykgvwlthgc5.herokuapp.com/en/campaigns/regrets-reporter/ 

And @TheoChevalier there's some new translation text on the Regrets Reporter page - not sure how you want to handle that but wanted to make you aware of it so we don't miss translations! 

The code looks good, I approved that already. Just need the design + translation approvals.

**Comment by kristinashu** [comment]
Top button looks! The timeline should also link to the report tho. Here's a screen cap from the mockup:

image

**Review by TheoChevalier — APPROVED** [review]
Thanks, looking good! Started translation on these

**Comment by fessehaye** [comment]
Closing because the Preview branch link is expired!

**Pull request closed without merging**
