### PR TITLE
turn post_generation into reseeded code

### LINKED ISSUE #6102: Change how we use @post_generation code
### File(s) or components

All factory code that relies on the `@post_generation` factory boy decorator.

image

### Reason for cleanup

Reading through the post generation docs, all post generation decorated defs run once _all other factory code_ has finished running, and then runs "one post_generation def at a time", which means we can't control their random seed.

Instead of having classes with `@post_generation` decorated properties, we should handle the the data generation as aggregate function as part of the `generate` function. So instead of this:

```python
class PublicationPageFactory(PageFactory):
    ...
    @post_generation
    def toc_thumbnail_image(self, create, extracted, **kwargs):
        if random() < 0.5:
            self.toc_thumbnail_image = ImageFactory()

def generate(seed):
    ...
    PublicationPageFactory.create_batch(parent=pub_page_with_chapters, size=3)
```

we should use this as much as possible:

```python
class PublicationPageFactory(PageFactory):
    ...

def generate(seed):
    reseed(seed)
    ...

    pages = PublicationPageFactory.create_batch(parent=pub_page_with_chapters, size=3)

    reseed(seed)
    for p in pages:
        if random() < 0.5:
            p.toc_thumbnail_image = ImageFactory()
            p.save_revision()
```

### PR DESCRIPTION
**Pull request by Pomax**
Closes #6102

This rewrites all `post_generation`-decorated code to running the same code but as a for loop that can be preseeded.

### CODE REVIEW

**Review by KalobTaulien — APPROVED** [review]
👍 LGTM! Works as expected

**Comment by Pomax** [comment]
Time to dig into why CI fails, because this is a very weird error:

```
Internal Server Error: /en/what-you-can-do/
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'FieldFile' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/defaulttags.py", line 513, in render
    return self.nodelist.render(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/library.py", line 213, in render
    resolved_args, resolved_kwargs = self.get_resolved_arguments(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/library.py", line 177, in get_resolved_arguments
    resolved_args = [var.resolve(context) for var in self.args]
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/library.py", line 177, in <listcomp>
    resolved_args = [var.resolve(context) for var in self.args]
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/db/models/fields/files.py", line 61, in url
    self._require_file()
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/django/db/models/fields/files.py", line 38, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'image' attribute has no file associated with it.
Error: -25 00:18:33,261 [ERROR] "GET /en/what-you-can-do/ HTTP/1.1" 500 333749
Error: -25 00:18:33,261 [ERROR] "GET /en/what-you-can-do/ HTTP/1.1" 500 333749
```

**Review by KalobTaulien — CHANGES_REQUESTED** [review]
Unapproving for now. CI needs to pass.

**Comment by Pomax** [comment]
Looking at what the new Visual CI does with our code, it seems to not have the same constant PNI differences that Percy shows, so... I'm actually going to invalidate the work necessary here.

**Pull request closed without merging**
