### PR TITLE
8348 - Cleanup glyph.scss

### LINKED ISSUE #8348: cleanup source\sass\glyphs.scss
This would be a good file to remove and replace with a tailwind plugin like `tailwind.button.js`

### PR DESCRIPTION
**Pull request by fessehaye**
Closes #8348

### CODE REVIEW

**Comment by tbrlpld** [comment]
I just noticed the gylphs in the Mozfest footer:
image

They do seem to look a bit off. All other ones I have seen looked fine.

**Review by tbrlpld — COMMENTED** [review]
@fessehaye I am not sure if I am doing something wrong, but the Mozfest footer glyphs still look uneven somehow. 


https://user-images.githubusercontent.com/24797493/171949778-a74530b6-da6c-4d4f-95c6-2016dab846a1.mov

**Comment by fessehaye** [comment]
https://percy.io/Mozilla-Foundation/foundation.mozilla.org/builds/18578840/unchanged/1042027088?browser=firefox&browser_ids=22%2C23&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1280&widths=375%2C1280

Looks like mozfest footer looks normal on percy and my machine? Might need to restart npm script?

**Comment by tbrlpld** [comment]
Weird. I thought I had rebuild. 

Approved 👍

**Review by tbrlpld — APPROVED** [review]

**Pull request merged**
