### PR TITLE
Limit the number child pages that are permitted for the campaigns route

### PR DESCRIPTION
**Pull request by Pomax**
Closes https://github.com/mozilla/foundation.mozilla.org/issues/4221 by restricting the permitted child page types to only four.

Note that we may need to move the one blog post that lives under `campaigns` right now, in order for this PR to land.

Alternatively I can put the BlogPage back as permitted type, but given that blog pages are lots of special components that assume all blog posts exist under /blog, we probably don't want to keep allowing that as child type.

### CODE REVIEW

**Comment by kristinashu** [comment]
So much better! This will be much easier and quicker to use now. 

(Screen cap from PR to show only 4 options!) cc @xmatthewx 

image

**Re: blog template under /campaigns**
I was about to move the blog post from under /campaigns to /blog but something seems a little odd. The [live page](https://foundation.mozilla.org/campaigns/how-opt-out-human-review-your-voice-assistant-recordings/) is in English for me but the title in the CMS is in French (see screen cap from prod). @TheoChevalier do you know anything about this? Probably not a big deal and we can just move it but wanted to flag that something is up. Also, once we move it we should redirect the urls since this is a popular post.
image

**Comment by TheoChevalier** [comment]
> I was about to move the blog post from under /campaigns to /blog but something seems a little odd. The [live page](https://foundation.mozilla.org/campaigns/how-opt-out-human-review-your-voice-assistant-recordings/) is in English for me but the title in the CMS is in French (see screen cap from prod). @TheoChevalier do you know anything about this? Probably not a big deal and we can just move it but wanted to flag that something is up. Also, once we move it we should redirect the urls since this is a popular post.
> 

Yes, this is the same Wagtail issue Tais was hitting https://mozilla.slack.com/archives/C4EGUBY2Z/p1584973026002500
I’ve just made a dummy edit to fix it, thanks for flagging!

**Comment by Pomax** [comment]
@kristina I think that means we can move the blog page now? Once that's done I can merge this into master.

**Comment by kristinashu** [comment]
Yes thank you! I have two more hours of meetings but then I'll move it by the end of today.

**Comment by kristinashu** [comment]
Ok the page has been moved. 

@Pomax could you please redirect https://foundation.mozilla.org/en/campaigns/how-opt-out-human-review-your-voice-assistant-recordings/ to https://foundation.mozilla.org/en/blog/how-opt-out-human-review-your-voice-assistant-recordings/ for EN, DE, and FR.

@TheoChevalier could you please double check the localized pages?

**Comment by TheoChevalier** [comment]
> @TheoChevalier could you please double check the new localized pages?

Done, thanks! Added the Siri graphic to the French page, and updated the search descriptions

**Comment by Pomax** [comment]
redirects are in place for EN, FR, DE, and "no locale" (just in case).

**Pull request merged**
