### PR TITLE
Added translatable fields and sync fields to both product page types

### LINKED ISSUE #5953: wagtail-localize: Investigate foreign key bug on PNI products
[This snippet of code](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/pagemodels/products.py#L352-L360) makes wagtail-localize crash, we will need to find another way to handle this.

Capture d’écran 2020-12-16 à 15 55 26

Note: you can only reproduce the error with [this branch](https://github.com/mozilla/foundation.mozilla.org/tree/wagtail-2-11) (enabling wagtail-localize), by creating a new locale in http://localhost:8000/cms/locales/ then translating a PNI product in that locale.

### PR DESCRIPTION
**Pull request by KalobTaulien**
Closes #5953

While we wait for an "ignore _x_ or _y_ field" feature, this is the way around the "votes" foreignkey issue - we simply list all the translatable and synchronized fields and ignore the votes and creepiness fields.

To test:
* Start a new database with `inv new-db` (or new env if you dont have wagtail-localize in your branch with `inv new-env` 
* Log into the admin 
* Go to Settings -> Locale 
* Add a new locale (ie. Spanish, French, German, etc) 
* Edit the English version of a PNI product (One for General Product and one for Software Product) 
* Click on the translation option 
image
* Translate the page, and Publish the translated page. If this doesn't let you save a translation, open settings.py and comment out the REST_FRAMEWORK settings temporarily. 
* If successful, the page won't give you the error found in #5953, previews will work, and both English and your new locale urls will work.

### CODE REVIEW

**Comment by Pomax** [comment]
Getting some odd errors while trying to stand up our fake data:
```
C:\Users\Mike\Documents\Git\mozilla\foundation.mozilla.org>inv manage load_fake_data
cd C:\Users\Mike\Documents\Git\mozilla\foundation.mozilla.org && docker-compose run --rm backend ./dockerpythonvenv/bin/python network-api/manage.py load_fake_data
Found orphan containers (redisfomo) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting foundationmozillaorg_watch-static-files_1 ... done
Starting foundationmozillaorg_postgres_1           ... done
Creating foundationmozillaorg_backend_run          ... done
Traceback (most recent call last):
  File "/app/dockerpythonvenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "wagtailcore_collection" does not exist
LINE 1: ...."numchild", "wagtailcore_collection"."name" FROM "wagtailco...
```

**Comment by KalobTaulien** [comment]
That's odd. I'll look into this. But this PR doesnt have any migration changes so we shouldnt be seeing this unless `wagtail-localize` has a migration issue

**Comment by Pomax** [comment]
Wagtail usability suggestion: auto-select the default locale when adding a locale and no other locales exist yet =D

**Review by Pomax — APPROVED** [review]
no errors = win

**Pull request merged**
