### PR TITLE
add experiments to our setup

### PR DESCRIPTION
**Pull request by Pomax**
Closes https://github.com/mozilla/foundation.mozilla.org/issues/2428 by adding https://github.com/torchbox/wagtail-experiments to our setup.

### CODE REVIEW

**Comment by alanmoo** [comment]
(I was standing next to Chris while he was looking at this, so other than his suggestion, this looks great to me as long as he approves of the code too.)

**Comment by Pomax** [comment]
I was thinking of adding that in follow up, once we actually have an experiment that requires the JS end point, but it's so little work you're right, we should just add that now.

Where do we want to document the fact that we'll now have this functionality?

**Comment by cadecairos** [comment]
Let's document that we use it for A/B testing in the readme and link to the documentation.

Another thought, can we limit access to experiments to specific roles in django? I spoke with @alanmoo and he suggested we might want to limit it to the producer role until we're ready to train people on using it.

**Comment by Pomax** [comment]
As far as I understand it only superusers and "explicitly experiments-granted" users get access to the experiments interface.

**Comment by Pomax** [comment]
image

**Pull request merged**
