### PR TITLE
[BE/FE] Mozfest Session Slider

### LINKED ISSUE #7423: Epic: Mozfest Session Slider
### Design team contact
@sabrinang for feedback

Torchbox designers can be found on slack:
Lindiwe (ux)
Jeth (visual design)

### Final Designs

Figma - https://www.figma.com/file/2knnwWmmqCXuMyF6WPiOuG/MozFest-Additional-Features?node-id=54%3A296

### Details

Help text says "recommend up to 5 items in the slider"
User can move through items using arrow buttons
The component has a heading.

Each item in slider contains:
- Heading *
- author subheading
- Image *
- Video - autoplays on hover (optional)
- rich text copy *
- the card will link to an internal page or external url *

### Implementation Checklist

- [ ] Editor can add a component Heading (required)
- [ ] Editor is advised that 5 items max are added though any number can be added
- [ ] Each item has a Heading (required)
- [ ] Each item has a Sub-heading
- [ ] Each item has a Image (required)
- [ ] Each item has a Video (mp4 or webp) (optional)
- [ ] Each item has a rich text description (required)
- [ ] Each item has a link to an external URL or internal page (required)

### PR DESCRIPTION
**Pull request by b-ggs**
Closes #7423

## Implementation Checklist

Each item in slider contains:
- [X] Heading (required)
- [X] author subheading
- [X] Image (required)
- [X] Video - autoplays on hover
- [X] rich text copy (required)
- [X] the card will link to an internal page or external url (required)

## Screenshots

Session Slider on a page with the signup snippet:
screencapture-mozfest-localhost-8000-en-2021-10-26-13_41_00

Session Slider on a page without the signup snippet:
screencapture-mozfest-localhost-8000-en-spaces-2021-10-26-13_42_08

Session Slider items can be localized:
Screen Shot 2021-10-26 at 1 44 28 PM

## Checklist
- [X] Did I squash my migration?

### CODE REVIEW

**Comment by Pomax** [comment]
@b-ggs  it looks like merging 7457 has created merge conflicts for this PR - just a few, but can you resolve those? I can merge it after that.

**Comment by b-ggs** [comment]
@Pomax, seems that `main` has some migration issues on the `wagtailpages` app. For now, i've merged from `4fb189584a06eff2b1f3469e9ea8ec3331e15d1a` into this branch to be able to properly recreate the migrations. This should be good to merge once the issues on `main` have been resolved and this branch is updated.

**Comment by b-ggs** [comment]
@Pomax, looks like this is good to go!

**Comment by b-ggs** [comment]
@Pomax, remarking you as a reviewer to notify you that this should be good to merge! I've updated the migration to `mozfest.0026`.

**Comment by Pomax** [comment]
perfect, thank you

**Pull request merged**
