### PR TITLE
better product update CMS

### PR DESCRIPTION
**Pull request by Pomax**
Closes https://github.com/mozilla/foundation.mozilla.org/issues/5390 by adding some code that sorts product updates alphabetically, with an update to load_fake_data that generates a bunch of fake product updates to populate the update list in the CMS.

This is similar, but subtly different, from the RelatedProductsFieldPanel work that already landed.

**Changes in Models:**
- [x] Did I update or add new fake data?
- [x] [Are my changes backward-compatible]

### CODE REVIEW

**Comment by mmmavis** [comment]
@Pomax does this close #5341 (have we asked designers to do final pass of review)? Or you meant to link this PR to another ticket?

**Comment by Pomax** [comment]
that other one. Updated the comment.

**Review by mmmavis — COMMENTED** [review]
@Pomax I checked on https://foundation.mofostaging.net and it seems like updates are already in alphabetical order? 
image

**Review by mmmavis — APPROVED** [review]
🎉

**Pull request merged**
