### PR TITLE
Change url() to re_path()

### PR DESCRIPTION
**Pull request by Sparsh-Bansal**
Closes [#5441 ](https://github.com/mozilla/foundation.mozilla.org/issues/5441)

I have changed the old `django.conf.urls.url()` function with new `django.urls.re_path()` function for routing in all the required `urls.py` files.

### CODE REVIEW

**Comment by Sparsh-Bansal** [comment]
@Pomax  Do I have to care about this `percy/foundation.mozilla.org Expected — Waiting for status to be reported` check or not?
If yes what do I need to do for this check to pass?

**Comment by Pomax** [comment]
I've triggered a retest by updating the branch, I think Percy just got stuck, but it does need to either pass or fail before anything can be accepted.

**Comment by Sparsh-Bansal** [comment]
@Pomax what can we do to produce some result of `percy` check ?

**Comment by Pomax** [comment]
percy runs as part of the standard CI, based on the tests found in `cypress/integration/endpoint-tests,js`

**Review by Pomax — APPROVED** [review]

**Comment by Sparsh-Bansal** [comment]
Percy test are passing [here](https://travis-ci.org/github/mozilla/foundation.mozilla.org/jobs/737204291). Then why the `percy/foundation.mozilla.org ` check is not passing.

**Comment by Pomax** [comment]
Those are not the percy tests, that's the percy test _initiator_. Travis runs Cypress, which loads up pages, and creates snapshots, and then also triggers the Percy task for those same pages. Percy runs on percy.io and has a separate entry in the CI test bank (you can see it as "waiting for status to be reported"). Github and Travis have been having issues that last few days, so I fully expect this to be a matter of "percy ran, but it couldn't report the status because github's having problems".

**Comment by Pomax** [comment]
Right so this keeps failing to trigger an actual Percy run, so I'm going to merge this into an local branch instead, and then see if the PR for that will cleanly pass CI. Thanks for the help!

**Comment by Pomax** [comment]
refiled as https://github.com/mozilla/foundation.mozilla.org/pull/5572

**Pull request merged**
