### PR TITLE
change mozfest page URLs when using a review app

### PR DESCRIPTION
**Pull request by cadecairos**
The URLs for mozfest site pages are different on review apps, so I modified the nav template fragment so that if `HEROKU_APP_NAME` is set, it will use URLs with `/mozilla-festival/` as the prefix.

I'm open to suggestions if anyone can think of a DRY-er way to achieve this..

### CODE REVIEW

**Comment by alanmoo** [comment]
Can you set a variable in the if block? https://stackoverflow.com/a/1070414

**Comment by cadecairos** [comment]
> 
> 
> Can you set a variable in the if block? https://stackoverflow.com/a/1070414

oh interesting, I could try:

```
{% if  HEROKU_APP_NAME %}
  {% with path_prefix="/mozilla-festival/" %}
{% endif %}
{% if not  HEROKU_APP_NAME %}
  {% with path_prefix="/" %}
{% endif %}
```

**Comment by cadecairos** [comment]
no, I misunderstood how the `with` tag works, It's still scoped to a block

**Comment by cadecairos** [comment]
aha:

```
{% if foo %}
  {% with a as b %}
    {% include "snipet.html" %}
  {% endwith %} 
{% else %}
  {% with bar as b %}
    {% include "snipet.html" %}
  {% endwith %} 
{% endif %}
```

https://stackoverflow.com/a/7081901/4722739

**Comment by alanmoo** [comment]
I was just about to suggest that :)

**Comment by cadecairos** [comment]
@alanmoo should we close this out while we consider how to make the nav dynamic, or land this and open an issue to convert it to a dynamic solution? either way I'd rather not leave this PR here.

**Comment by alanmoo** [comment]
File an issue to make it dynamic, and then add a comment to this code referencing the issue, and we can land this.

**Comment by cadecairos** [comment]
> File an issue to make it dynamic, and then add a comment to this code referencing the issue, and we can land this.

@alanmoo done.

**Comment by alanmoo** [comment]
Looks like this is about to be superceded by #3294

**Pull request closed without merging**
