### PR TITLE
Fixes #9714 undefined variable error

### LINKED ISSUE #9714: ReferenceError when visiting PNI Articles pages
### Describe the bug
ReferenceError when visiting PNI Articles pages

### To Reproduce
1. Open browser's dev tool
2. Visit https://foundation.mozilla.org/en/privacynotincluded/articles/
3. See `ReferenceError` in console

### Expected behavior
No ReferenceError

### Screenshots
image

### PR DESCRIPTION
**Pull request by mmmavis**
# Description

Fixes undefined variable error, following the same code style in the file.

1. Go PNI Articles page
2. Click on the search box
3. Make sure you don't see the `ReferenceError` error in dev tool console.

Link to sample test page:
Related PRs/issues: #9714

### CODE REVIEW

**Review by danielfmiranda — COMMENTED** [review]
Hi Mavis! 

While testing this I can confirm that the undefined variable error is gone.

When testing on chrome however, I wanted to note that I am getting two new errors:
image

Is this to be expected?

**Comment by mmmavis** [comment]
Hello @danielfmiranda, 

Thank you for raising this. 

Yes it is expected. It's just we are loading the entire script in that file on all PNI pages and we needed to a way signal (in dev tool console) when a DOM element couldn't be found. I personally think we should change `console.error` to something looks less serious and scary like `console.warn`.  But for this ticket I'm just following the existing pattern in the file, which is using `console.error`.

**Review by danielfmiranda — APPROVED** [review]
Thanks for the explanation Mavis! 

Approved 👍

**Comment by mmmavis** [comment]
Closing this one as I couldn't find an easy way to update my very first commit message. New PR filed #9714

**Pull request closed without merging**
