### PR TITLE
removed intro_text field from buyersguide

### PR DESCRIPTION
**Pull request by danielfmiranda**
# Description

Link to sample test page:
Related PRs/issues: #9612

Per request of the design team, this PR removes the PNI homepage's unused `intro text` field, and any references to it in other files.

# Steps to test

1. Check this branch out and run either `inv new-env` or `inv migrate`
2. Visit the PNI homepage in the CMS
3. Note that the `intro_text` field is no longer there
4. If everything is looking as expected, testing is complete!

# Screenshots

Before:
image

After:
Screenshot 2022-11-14 at 19-16-23 Wagtail - Editing Buyers Guide Page Privacy not included

# Checklist

**Tests**
- ~~[ ] Is the code I'm adding covered by tests?~~

**Changes in Models:**
- ~~[ ] Did I update or add new fake data?~~
- ~~[ ] Did I squash my migration?~~
- [x] Are my changes [backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- ~~[ ] Is my code documented?~~
- ~~[ ] Did I update the READMEs or wagtail documentation?~~

### CODE REVIEW

**Comment by tbrlpld** [comment]
@danielfmiranda I am seeing that you crossed out the "backwards compatible" check point. I think removing fields is exactly a case where we need to be backward compatible. Have you checked that this PR is not causing backwards compatibility issues? 

https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations

**Review by tbrlpld — COMMENTED** [review]
See above comment regarding backward compatibility of removing fields.

**Comment by danielfmiranda** [comment]
Thanks for the help in slack Tibor! After our discussion, I marked this ticket as backwards compatible and re-requested review 🙌

**Review by tbrlpld — APPROVED** [review]
Thanks @danielfmiranda Looks good to me 👍

**Pull request merged**
