### PR TITLE
updated all variables to have whitespace in between brackets

### PR DESCRIPTION
**Pull request by danielfmiranda**
# Description
Related PRs/issues: #10095 

This PR updates all html templates that had djlint `t001` errors.

I first used Tibor's suggested regex expression: `sed -i.bak "s|{{\([A-z0-9._]*\)}}|{{ \1 }}|g" **/*.html` which did a great job at reducing the number of errors. 

However, there were still some other `t001` errors caused by formatting such as `{% block%}`. So I went through the list of remaining errors and updated them myself. 

# Screenshots:

### Linting output before:
Screenshot 2023-02-08 at 4 01 17 PM

### Linting output after:
Screenshot 2023-02-08 at 4 33 22 PM

# Steps to test

1. Check out this branch
2. On line 9 of `pyproject.toml`, paste: 
```
ignore="D004,D018,H005,H006,H007,H008,H008,H010,H011,H012,H013,H014,H015,H016,H017,H019,H020,H021,H022,H023,H024,H025,H026,H029,H030,H031,H033,J004,J018,T002,T003,T027,T028,T032,T034,H017"
```
3. Comment out / remove lines 15-250
4. In the terminal run the command `inv djlint-lint`
5. If the linter returns 0 errors, testing is complete! 
6. Undo changes made to `pyproject.toml`

### CODE REVIEW

**Review by mmmavis — COMMENTED** [review]
Wow @danielfmiranda thanks for updating so many files! I haven't reviewed the changes but am wondering what the urgency of this work is. My concern is, when we start merging PRs in after code freeze, this PR is likely to have or create quite a bit of code conflicts. I'm unsure the best way to prevent conflicts. Just wanted to raise my concern 😬

**Comment by danielfmiranda** [comment]
Thanks @mmmavis! Most of the changes were actually automatic thanks to Tibor's regex expression from above 👍 once I ran that, the linter was pretty specific in where the remaining errors were in about 15 files.

To answer your question, I would not say that this work is **super** urgent, as right now we have the linter set to ignore these errors on the list of files found in `pyproject.toml`. 

The reason being is that we did not want these linter errors for old files crowding the output whenever someone runs `inv djlint-lint` for any new files.

This ticket/pr is just a step towards having the linter take a look at the entire codebase when running `inv djlint-lint` instead of only new files.

Code conflicts is definitely a great concern to bring up, I will mention it during stand after the code freeze is over so we can discuss when the best time to merge this PR in might be. Thanks!

**Review by tbrlpld — COMMENTED** [review]
Thanks for fixing all these errors @danielfmiranda.

To make sure we don't reintroduce the `T001` you have fixed here, I would suggest to remove `T001` from all per-file-ignores in `pyproject.toml`. 


I am not too concerned with clashes. If another PR needs to merge in main (after these changes have been merged) they can just used `ours` as merge strategy to keep their own changes. The linter will then show if they kept parts with `T001` errors, which can be easily fixed.

**Comment by danielfmiranda** [comment]
Thanks for the catch @tbrlpld! I have removed all instanced of `T001` from the ignore list and re-requested review

**Review by tbrlpld — APPROVED** [review]

**Review by fessehaye — APPROVED** [review]

**Review by mmmavis — APPROVED** [review]
@danielfmiranda Thanks for the work and for addressing my concern (re: PR merging)! It's always great to have a more formatted codebase!

**Pull request merged**
