### PR TITLE
Add Coil tag to Buyer's Guide

### LINKED ISSUE #3866: Coil integration with PNI
Add support for web monetization on the buyer's guide

### PR DESCRIPTION
**Pull request by alanmoo**
Closes #3866 

Waiting on approval from Ashley, Anil, Abigail.

### CODE REVIEW

**Comment by Pomax** [comment]
If we're doing this, are we also doing the BAT thing for brave users?

**Comment by alanmoo** [comment]
I think that's different- seems BAT is based on actually showing ads.

**Comment by alanmoo** [comment]
Anil's given the OK to land this.

**Comment by alanmoo** [comment]
@anilkanji has given the OK to land this.

**Pull request merged**
