### PR TITLE
Update packs

### PR DESCRIPTION
**Pull request by gvn**
Removing some unused deps and doing minor/patch bumps to others.

### CODE REVIEW

**Comment by gvn** [comment]
@mmmavis Can you R?

**Comment by mmmavis** [comment]
@gvn oh yea I messaged you earlier on Slack - I'm getting this error... not sure if it's related to your PR https://gist.github.com/mmmavis/01106e588c1cae3a99cc5b5d0bb46ad0

**Comment by mmmavis** [comment]
The above log was from node v8.4.0 & npm 5.6.0

---

I just tried with node v10.0.0 and got the following errors

```bash
mavisou:~/Development/foundation.mozilla.org[update-packs*]$ rm -rf node_modules/
mavisou:~/Development/foundation.mozilla.org[update-packs*]$ npm install
npm WARN npm npm does not support Node.js v10.0.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> fsevents@1.2.3 install /Users/mavisou/Development/foundation.mozilla.org/node_modules/fsevents
> node install

[fsevents] Success: "/Users/mavisou/Development/foundation.mozilla.org/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> node-sass@4.9.0 install /Users/mavisou/Development/foundation.mozilla.org/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.0/darwin-x64-64_binding.node
Download complete  ⸩ ⠋ :
Binary saved to /Users/mavisou/Development/foundation.mozilla.org/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Caching binary to /Users/mavisou/.npm/node-sass/4.9.0/darwin-x64-64_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/mavisou/Development/foundation.mozilla.org/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> guetzli@1.0.1 postinstall /Users/mavisou/Development/foundation.mozilla.org/node_modules/guetzli
> node lib/install.js

  ⚠ The `/Users/mavisou/Development/foundation.mozilla.org/node_modules/guetzli/vendor/guetzli` binary doesn't seem to work correctly
  ⚠ guetzli pre-build test failed
  ℹ compiling from source
  ✖ Error: mkdir -p /Users/mavisou/Development/foundation.mozilla.org/node_modules/guetzli/vendor && make && mv bin/Release/guetzli /Users/mavisou/Development/foundation.mozilla.org/node_modules/guetzli/vendor/guetzli
Command failed: make && mv bin/Release/guetzli /Users/mavisou/Development/foundation.mozilla.org/node_modules/guetzli/vendor/guetzli
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
Undefined symbols for architecture x86_64:
  "_png_create_info_struct", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
  "_png_create_read_struct", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
  "_png_destroy_read_struct", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
  "_png_get_channels", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
  "_png_get_image_height", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
  "_png_get_image_width", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
  "_png_get_rows", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
  "_png_init_io", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
  "_png_read_png", referenced from:
      (anonymous namespace)::ReadPNG(__sFILE*, int*, int*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*) in guetzli.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [bin/Release/guetzli] Error 1
make: *** [guetzli] Error 2

    at ChildProcess.exithandler (child_process.js:282:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:947:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)

> node-sass@4.9.0 postinstall /Users/mavisou/Development/foundation.mozilla.org/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/mavisou/Development/foundation.mozilla.org/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine

> optipng-bin@4.0.0 postinstall /Users/mavisou/Development/foundation.mozilla.org/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully
added 1393 packages in 37.494s
mavisou:~/Development/foundation.mozilla.org[update-packs*]$ 

```

**Comment by gvn** [comment]
So that's with npm 5.6.0 in both cases?

**Comment by mmmavis** [comment]
yup

**Comment by gvn** [comment]
Here's what I get:

```
foundation.mozilla.org g(update-packs) ▸ node -v
v10.0.0
 foundation.mozilla.org g(update-packs) ▸ npm -v
5.6.0
 foundation.mozilla.org g(update-packs) ▸ rm -rf node_modules
 foundation.mozilla.org g(update-packs) ▸ npm install

> fsevents@1.2.3 install /Volumes/Nostromo/mozilla-code/foundation.mozilla.org/node_modules/fsevents
> node install

[fsevents] Success: "/Volumes/Nostromo/mozilla-code/foundation.mozilla.org/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> node-sass@4.9.0 install /Volumes/Nostromo/mozilla-code/foundation.mozilla.org/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/gvn/.npm/node-sass/4.9.0/darwin-x64-64_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /Volumes/Nostromo/mozilla-code/foundation.mozilla.org/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> guetzli@1.0.1 postinstall /Volumes/Nostromo/mozilla-code/foundation.mozilla.org/node_modules/guetzli
> node lib/install.js

  ⚠ The `/Volumes/Nostromo/mozilla-code/foundation.mozilla.org/node_modules/guetzli/vendor/guetzli` binary doesn't seem to work correctly
  ⚠ guetzli pre-build test failed
  ℹ compiling from source
  ✔ guetzli built successfully

> node-sass@4.9.0 postinstall /Volumes/Nostromo/mozilla-code/foundation.mozilla.org/node_modules/node-sass
> node scripts/build.js

Binary found at /Volumes/Nostromo/mozilla-code/foundation.mozilla.org/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine

> optipng-bin@4.0.0 postinstall /Volumes/Nostromo/mozilla-code/foundation.mozilla.org/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully
added 1393 packages in 28.066s
 foundation.mozilla.org g(update-packs) ▸ echo $?
0
```

**Comment by mmmavis** [comment]
Seems like it might be just me 💔 since I got the same errors from `master`! `npm start` works though so I'm gonna R+ this!

**Pull request merged**
