### PR TITLE
[5784] Change prev/next functionality

### LINKED ISSUE #5784: Previous/next buttons should link to next chapter instead of taking the user back to the Publication Listing page
previous/next buttons on child publications to link to next chapter instead of back to the same chapter to connect reading experience

Target area:

Criteria:
- [ ] Next page (when the page is the last in a Chapter) should go to the next chapter immediately
- [ ] Prev page (when the page is the *first* in a Chapter) should go to the *previous* chapter immediately

### PR DESCRIPTION
**Pull request by KalobTaulien**
Closes #5784

Review URL:https://foundation-s-5784-previ-4eblns.herokuapp.com/en/publication-page-with-child-article-pages/fixed-title-article-page/

If there is another next or previous article page, go there. 
If there is no next/prev article page, go to the next/prev chapter page.
If there is no next/prev chapter page, go to the parent page (wherever that lies)

Target area:

Criteria:
- [x] Next page (when the page is the last in a Chapter) should go to the next chapter immediately
- [x] Prev page (when the page is the *first* in a Chapter) should go to the *previous* chapter immediately

### CODE REVIEW

**Comment by KalobTaulien** [comment]
@sabrinang can you double check this is the functionality you intended?

**Comment by sabrinang** [comment]
@KalobTaulien The review URL is giving me a 404

**Comment by KalobTaulien** [comment]
@sabrinang Sorry I pasted the wrong url 🤦 Here's the proper link: https://foundation-s-5784-previ-4eblns.herokuapp.com/en/publication-page-with-child-article-pages/fixed-title-article-page/

**Review by sabrinang — CHANGES_REQUESTED** [review]
For **Publication Page with child Article Pages**:
- The very first article page’s previous button is going back to _“news”_ but should go to the main _“Publication Page with child Article Pages”_ 
- The very last article page’s next button goes to a different publication _“Publication Page with chapter pages”_ but should go to the main _“Publication Page with child Article Pages”_ 


For **Publication Page with chapter pages**:
- The very last chapter article page’s next button should go back to the main _“Publication Page with chapter pages”_

**Comment by KalobTaulien** [comment]
@sabrinang I think I had it wrong in my head. The first and last Article pages will now go to the main Publication Page. Try it out and let me know if this is more along the lines of what you were thinking.

**Review by sabrinang — CHANGES_REQUESTED** [review]
Great the **Publication Page with child Article Pages** are fixed!

For **Publication Page with chapter pages**: 
The very last chapter article page’s next button is fixed now (going back to the main “Publication Page with chapter pages”) however now all the other links changed. Article pages that are at the end of their chapter brings them back to the main ToC but should bring them to the next chapter as it did previously. Also, I think the version before the first article pages in a chapter also connected back to the chapter’s ToC (not the main ToC)

I made a diagram I hope this helps:
image

(note: I'll re examine this UX in future sprint too when we get more content testers too cause I think it can perhaps be simplified to make the flow more straightforward)

**Comment by KalobTaulien** [comment]
@sabrinang Ok I think I have this mapping prev/next links the correct way to match your diagram. Can you give it a test again please?

**Comment by sabrinang** [comment]
@KalobTaulien Do you have another review url? _(the one on description now says no such app)_

**Comment by KalobTaulien** [comment]
@Pomax Can you rebuild this review app for us please? I can click the button in Heroku but it doesn't actually do anything (probably missing permissions).

**Review by sabrinang — APPROVED** [review]
Both _Publication Page with child Article Pages_ and _Publication Page with Chapter Pages_ are linked through now, thank you!

**Review by Pomax — APPROVED** [review]

**Pull request merged**
