### PR TITLE
Intro notes to publications

### LINKED ISSUE #6419: [Publications] Add Intro Notes to Child/Publication Template
design and context issue: https://github.com/mozilla/foundation.mozilla.org/issues/6311

Currently we have a notes field that appends copy after the Table of Contents. Stakeholders would like the option to include introductory copy above the page to give content more context before readers get into the ToC sections themselves. 

**Design examples**
Publication page: https://share.goabstract.com/ab0f3e48-fee0-449b-984c-96a66d71d9fd?collectionLayerId=903ef120-e271-4dfc-892b-08ea9ec1623d&mode=design
Child publication page: https://share.goabstract.com/ab0f3e48-fee0-449b-984c-96a66d71d9fd?collectionLayerId=75597cfa-f09b-47f8-a472-b9280fff3bcf&mode=design
image

It can use the same field type that contains bold, italic, h4, lists but we can call the new field `INTRO NOTES` to differentiate it in the editor:
image

For child publication pages, can we also get the `CONTENTS TITLE` field as an option to display on the page? _(field is present but doesn't display on the page)_ This works on publication pages and it will be a helpful option to give hierarchy and separation between ToC/intro notes.

### PR DESCRIPTION
**Pull request by KalobTaulien**
Closes #6419 

Design examples
Publication page: https://share.goabstract.com/ab0f3e48-fee0-449b-984c-96a66d71d9fd?collectionLayerId=903ef120-e271-4dfc-892b-08ea9ec1623d&mode=design
Child publication page: https://share.goabstract.com/ab0f3e48-fee0-449b-984c-96a66d71d9fd?collectionLayerId=75597cfa-f09b-47f8-a472-b9280fff3bcf&mode=design

### Acceptance criteria
- [x] Intro notes should be called "intro notes" in the admin. 
- [x] Allow bold, italic, links and h4 in intro notes 
- [x] Display the content title on the Chapter page 
- [x] Styling matches the design links above

**Link to sample test page**: 
Publication Page with Intro Text: https://foundation-s-6419-intro-knwqlw.herokuapp.com/en/publication-page-with-chapter-pages/ 
Publication Page with Intro Text and Content Title: https://foundation-s-6419-intro-knwqlw.herokuapp.com/en/publication-page-with-chapter-pages/fixed-title-chapter-page/

**Note**: Don't land/merge this yet until migrate squashing is complete.

### CODE REVIEW

**Review by danielfmiranda — APPROVED** [review]
Looks good to me after comparing the mock-ups and the display pages/looking at the code. Approving!

**Review by mmmavis — CHANGES_REQUESTED** [review]
Code and page look great! Thanks for the detailed PR description as well! Can I request that we update the factory so it generates fake data for this new field? 😉

**Comment by KalobTaulien** [comment]
Good catch Mavis, I forgot about that. I also added in the original notes factory in the latest commit.

**Review by mmmavis — APPROVED** [review]
Lovely! Thanks for updating factory!

**Review by sabrinang — APPROVED** [review]
Intro notes looks great on the page and in the cms — thank you Kalob!

**Pull request merged**
