### PR TITLE
add missing new-pni fields

### PR DESCRIPTION
**Pull request by Pomax**
Related PRs/issues https://github.com/mozilla/foundation.mozilla.org/issues/5828

Adds the `social_data_collected` and `offline_use_description` fields to the `GeneralProductPage` set of translatable fields, and makes the `label` for privacy policy links translatable

### CODE REVIEW

**Comment by TheoChevalier** [comment]
Hmm… https://foundation-s-add-missin-lophqf.herokuapp.com/cms/pages/91/edit/ is throwing a 500 error (editing a random product)

**Comment by TheoChevalier** [comment]
And it works locally 🤷‍♂️

**Comment by Pomax** [comment]
let's rebuild the heroku app, I think it got migrations crossed

**Comment by Pomax** [comment]
Looks to have recovered now

**Comment by Pomax** [comment]
new URL is https://foundation-s-add-missin-h66p3p.herokuapp.com/cms/pages/91/edit/ though

**Review by TheoChevalier — APPROVED** [review]
Thanks, looking good!

**Pull request merged**
