### PR TITLE
Remove auto numbering from Publication ToC

### LINKED ISSUE #5822: [Publications] Remove ToC Numbering
@baricks is inputting content for the whitepaper and it has a very specific numbering structure that is integral to the content itself. Our table of content numbers are auto generated and can not be edited so it is clashing and misaligned with the paper's content.

Are we able to remove the table of content numbers since they are not editable? 

image 

Are we able to upload imagery in the boxes?
image

/cc @jamilasnell

### PR DESCRIPTION
**Pull request by mmmavis**
Closes #5822 

Will assign code reviewer once this passes design review.

https://foundation-s-issue-5822-bmjxty.herokuapp.com/en/publication-page-with-chapter-pages/

### CODE REVIEW

**Review by sabrinang — CHANGES_REQUESTED** [review]
Numbers are still on publication/publication children:
image
image

**Review by sabrinang — CHANGES_REQUESTED** [review]
numbers still present on child publication pages
image

**Review by sabrinang — APPROVED** [review]
Thanks for removing all the numbers!

**Review by KalobTaulien — APPROVED** [review]
LGTM. However, the pages look kind of strange without the numbers or images imo

**Pull request merged**
