### PR TITLE
Add share buttons to blog pages

### LINKED ISSUE #3157: Blog: add share buttons
Build on the Blog MVP work to fully flesh out capabilities.

- [x] Design has been finalized
- [x] Link to original design ticket: #2911 (original design ticket)
- [x] Link to related ticket: #3029 (MVP ticket) & #3086 3030 (post MVP ticket)
- [x] Link to Redpen: https://redpen.io/p/bha12cf7387de4f7e7
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Hover state for elements are designed

## Requirements Checklist:
- [ ] Sticky Side Share buttons (disappears on mobile)
- [ ] Share buttons at the bottom of the blog post

## Desktop (with hover states):
Post-MVP-hover-states@2x

### PR DESCRIPTION
**Pull request by mmmavis**
Closes #3157 

### Test pages
- https://foundation-mofostaging-pr-3383.herokuapp.com/en/blog/post/
- (with related content section) https://foundation-mofostaging-pr-3383.herokuapp.com/en/blog/test-post-2/
- (with related content section) https://foundation-mofostaging-pr-3383.herokuapp.com/en/blog/test-post-3/

61010126-e73c8300-a329-11e9-99d1-c3551a82a1c0

Sticky side button group is set to be `140px` from the nav so the button group can align with the blog title. Depending on how much content is after the blog body... in some cases the sticky side button group can reach to the bottom (and align with the last element in the blog body) and in some other cases it won't align.

### CODE REVIEW

**Comment by mmmavis** [comment]
@beccaklam  

> ## Tablet:
> Buttons should fit in one line horizontally

If we don't wanna stack the buttons on tablet... are we okay with letting the buttons wrap themselves based on its container width? This means on some screens the buttons might show in 2 rows, with the first row having 3 buttons and second row having the last button.

**Comment by beccaklam** [comment]
> @beccaklam
> 
> > ## Tablet:
> > Buttons should fit in one line horizontally
> 
> If we don't wanna stack the buttons on tablet... are we okay with letting the buttons wrap themselves based on its container width? This means on some screens the buttons might show in 2 rows, with the first row having 3 buttons and second row having the last button.

Hmm ... it wouldn't be ideal. Looking at the screen again the left aligned design isn't actually working that well. I took a look at how we handled the social buttons on PNI and was wondering how big of a lift would it be to have the bottom social buttons behave like the creepometer share buttons? 😬 

Screen Shot 2019-07-11 at 3 23 35 PM

**Comment by mmmavis** [comment]
@beccaklam from #3321, #3322, #3323, and PR #3352 (and now landed on [staging style guide](https://foundation.mofostaging.net/en/style-guide/) the "share button group" section) I'm assuming our goal is to have one share button "group" component that can work across the site (both functionalities and design). Buttons on PNI aren't really following specs in #3321, #3322, #3323 so I assume they should on the to-update list.

I think we need to decide whether we want to unify social button styling from the "button" level or "button group" level and update the following tickets accordingly.

- #3321 (button level)
- #3322 (button group level)
- #3323 (both)

Having a shared button group component makes future implementation and design a lot easier as the code and style is set and we don't have to worry about devs/designers accidentally creating a new version of share button group. However, I do understand that it is challenging to design something that can look good for every use case. So if we want to adjust button group style case by case then we shouldn't design it from "button group" level as this means we will end up having styling overrides everywhere. 

Do you think we should loop others in for this? Whatever we decide we just need to be consistent about it so we don't end up going back to where we were before 😂  (aka having multiple versions of share button (group) styles on the site)

**Comment by beccaklam** [comment]
> (Sorry for the lengthy reply. We can hop on a call to chat about this as well)
> 
> @beccaklam from #3321, #3322, #3323, and PR #3352 (and now landed on [staging style guide](https://foundation.mofostaging.net/en/style-guide/) the "share button group" section) I'm assuming our goal is to have one share button "group" component that can work across the site (both functionalities and design). Buttons on PNI aren't really following specs in #3321, #3322, #3323 so I assume they should on the to-update list.
> 
> We need to decide whether we want to unify social button styling from the "button" level or "button group" level and update the following tickets accordingly.
> 
>     * #3321 (button level)
> 
>     * #3322 (button group level)
> 
>     * #3323 (both)
> 
> 
> Having a shared button group component makes future implementation and design a lot easier as the code and style is set so we don't have to worry about devs/designers accidentally creating a new version of share button group. However, I do understand that it is challenging to design something that can look good for every use case... If we want to adjust button group style case by case then we shouldn't design it from "button group" level as this means we will end up having styling overrides everywhere.
> 
> Do you think we should loop others in for this? Whatever we decide we just need to be consistent about it so we don't end up going back to where we were before 😂 (aka having multiple versions of share button (group) styles on the site). Don't worry about if I have to redo the implementation or not, I rather fix things early than late 😉 .
> 
> (If I understand Sketch's symbols correctly)
> If the element is something designers can't turn into a Sketch Symbol
> ➡️ then it shouldn't be part of the [styleguide](https://foundation.mozilla.org/en/style-guide/) as it means this element is something that can't be standardized
> ➡️ we should have **design guidelines** for this particular element for designers to follow when they create comps (e.g., make sure button icon is x pixels away from the button text, space in between two buttons is y pixels etc)

Hey @mmmavis no worries about the lengthy reply at all. I see what you mean, and knew that I was opening a larger conversation by asking about the PNI styling. I think currently the design I gave you may not be flexible enough and think perhaps we should go with something more responsive. And yes we should pull others in ... maybe we can talk about it Monday after stand?

**Comment by beccaklam** [comment]
FWIW, this is what I'm thinking instead:
## Desktop:
Screen Shot 2019-07-12 at 11 02 47 AM

## Tablet
Screen Shot 2019-07-12 at 11 02 54 AM

## Smaller Tablet
Post-MVP-tablet Copy 2@2x

## Mobile
Screen Shot 2019-07-12 at 11 03 09 AM

But I do think we should talk it through with the larger design team first. Just dropping this here and I also dropped the designs into the blog redpen. And then we can decide how to update the tickets.

**Comment by beccaklam** [comment]
Hi @mmmavis so based on our conversation today I would say **113px** wide would be the **min width** for the single row buttons. That is how wide the button would be for Facebook (the longest word) with 8px spacing between the button, icon, and the label:
Screen Shot 2019-07-15 at 4 06 42 PM
Let me know if you need anything else!

**Comment by mmmavis** [comment]
@beccaklam the minimum width for the Facebook button seems to be roughly `130px` so I used that number instead of `113px`. I also grouped the buttons in pairs so when the buttons get wrapped we won't have just one orphan button sitting on the second row for certian screen sizes. Let me know what you think.

image

| Type                             |         |   |          |
|-------------------------------|---------|---|----------|
| border                        | 2px*2   | = |  4px     |
| side padding                  | 16px*2  | = |  32px    |
| icon                          | 16px    | = | 16px     |
| spacing between icon and text | 8px     | = |  8px     |
| width of "Facebook"           | 70.35px | = | 70.35px  |
| **Total mininum width**           |         | = | 130.35px |

**Comment by mmmavis** [comment]
@Pomax this is ready for code review! 😃

**Comment by Pomax** [comment]
Code looks good! @mmmavis @beccaklam do we want to make the buttons fade out/in rather than abruptly existing, though? It might be jarring to readers to have them suddenly exist or be gone?

**Comment by mmmavis** [comment]
> Code looks good! @mmmavis @beccaklam do we want to make the buttons fade out/in rather than abruptly existing, though? It might be jarring to readers to have them suddenly exist or be gone?

Sounds good but I'll let @beccaklam decide what kind of effect we want to have. I'll file a followup ticket and tag you both soon 😄

**Pull request merged**
