### PR TITLE
heroku3 version bump for API depreciations, removal of py packages th…

### LINKED ISSUE #7734: heroku3 version bump for API depreciations
Email from Heroku :

[Action Required] Required Parameter for Domain Create Heroku API endpoint starting November 1, 2021
9 messages
'Ethan Limchayseng' via accounts <accounts@mozillafoundation.org>	Wed, Oct 27, 2021 at 5:16 PM
Reply-To: Ethan Limchayseng <elimchayseng@salesforce.com>
To: Ethan Limchayseng <elimchayseng@salesforce.com>
Bcc: accounts@mozillafoundation.org

Hi there, 

My name is Ethan and I'm a Product Manager for Heroku/Salesforce.

I'm reaching out to give you a heads up about a change to a Heroku Platform API attribute that took place in October of last year. See the original changelog post here.

We've seen that you're currently still using the Domain Create endpoint without the sni_endpoint parameter. As the changelog says, if the parameter isn't provided, you'll begin to see 422 errors starting November 1, 2021.

In order to prevent this, please make sure you add the required parameters for Domain Create, as detailed in the changelog entry, when using the Heroku Platform API or any other HTTP libraries you choose to use. You can see the full instructions in the Dev Center article linked above. 

If you're using the Heroku CLI, you will most likely need to update to version 7.59.1 or higher, which now includes this parameter by default. This may be as simple as running $ heroku update in your CLI depending on the nature of your installation. You can verify this here at the Heroku CLI Dev Center article. 

Let me know if you have any questions, and if you need further help you can always open a ticket at support.heroku.com.

Thanks,

-- 
Ethan Limchayseng
Product Manager, Platform Team/Heroku Runtime 
elimchayseng@salesforce.com

### PR DESCRIPTION
**Pull request by jzinner**
Closes #7734
Related PRs/issues #

So Dependabot suggested a partial fix which I Closed without merging:  https://github.com/mozilla/foundation.mozilla.org/pull/7728.
Dependabot then auto deleted the branch when I choose "Close the Pull Request"

### CODE REVIEW

**Comment by tomusher** [comment]
This looks good to me.

@Pomax - the removed dependencies were done by `pip-compile` when `heroku3` was upgraded - I guess it's just catching up with removals that have been missed in the past, but can you cast your eye over them too?

**Comment by jzinner** [comment]
To generate a new requirements.txt file, run:

```
sudo pip install pip-tools
pip3 install pip-tools
python3 -m piptools compile --upgrade-package heroku3
```

**Comment by jzinner** [comment]
Check the build through mofo-ra-foundation channel, slack bot. 

Also a [link to the heroku3 pypi, search for add_domain](https://pypi.org/project/heroku3/) - this is where sni_endpoint logic came from

**Review by Pomax — APPROVED** [review]
this looks sane to me, but let's land this on Wednesday if we can, so it doesn't interfere with the PNI mergers that will happen on Tuesday.

**Pull request merged**
