### PR TITLE
Add Cloudflare cache invalidation support

### PR DESCRIPTION
**Pull request by tomusher**
Adds support for Cloudflare cache invalidation so we can get caching enabled

### CODE REVIEW

**Review by KalobTaulien — APPROVED** [review]
LGTM. Thanks for adding this Tom!

**Review by KalobTaulien — CHANGES_REQUESTED** [review]
Looks like tests aren't passing. Havent looked into why yet. But we should dig into that.

**Comment by tomusher** [comment]
I don't think there's anything in this change that should be causing these tests to fail - any idea what might be going on?

**Comment by Pomax** [comment]
Testing the failing tests "with real data on the running server" does not seem to run into any trouble (vote posting through a product page is HTTP 200 for example), what are these two tests doing...

**Review by KalobTaulien — APPROVED** [review]

**Review by Pomax — APPROVED** [review]

**Pull request merged**
