### PR TITLE
[Part 1 of 3] Newsletter sign up button/form

### PR DESCRIPTION
**Pull request by youriwims**
Related PRs/issues #2994

Updated donate button styles & extended mobile nav behavior to tablet dimensions.

### CODE REVIEW

**Comment by youriwims** [comment]
Screen Shot 2019-04-17 at 4 34 46 PM

@mmmavis , this is caused by a box-shadow on `.btn:focus`, do we want to keep this?

**Comment by mmmavis** [comment]
@sabrinang wondering if we should design another type of button for use cases like above? (button with transparent background, no border)

**Comment by sabrinang** [comment]
For the use case that we need an icon before a link or label, we shouldn't use a button at all then? It should be a link with an in-line icon that comes before it. Similar to how read more →  has an arrow after it, I can see donate having the heart before it

**Comment by mmmavis** [comment]
@youriwims - @sabrinang and I are chatting now. This might be special "anchor" or "button" style that we wanna add to our style guide. Will get back to you!

**Comment by youriwims** [comment]
Okay, not a problem. Can I land this in the meantime so I can move on to Part 2(adding the newsletter button & form) of this?

**Comment by mmmavis** [comment]
@youriwims thanks for flagging it. I chatted with @sabrinang and @kristinashu and we are all okay with making the "donate" link using the default link behaviour for now. i.e., remove `btn` class from it

donate

**Comment by youriwims** [comment]
okay, sounds good. Thank you!

**Comment by kristinashu** [comment]
Hover is looking good but sizing seems generally a little small. The "Donate" text was designed to be the same font size and weight as the nav item. The heart icon also seems a little small, it should be a little bigger so it stands out.

image

**Comment by youriwims** [comment]
Sorry, I was under the impression from Mavis' conversation with you and
Sabrina that I should be removing the `.btn` class from this which gives it
those styles...just want to confirm that it should have the same font &
font weight as nav items?

As for the heart, I swapped the dimensions accidentally 😬.Thanks for
pointing that out—I'll go back and fix that!

>

**Comment by youriwims** [comment]
@kristinashu, all should be fixed now. Let me know if any other updates need to be made :)

**Comment by Pomax** [comment]
Chrome with mobile view set to something with a small screen shows me an empty nav... =S

image

**Comment by youriwims** [comment]
Thanks for pointing this out @Pomax 😬

**Comment by Pomax** [comment]
Looks like there's still something funny happening with the width. 

### foundation site, mobile view:

image

### https://foundation-mofostaging-pr-3028.herokuapp.com/en/, mobile view:

image

**Pull request merged**
