### PR TITLE
Update publication ToC thumbnail background's position and sizing rules

### LINKED ISSUE #6141: Adjust Publication's ToC thumbnail background's position and sizing
Based on user feedback, we are going to adjust the background styling rules to `background-size: cover;` and `background-position: centter`

Related issue: #5847

### PR DESCRIPTION
**Pull request by mmmavis**
Closes #6141 

I downloaded the image from production to set up these test pages. Feel free to upload other images to test it out as well.

Test: https://foundation-s-issue-6141-xsi3bh.herokuapp.com/en/publication-page-with-child-article-pages/
Edit: https://foundation-s-issue-6141-xsi3bh.herokuapp.com/cms/pages/49/

---

Test page: https://foundation-s-issue-6141-xsi3bh.herokuapp.com/en/publication-page-with-chapter-pages/
Edit: https://foundation-s-issue-6141-xsi3bh.herokuapp.com/cms/pages/50/

### CODE REVIEW

**Review by sabrinang — COMMENTED** [review]
Great the images are showing up fully now on child publication pages and narrow viewport publication pages!

For the images here, is there a way to increase image quality for these images? some of the line details are getting blurred or lost but not sure if this is related to the resizing or not
image

**Comment by mmmavis** [comment]
@sabrinang good catch! I've doubled up the pixel values so the image looks better on retina device. If you visit the test pages again you should see the difference.

**Comment by mmmavis** [comment]
@Pomax I have no idea why Percy test says
> Missing build resources, check your CI logs for failures 

🙄

**Review by sabrinang — APPROVED** [review]
Awesome thanks for improving the image quality 👍

**Comment by Pomax** [comment]
I see the CI log say the following:
```
[percy] stopping percy...
[percy] waiting for 28 snapshots to complete...
[percy] StatusCodeError 503 - "upstream connect error or disconnect/reset before headers. reset reason: connection termination" | Tue Feb 02 2021 00:09:04 GMT+0000 (Coordinated Universal Time)
[percy] StatusCodeError 400 - {"errors":[{"status":"bad_request","detail":"Finalizing snapshot 490765474 failed: cannot finalize before all snapshot resources are uploaded. This is likely a client library bug, please make sure that content for all SHAs in 'missing-resources' from the snapshot response are uploaded before calling finalize."}]} | Tue Feb 02 2021 00:09:04 GMT+0000 (Coordinated Universal Time)
[percy] done.
[percy] error finalizing build
[percy] StatusCodeError 400 - {"errors":[{"status":"bad_request","detail":"Finalizing build 8637426 failed: cannot finalize before all snapshot resources are uploaded. This is likely a client error, please make sure that content for all SHAs in 'missing-resources' from the snapshot response are uploaded before calling finalize."}]} | Tue Feb 02 2021 00:09:20 GMT+0000 (Coordinated Universal Time)
```

**Review by Pomax — APPROVED** [review]
code is R+, let's deal with Percy separately

**Comment by mmmavis** [comment]
@Pomax where did you find the log? I was looking at 
image
but wasn't able to spot the messages you posted above.

**Pull request merged**
