### PR TITLE
center the submit button at small sizes

### PR DESCRIPTION
**Pull request by Pomax**
Closes https://github.com/mozilla/foundation.mozilla.org/issues/3195

This centers the submit button in the nav as medium/small sizes.

screenshot 776

screenshot 777

### CODE REVIEW

**Comment by Pomax** [comment]
Note that we also need to "move" the button to the visual center, and align/justify don't seem to be enough for that.

**Comment by mmmavis** [comment]
Ummm we can loop designers in. But I _think_ vertically aligning the button is what we wanna do here? ?? /cc @kristinashu @sabrinang

**Comment by kristinashu** [comment]
This button should **right aligned** and **vertically centered** and behave responsively like on the main site:

image

and in the tablet comp: https://redpen.io/p/nt88aa617b390e8eb0
image

and mobile comp:
image

**Comment by Pomax** [comment]
aha, in that case I misunderstood gideon's report. Going the align-items-center route =D

**Pull request merged**
