### PR TITLE
Fix #3900: comment out watch video button from mozfest homepage

### LINKED ISSUE #3900: Remove Watch Video button from mozfest homepage
Remove the button at the top of the site. Bonus: make it toggleable via the CMS so that we can easily add it back in later.

### PR DESCRIPTION
**Pull request by ragnarokatz**
Closes #3900

### CODE REVIEW

**Comment by gideonthomas** [comment]
@Pomax is this fix ok?

**Comment by gideonthomas** [comment]
@ragnarokatz are you able to make the fix that @Pomax suggests here: https://github.com/mozilla/foundation.mozilla.org/issues/3900#issuecomment-555276136?

@mmmavis Feel free to take yourself off review if you're comfortable with me handling it.

**Comment by ragnarokatz** [comment]
@gideonthomas yes. I will do so shortly.

**Comment by Pomax** [comment]
@ragnarokatz it looks like maybe something went wrong with the commits: we don't want to remove the video url field, we just want to update the template so that if the field has no value, we don't show a video button. That way no models or admin panels need to change.

**Comment by ragnarokatz** [comment]
@Pomax I see.

I think the existing code already does this in the following:

```
{% if page.banner_video_url %}
<a class="btn btn-primary" href="{{ page.banner_video_url }}" target="_blank" id="mozfest-home-watch-video-button">Watch Video</a>
{% endif %}
```

I'm not sure `if page.banner_video_url` will return true if a `none` object is passed in for `banner_video_url`. If that is the case, I can change it to either `{% if variable is defined %}` or `{% if variable is not none %}`

**Comment by gideonthomas** [comment]
@ragnarokatz can you commit the changes you mention in your PR? I can test it and see if that works.

**Comment by ragnarokatz** [comment]
@gideonthomas done. In order to remove the watch video button, simply do not pass in `page.banner_video_url` or pass in a null.

**Comment by gideonthomas** [comment]
Sorry to get back to you so late @ragnarokatz. Since the fix for this ticket was changed to - if the url doesn't exist, don't show it -- I think the code that already exists in the repository is correct. You dug into the code to find out that we have a field that can be toggled and that's how we were able to identify what the right course was for fixing this ticket, so we really appreciate you digging into the code. With that said, it looks like code-wise, nothing needs to be fixed here.

**Comment by ragnarokatz** [comment]
@gideonthomas I see. No worries.

**Pull request closed without merging**
