### PR TITLE
Update the directory we run compilemessages in

### PR DESCRIPTION
**Pull request by cadecairos**
...otherwise it compiles messages from dependencies outside our project

### CODE REVIEW

**Comment by TheoChevalier** [comment]
The invoke task bit doesn’t work on my machine, trying to figure out what’s wrong

```
theochevalier@Theos-MBP:foundation.mozilla.org (compilemessages_fix=)$ inv compilemessages
Traceback (most recent call last):
  File "/usr/local/bin/inv", line 10, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python3.7/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/usr/local/lib/python3.7/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/usr/local/lib/python3.7/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/lib/python3.7/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/Users/theochevalier/Documents/GitHub/foundation.mozilla.org/tasks.py", line 107, in compilemessages
    copy("pt_BR/LC_MESSAGES/django.po", "pt/LC_MESSAGES/django.po")
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'pt_BR/LC_MESSAGES/django.po'
```

**Comment by cadecairos** [comment]
> The invoke task bit doesn’t work on my machine, trying to figure out what’s wrong

oh right, there's a non-docker version. I need to update that as well I think

**Comment by TheoChevalier** [comment]
> > The invoke task bit doesn’t work on my machine, trying to figure out what’s wrong
> 
> oh right, there's a non-docker version. I need to update that as well I think

That’s the one you updated, actually. So we will need to figure out why it doesn’t work, then update the docker one

**Comment by cadecairos** [comment]
hmm, okay I'm on it

**Comment by cadecairos** [comment]
the problem is that the `manage` task changes directory back to the root.

**Comment by cadecairos** [comment]
Ran out of time to get this working. locally, I'm seeing an error about gettext not being available (on my host OS (windows) and in the docker container (though it is installed according to the dockerfile)

Going to need someone to take this one across the finish line. @Pomax ?

**Comment by Pomax** [comment]
- [x] windows `inv setup` 
- [?] windows `inv docker-new-env` (I can't for the life of me get docker working on windows)
- [] mac `inv setup` 
- [] mac `inv docker-new-env`

**Comment by Pomax** [comment]
I can't make this "not work" locally, so.... I guess time to merge it in?

**Pull request merged**
