### PR TITLE
Updated MozFest site's title meta

### LINKED ISSUE #3249: MozFest: fav icon and title
Please update the fav icon from the m to the mozfest specific one:
[fav icon.zip](https://github.com/mozilla/foundation.mozilla.org/files/3224678/fav.icon.zip)

Is it possible to update the site name from `Mozfest` to `Mozilla Festival`

image

### PR DESCRIPTION
**Pull request by mmmavis**
Closes #3249 

https://foundation-mofostaging-pr-3264.herokuapp.com/en/

### Review tips

To make main Foundation site pages (or vice versa, MozFest site) show, you have to manually change the setting on Wagtail: 😂 

1. go to /cms on review app
2. go to "Setting" from side menu
3. choose "Sites"
4. click on `foundation-mofostaging-pr-<pr-number>.herokuapp.com`
5. choose "CHOOSE A DIFFERENT ROOT PAGE"
6. select "homepage" (or vice versa, MozFest site)
7. visit review app again

### CODE REVIEW

**Comment by kristinashu** [comment]
Please don't merge yet! The icon is super pixely so I'm asking @sabrinang if we can use the cubes instead of the full icon.

**Comment by sabrinang** [comment]
We can try using the Mozilla Festival Logo in white with no black box if that helps? We should use logo not cubes as we used that to represent experiences at MozFest

**Comment by kristinashu** [comment]
Ok @mmmavis here's the icon in white on a transparent background (it should be a little better): 
[favicon_package_v0.16.zip](https://github.com/mozilla/foundation.mozilla.org/files/3230247/favicon_package_v0.16.zip)

**Comment by mmmavis** [comment]
@kristinashu do we want the icon on transparent background or white? If it's the former can you attach the right `.svg` as well as I need to export it into PNGs for various sizes. The one in the zip is on white and I don't know how to remove the white background before exporting it.

**Comment by kristinashu** [comment]
Here's the white icon on a transparent background as an svg and at png at 392x392 and 360x360:

[white icon on transparent.zip](https://github.com/mozilla/foundation.mozilla.org/files/3233399/white.icon.on.transparent.zip)

Let me know if you need anything else!

**Comment by mmmavis** [comment]
@kristinashu this is ready for review again. You might wanna open the review app on a different browser (just private mode) as the old favicon probably had been cached by the browser you opened it on.

**Comment by sabrinang** [comment]
should we colour it black or blue? white doesn't show up on current tab:
image

**Comment by mmmavis** [comment]
image

It shows for me on private browsing on FF. I think it all depends on user's browser theme. I'm not sure what the best practices are for favicons. Let me know if we wanna change the favicon to another color.

**Comment by gideonthomas** [comment]
eek, @mmmavis can we revert/redo this? I didn't realize there were changes made after review.

Before, `Mozfest - <SEO title>` was ok (not ideal, but good enough). 

But since it's been changed to `Mozilla Festival - <SEO title>`, it wouldn't make sense to put anything after the `-` for the homepage (e.g. "Mozilla Festival - 2019", or "Mozilla Festival - Mozilla Festival 2019") because that's what shows up in a google search.

Can we change it to the following?
```django
Mozilla Festival 2019{% if page.specifics.seo_title %} - {{ page.specifics.seo_title }}{% else %} {{ page.title }}{% endif %}
```

**Comment by mmmavis** [comment]
@gideonthomas I didn't make changes to the title meta portion you reviewed and r plused (it was already changed to `Mozilla Festival` at the time you reviewed. See [here](https://github.com/mozilla/foundation.mozilla.org/pull/3264/commits/b80091246a7c1ba398024e30ce6d30f2b3ff507e)). The changes done after you gave the R+ was just to remove MozFest favicons since we decided to use go with what the main Foundation site is using.

**Comment by mmmavis** [comment]
I'll revert the changes. @gideonthomas can you file a new ticket or update this https://github.com/mozilla/foundation.mozilla.org/issues/3249 so it's clear what changes we should be making?

**Comment by gideonthomas** [comment]
Damn, sorry I missed it in the review and in the ticket; oversight on my part. The PR is small so I'll create it myself if you're up for reviewing it.

**Comment by mmmavis** [comment]
@gideonthomas no prob! I just wanted to make sure I didn't accidentally sneak in more changes after the review. Let me know if there's anything I can help to push this forward. 👍

**Pull request merged**
