### PR TITLE
make nonexistent tags not cause a crash

### PR DESCRIPTION
**Pull request by Pomax**
Closes https://github.com/mozilla/foundation.mozilla.org/issues/3659

Also adds a test for nonexistent tags as part of the percy run to ensure we have a screenshot in the future to warn us.

compare:
- https://foundation.mozilla.org/en/blog/tags/mozillawedwdwfwef/ (500 error)
- https://foundation-mofostaging-pr-3660.herokuapp.com/en/blog/tags/mozillawedwdwfwef/ (should be an actual page)

### CODE REVIEW

**Comment by alanmoo** [comment]
Can the message "0 results for" on the now-existant page show the term you tried to use?

**Comment by youriwims** [comment]
+1 to prev. comment.

**Comment by Pomax** [comment]
Not without substantially more rewriting, since that string is pulled from the tags (the "real" tags), not from what's in the URL bar.

**Comment by alanmoo** [comment]
What about removing the "for"?

**Comment by Pomax** [comment]
also quite easy, let me add that in.

**Pull request merged**
