### PR TITLE
iFrame Component updates

### PR DESCRIPTION
**Pull request by gvn**
Related issue: #1512

### CODE REVIEW

**Comment by gvn** [comment]
For design review: https://foundation-mofostaging-pr-1522.herokuapp.com/test/

**Comment by taisdesouzalessa** [comment]
@gvn I can't see the herokuapp link. Could you update it again, please?

**Comment by gvn** [comment]
@taisdesouzalessa Try again now!

**Comment by taisdesouzalessa** [comment]
Yay! It works, thanks :)

**Comment by gvn** [comment]
I believe that is something we're doing, yeah. It is responsive so will scale to whatever container width its parent has.

**Pull request merged**
