### PR TITLE
Add a configurable referrer policy header

### LINKED ISSUE #710: Implement Referrer-Policy Header
The use of Referrer Policy can help protect the privacy of your users by restricting the information that browsers provide when accessing resources kept on other sites

[Mozilla Web Security Guidelines (Referrer Policy)](https://wiki.mozilla.org/Security/Guidelines/Web_Security#Referrer_Policy)

### PR DESCRIPTION
**Pull request by cadecairos**
Fixes #710

### CODE REVIEW

**Comment by Pomax** [comment]
Can we add a test somewhere that lets us verify that the "referer" header gets sent?

**Comment by cadecairos** [comment]
Does this project have a test suite yet?

**Comment by cadecairos** [comment]
@Pomax so, we going to be test that Django is properly applying this middleware to requests? Do you have any suggestions on what this test might look like?

**Comment by cadecairos** [comment]
@Pomax ping!

**Comment by gvn** [comment]
@Pomax @cadecairos – Is this still a thing we want to do?

**Comment by cadecairos** [comment]
Yes, I'd like to land this to boost our score on the SSL observatory

**Comment by Pomax** [comment]
@cadecairos I'd imagine the test to mostly look like a django test Client connecting, and then verifying the `result.headers` (assuming that's where we can find them). That should be good enough.

**Comment by Pomax** [comment]
@cadecairos is this still a pending PR or did we solve this in the main code already through some other PR(s)?

**Comment by cadecairos** [comment]
Nope, this has not beenimplemented yet.

**Comment by cadecairos** [comment]
I'll pick this up in the next couple weeks and write the necessary tests

**Pull request merged**
