### PR TITLE
Updated text stylings for improved contrast/readability

### LINKED ISSUE #6285: [Publications] Implement revised text size/colors to improve constrast/legibility
based on https://github.com/mozilla/foundation.mozilla.org/issues/5950#issuecomment-786282143

Areas of improvement are:
- [x] version/date & document size from `#999999` → `#cccccc`
- [x] breadcrumb from `12px` `#b7b9fa` → `16px` `#e7e7fc`
- [x] summary anchor links from `#666666` → `#333333` 
- [x] previous/next from `#666666` → `#333333`

image

### PR DESCRIPTION
**Pull request by danielfmiranda**
Closes #6285 
Related PRs/issues #

Preview for breadcrumb, breadcrumb-arrow, summary anchor and previous/next links: [here](https://foundation-s-6285-publi-htbp53.herokuapp.com/en/publication-page-with-child-article-pages/fixed-title-article-page/)
Preview for secondary-subtitle (version number): [here](https://foundation-s-6285-publi-htbp53.herokuapp.com/en/publication-page-with-chapter-pages/ )

## Checklist

**Changes in Models:**
- [x] [Are my changes backward-compatible]

### CODE REVIEW

**Comment by mmmavis** [comment]
@danielfmiranda I'm gonna review this PR once we know what line heights we should use.

**Comment by sabrinang** [comment]
Should I be reviewing these pages?
https://foundation-s-6285-publi-htbp53.herokuapp.com/en/publication-page-with-chapter-pages/
https://foundation-s-6285-publi-htbp53.herokuapp.com/en/publication-page-with-child-article-pages/

**Comment by mmmavis** [comment]
@danielfmiranda I forgot to mention to you that PR should include review app test links (PR template should already have a placeholder line for it). Ping me if you have issues logging into the review app! 😀

**Review by sabrinang — CHANGES_REQUESTED** [review]
I reviewed:

- https://foundation-s-6285-publi-htbp53.herokuapp.com/en/publication-page-with-chapter-pages/
- https://foundation-s-6285-publi-htbp53.herokuapp.com/en/publication-page-with-child-article-pages/

Changes to make:
- Version/date & document size is still #999999
- Breadcrumb arrow › can also be 16px to match 
- Breadcrumb line height to be 1.333 (to stay the same)

**Comment by danielfmiranda** [comment]
Hi @sabrinang, I have made the requested changes. 
The arrow, even though it is 16px with a line height of 1.333333, did not seem to change too much. If you would like me to make it larger, let me know 😄

**Review by sabrinang — COMMENTED** [review]
Thanks for making those updates Daniel! The only thing left is that the document size  _(which appears by the download pdf button)_, `publication-hero-file-size`, text color also needs to be updated too

**Comment by danielfmiranda** [comment]
Hi @sabrinang, the change to the file size is now pushed. Apologies for the delay!

**Review by sabrinang — APPROVED** [review]
👍 Awesome — thanks for that last update Daniel!

**Review by mmmavis — APPROVED** [review]
Wooooohoooo! Great work, @danielfmiranda ! I'm merging your PR now. 🎉 🎉 🎉 🎉 🎉

**Pull request merged**
