### PR TITLE
Summary box width and Publication offset are the same size now

### LINKED ISSUE #5786: Make widths the same for summary/white block areas
On the publication page: Cut out width (align edge of 2nd and 11th columns) should match/be same as summary box width of article pages

Target area:

Criteria:
- [ ] Make the white block that enters the hero a bit smaller so it matches the width of the Summary block 

**Note**: The white block in the Publication Page is just an empty block, there's no content in it. It's purely for aesthetics.

### PR DESCRIPTION
**Pull request by KalobTaulien**
Closes #5786 

## Checklist
- [x] Make the white block that enters the hero a bit smaller so it matches the width of the Summary block

Review app link: https://foundation-s-5786-make--xq35ym.herokuapp.com/

**Publication page:**
image

**Summary box:**
image

**Note:** This is making use of the `.article-summary` and overwriting it using bootstrap classes. I only added a height of 50px to ensure the box always looks like it's part of the content.

### CODE REVIEW

**Comment by sabrinang** [comment]
@KalobTaulien How do I get to the review pages (one with table of contents, one with summary) so I can compare the changes from the review app link?

**Review by sabrinang — CHANGES_REQUESTED** [review]
The publication page and article summary box matches now!

However, I noticed children publication pages box width needs to expand to match them now:
image
example from https://foundation-s-5786-make--xq35ym.herokuapp.com/en/publication-page-with-chapter-pages/without-great-picture-owner-fire-town-base-those-door-know-indicate-consider-much-concern-successful-can-their-study/

**Review by mmmavis — COMMENTED** [review]
will do a code review once this passes design review 👍

**Comment by KalobTaulien** [comment]
Hey @sabrinang we should chat through this, because it breaks out of the grid it gets tricky to code this in an easy-to-maintain way.

**Comment by sabrinang** [comment]
@KalobTaulien yeah let chat what is feasible to align the three or what you recommend that makes it easier to maintain
image

**Pull request closed without merging**
