### PR TITLE
Remove people page

### PR DESCRIPTION
**Pull request by Pomax**
Closes https://github.com/mozilla/foundation.mozilla.org/issues/2591

### CODE REVIEW

**Comment by mmmavis** [comment]
@Pomax let's remove `people.scss` as well

**Comment by alanmoo** [comment]
This feels like a good opportunity to leverage Percy on any page that might possibly share styling.

**Comment by Pomax** [comment]
marked as blocked by https://github.com/mozilla/foundation.mozilla.org/issues/2667

**Comment by Pomax** [comment]
superceded by https://github.com/mozilla/foundation.mozilla.org/pull/2870)

**Pull request closed without merging**
