### PR TITLE
Made the attribution field of blockquotes optional

### LINKED ISSUE #6454: Make blockquote authors optional across all templates
```python

class QuoteBlock(blocks.StructBlock):

    # The goal is to be able to cycle through multiple quotes,
    # so let's accept multiple quotes to start even if we only show one for now.
    # This way we don't have to migrate the model again later

    quotes = blocks.ListBlock(blocks.StructBlock([
        ('quote', blocks.CharBlock()),
        ('attribution', blocks.CharBlock(required=False))  # <- Need that 
    ]))

    class Meta:
        template = 'wagtailpages/blocks/quote_block.html'
        icon = 'openquote'
        help_text = 'Multiple quotes can be entered, but for now we are only using the first'

```

### PR DESCRIPTION
**Pull request by danielfmiranda**
Closes #6454
Related PRs/issues #

**Link to sample test page**: https://foundation-s-6454-optio-bff0t0.herokuapp.com/en/blog/stay-our-ten-those-us-live/

## Checklist

**Changes in Models:**
- [x] [Are my changes backward-compatible]

### CODE REVIEW

**Review by Pomax — CHANGES_REQUESTED** [review]
Technically fine, but you will need to renumber the migration... thankfully, this is pretty simple:
- check what the latest migration is on master
- rename your migration file to "the next number" (e.g 0007_......)
- edit the file so that the "depends_on" is the name of the highest migration on master
- commit and push

**Comment by Pomax** [comment]
@kristinashu I added you for design review, just to make sure we're not landing code that's missing style tweaks that would improve the attribution-less quote.

**Review by kristinashu — APPROVED** [review]
Looks good!

**Comment by danielfmiranda** [comment]
Hi @Pomax thank you for the heads up, and for the easy-to-follow instructions. I have made the requested changes and pushed them for re-review :)

**Review by Pomax — APPROVED** [review]

**Pull request merged**
