### PR TITLE
Horizontal nav

### PR DESCRIPTION
**Pull request by ScottDowne**
Building the nav as shown in these comps https://redpen.io/pg11648642fd877912

I'm actually not aware of a ticket specifically for this. @kristinashu is there a ticket for just the nav?

### CODE REVIEW

**Comment by ScottDowne** [comment]
Actually, probably should send this through design review first (forgot)

**Comment by kristinashu** [comment]
Comp
image

PR
image

- [ ] Here's the ticket https://github.com/mozilla/foundation.mozilla.org/issues/1560 it has some specifics about the font styling (what you have is close but the sub nav items should be a thinner font weight and slightly smaller)

- [ ] Like in the mobile view, we don't need to show "Key Challenges" since people see it in the menu

- [ ] Mobile: nav items seem to have disappeared from dropdown
screen shot 2018-06-04 at 12 57 07 pm

**Comment by ScottDowne** [comment]
@kristinashu updated.

I think given that most of the header changes are already like they are in my PR and not relatedto the nav, to keep this pr smaller and easier to review, let's do header changes in another ticket if possible.

**Comment by kristinashu** [comment]
Cool, sounds good! 

Sorry but I realize now that making the font change weights shifts all the text over on hover. My bad! Please make the font bold all the time.

nav

**Pull request merged**
