### PR TITLE
switching to new classnames - #1321

### PR DESCRIPTION
**Pull request by gvn**
Related issue: #1321

### CODE REVIEW

**Comment by gvn** [comment]
This won't show up on the staged PR, so for design review see this screenshot:

screen shot 2018-04-12 at 11 45 08 am

**Comment by kristinashu** [comment]
Looks good as long as that is reflected on all the primary pages, not just Participate.

**Comment by alanmoo** [comment]
So which pages need to be compared? I see a few more on "Initiatives" but I think that's it.

**Comment by kristinashu** [comment]
@alanmoo probably all the wagtail pages: Initiatives, Participate, People, About Us, (News looks ok I think). Not sure what's happening with all the Opportunity and Campaign pages.

**Comment by alanmoo** [comment]
Opportunity and Campaign will likely need updates in the CMS editor, not in the code.

**Pull request merged**
