### PR TITLE
Creep-o-meter section changes

### LINKED ISSUE #5236: Creep-o-meter work
### Todo backend (estimate: 2)
- [ ] double checking that things still work purely with the frontend removed

possibly, but we're not sure (follow up if necessary), not estimating unless necessary

- [ ] Backup/preserve likely-to-buy data for existing products ([cade] let's run a query for this data and back it up in our S3 archives for potential future use)
- [ ] Remove ‘Likely to buy’ backend models
- [ ] Remove 'Likely to buy' stats aggregation during manage.py

Note that removing the likely/unlikely to buy also allows us to clean up the statistics code and the aggregation commands on the python side (but let's make sure to capture a snapshot of this data before we migrate it out of existence!)

### Todo frontend (estimate: 3)
- [x] Remove ‘Likely to buy’ question 
- [x] Remove ‘Likely to buy’ results 
- [x] Remove "Tell us what you think" banner
- [x] Restyle "How creepy do you think this is?" title to match other headings on production
- [x] Replace outline with grey background `#f4f4f4` (should match banner grey)
- [x] Update button to `.btn_pop` style from [style guide](https://foundation.mozilla.org/en/style-guide/)
- [x] Expand the width of the creep-o-meter 
- [x] Expand the width of creep-o-meter results screen (note: should already be expanded on mobile)
- [x] Keep the newsletter sign up prompt the same

### Creep-o-meter currently looks like:
image

### New desktop comp 
https://redpen.io/va5424e577adb0d331
image

image

image

### New mobile comp 
image

---

**🗒  Design -> Dev Handoff Checklist**

- [x] Design has been finalized
- [x] Link to original design ticket #5152
- [X] Link to related ticket #5234
- [x] Link to [Sketch file](https://share.goabstract.com/584e7002-4d07-4ce5-aafe-dc825e076a27?sha=f0b8ca1b588425d1ef83c57a9f4126c8ff97648e)
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included - n/a
- [x] Hover state for elements are designed - same as on production
- [x] Other states for elements are designed (e.g., error state for form) - same as on production

### PR DESCRIPTION
**Pull request by mmmavis**
Closes #5236 

https://foundation-s-issue-5236-bxlhff.herokuapp.com/en/privacynotincluded/products/reach-cost/

@Pomax For `double checking that things still work purely with the frontend removed` -
No errors were generated on dev tool console and terminal when I tried submitting the vote. Is there anywhere else I should be checking?

### CODE REVIEW

**Comment by kristinashu** [comment]
The content filling the width looks really good! 

For the signup screen, can the fields be either transparent or match the background grey (like the buttons on the first and third screen)? (screen cap from PR)
image

Also please make the headings the same styling on the second and third screen as the first screen.

We could take this opportunity to make the title and button case more consistent (make them all sentence case). Should I open a new ticket for that?

**Review by kristinashu — CHANGES_REQUESTED** [review]
See comment above.

**Comment by mmmavis** [comment]
@kristinashu PR updated! Hopefully I've captured everything you mentioned.

**Comment by Pomax** [comment]
@mavis the only other thing we'll need to verify is that `inv manage aggregate_product_data` works correctly

**Review by Pomax — CHANGES_REQUESTED** [review]
The code looks good, but voting a few times on a product and then running the `aggregate_product_votes` command and restarting docker doesn't show an updated vote count, so we might be missing something somewhere...

**Review by kristinashu — APPROVED** [review]
Sweet! Design looks good!

**Comment by mmmavis** [comment]
@Pomax I've found the [issue](https://github.com/mozilla/foundation.mozilla.org/pull/5269/commits/7bb18f7f583fb550d6a2562e4c5923cebde76bcb)! Total votes should be based on votes on `creepiness` and not `confidence`.  This is currently happening on production, too. I wonder if I should commit the fix directly to `master` (through a PR, of course) instead of including it as part of this PR.

**Comment by Pomax** [comment]
@mmmavis good find! yes, let's make a new unplanned-but-not-stretch issue for that targeting master directly.

**Review by Pomax — APPROVED** [review]
Approved, but it'll need that conflict resolved before we can land it

**Comment by Pomax** [comment]
@mmmavis I wasn't sure which of the two lines should be kept, so I'll leave the conflict resolution to you.

**Comment by mmmavis** [comment]
Ticket/PR filed for the total vote issue: https://github.com/mozilla/foundation.mozilla.org/issues/5293

**Pull request merged**
