### PR TITLE
Initiatives Page

### PR DESCRIPTION
**Pull request by gvn**
This is a build of just the new Initiatives page.

Related : #1648

### CODE REVIEW

**Comment by gvn** [comment]
For design review: https://foundation-mofostaging-pr-1674.herokuapp.com/initiatives/

**Comment by beccaklam** [comment]
This looks great @gvn! Really true to the comp. 

- [ ] Not sure why but no matter how big I make the browser window, I get a horizontal scroll bar:
design-review

- [ ] We're missing the external link icon for all links to the MozFest, Internet Health Report and Advocacy pages (I will get this to you, we need to decide on an icon -- we may choose a different icon than the one currently in the comps)

- [ ] Clean up spacing and some max-widths on the paragraphs. This was mostly my fault for not being pixel perfect. I've outlined the spacing for you here though:
screen shot 2018-07-24 at 1 47 20 pm

- [ ] Noticed this bug, not sure why the padding is cutting into the scroll bar:
screen shot 2018-07-24 at 10 47 09 am

- [ ] Secondary nav bar select and hover states should be like the secondary nav on the Aadhaar campaign: https://foundation.mozilla.org/campaigns/aadhaar/

Let me know if you have any questions! Again, it's looking sooo great 😍

**Comment by beccaklam** [comment]
Hi @gvn The changes look great! 👏 Just some small tweaks plus I neglected to look at mobile yesterday so I added some feedback for that too. Thanks so much!
# Desktop 
- [ ] Can we add a max-width of 625px to all the Initiatives paragraphs? And increase the padding for its parent div from 3rem to 5.5rem? Will need to change the padding for mobile though, see below.
screen shot 2018-07-25 at 12 11 02 pm
# Mobile
- [ ] Add in 'cut out' for header image and change h1 to be left aligned. 
- [ ] Change padding to 1.5rem or whatever it normally is for cards and then match the padding for all other paragraphs to the foundation's site normal padding (looks like 15px on main page)
screen shot 2018-07-25 at 12 30 27 pm
screen shot 2018-07-25 at 12 30 39 pm

**Comment by beccaklam** [comment]
# All
- [ ] Add external icon to secondary nav
screen shot 2018-07-27 at 9 58 01 am

# Mobile
- [ ] Can we do .my-4 for the initiatives paragraphs? or change the padding to .py-5 and maintain .px-3
screen shot 2018-07-27 at 10 17 05 am

- [ ] The blank drop down menu looks weird. Can we start with the first link showing up there?
screen shot 2018-07-27 at 11 21 52 am

- [ ] This is a universal change ... so maybe it should be in another ticket. But I feel like the line-height for the paragraph style 'body-large' is too tight. Could we bump from line-height: 1.333rem to 1.4rem?

# Medium/Tablet
 _(>960px - mobile break point)_
Sorry for the lateness on this, but here is the mock up for what the page should look like at the tablet break point, which I'm thinking should maybe start at 960px since the google nexus 7 is that width and the desktop layout already looks kinda wonky there. Not sure what you have for the mobile break point, but maybe 600px would work? Let me know your thoughts.
initiatives tablet ui-withnotation 2x

**Comment by gvn** [comment]
> Add external icon to secondary nav (@gvn you were able to do this for the buttons so i'm assuming you have access to an icon?)

For the secondary nav revisions as we discussed earlier on Slack, I'm going to hold off and do that as part of the work to unify the various secondary nav designs.

**Comment by gvn** [comment]
> This is a universal change ... so maybe it should be in another ticket. But I feel like the line-height for the paragraph style 'body-large' is too tight. Could we bump from line-height: 1.333rem to 1.4rem?

This would be a very big change to the overall typography of the site which has already had a ton of design effort put in to make consistent. I'd strongly recommend we leave it as is.

**Comment by gvn** [comment]
FYI: Here are the breakpoints that Bootstrap defines: 

https://getbootstrap.com/docs/4.1/layout/overview/#responsive-breakpoints

**Comment by gvn** [comment]
You can actually put the images in directly through the CMS to try them out!

Just go to https://foundation-mofostaging-pr-1674.herokuapp.com/cms/ 

(username and password are in #mofo-review-apps)

**Comment by beccaklam** [comment]
Oh niiiice, will try it out.

**Comment by beccaklam** [comment]
@gvn The cms is working really swell! Looks and feels great. 
The image appears cut off though on horizontal tablet view(see below). Is there something that can be done about the resizing of the image at that break point or can we do something on the image end of things (resize to a different ratio)?
screenshot_2018-07-30 mozilla foundation -

**Comment by beccaklam** [comment]
@gvn So I put in all the content and played with different browsers, it's pretty much good to go. Two things:

- [ ] Can we decrease the height of the desktop header? I couldn't find what was determining its height in the styling but I think if we decreased it by 2/3 that should be about right. It should look more like this: https://redpen.io/svdf7af7cee3d4fa44 Sorry the grey space was misleading in the other comps ... will make more precise in the future.

- [ ] For tablet view can we change the initiatives paragraphs div to 6 columns, keeping the py-5 but adding px-4?
screen shot 2018-07-30 at 3 53 10 pm

**Pull request merged**
