### PR TITLE
7981 - Update donation top banner to DearInternet style

### LINKED ISSUE #7981: [Fundraising] Update donation top banner to DearInternet style (live date: Dec 20)
We want to update the year-end fundraising banner to have [DearInternet](https://foundation.mozilla.org/en/campaigns/dearinternet/) visuals to align with the EOY email push. 

The planned dates to go live are December 20-31, 2021.

Design Files:
- [figma mockup](https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/?node-id=115%3A271)
- [background image file](https://drive.google.com/open?id=1W92ljfva7puOuvbRN-eZgdkCKnegCb7-&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)

Layout and functionality are same as before so the differences from the previous https://github.com/mozilla/foundation.mozilla.org/issues/7819 banner are to update: 
- heading copy _(I’ve used copy from the “No Testing/Year-End” section of the [banner copy doc](https://docs.google.com/document/d/1r2Ft9tvEZLzgBPQE3HzECTUhCMBlNiSvWyFJCJOKsTQ/edit))_
- type styling
- button colour 
- background image

### PR DESCRIPTION
**Pull request by fessehaye**
Closes #7981 

Do not merge til Dec. 20th

Use `localStorage.removeItem("donate banner dismiss day")` if you can not see the banner!

### CODE REVIEW

**Review by sabrinang — DISMISSED** [review]
- Italicize heading-2 italicized to match [dearinternet](https://foundation.mozilla.org/en/campaigns/dearinternet/) styling
- When pressed it isn’t a darker blue `#0A0C8F` for me (border should still be present on press)
- Can we make the close `x` black to make it look more like the UI _(let me know if you need an SVG export for this)_
- I simplified the mobile background for MoCo's for legibility, so I'll approach this similarly where < 992px breakpoint can you switch to [this background image ](https://drive.google.com/open?id=1WZE_V53zkyh-FI77CHSkvRw6pxngjQkS&authuser=sabrina%40mozillafoundation.org&usp=drive_fs) so the globe doesn't make it too busy for text on smaller viewports

**Review by sabrinang — DISMISSED** [review]
For the background image, can we keep the [original](https://drive.google.com/open?id=1W92ljfva7puOuvbRN-eZgdkCKnegCb7-&authuser=sabrina%40mozillafoundation.org&usp=drive_fs) for >992px breakpoints and switch to use the [simplified](https://drive.google.com/open?id=1WZE_V53zkyh-FI77CHSkvRw6pxngjQkS&authuser=sabrina%40mozillafoundation.org&usp=drive_fs) one for <992px breakpoints?

Thanks for making the other changes so far!

**Review by sabrinang — APPROVED** [review]
The image update is looking good, thank you @fessehaye !

**Review by danielfmiranda — APPROVED** [review]
Hey Simon! Code looks good to me, approving!

**Pull request merged**
