### PR TITLE
Signup form outline fix

### LINKED ISSUE #3507: Signup field `has-danger` on pageload
**Describe the bug**
Bannered Campaign page signup field shows red outline on email form field at page load

**To Reproduce**
1. Visit https://foundation.mozilla.org/en/initiatives/open-leadership-events/
2. Observe the join component in the right column on desktop

**Expected behavior**
Field does not have "danger" class on page load

(Suspected problem line](https://github.com/mozilla/foundation.mozilla.org/blob/master/source/js/components/join/join.jsx#L227)

### PR DESCRIPTION
**Pull request by youriwims**
Closes #3507 
Related PRs/issues #3561 

Test Page: https://foundation-mofostaging-pr-3570.herokuapp.com/en/bannered-campaign-signup-test/

### CODE REVIEW

**Comment by mmmavis** [comment]
@youriwims PR shows up as draft. Is this ready for review?

**Comment by youriwims** [comment]
Yeah, sorry about that. Forgot to take it off draft!

**Comment by youriwims** [comment]
my bad, give me a sec

**Comment by youriwims** [comment]
Also, I'm a little confused on the behavior of the `.has-danger` class. Should it be active if there's any error (Checkbox and/or invalid email) or should it only be active _if_ there's an invalid email?

**Comment by mmmavis** [comment]
`.has-danger` should be added on to the field that has error.

**Comment by youriwims** [comment]
ya, I agree. I was going to remove that and clean some things up, but it was going to be a lot more than the simple ask from the ticket :/

**Pull request merged**
