### PR TITLE
7770 - Add and fix mini-dings in tab section

### LINKED ISSUE #7770: [PNI QA] Add and fix mini-dings in tab section
Note this is not a critical bug and can be done next sprint.

Checking the Mini-ding within any of the tab sections shows the ding in the tab but not within the tab.

### Todo
- [x] Show mini-ding next to each individual criteria when the related check-box is selected in the CMS
- [x] Ding in the tabs should always appear to the right of the title

### Screen cap from prod
Screen Shot 2021-11-03 at 5 29 20 PM

### Figma comp
Screen Shot 2021-11-03 at 5 29 13 PM

cc @sabrinang @nancyt1 in case you have any extra insights on this

### LINKED ISSUE #7824: [PNI QA] Weird text overlap
There's draft were this is happening on the "Kobo eReaders" https://foundation.mozilla.org/cms/pages/1676/edit/preview/ (I don't want to publish it).

The "How can you control your data?" text is very long so maybe that broke it?

Screen Shot 2021-11-09 at 3 57 48 PM

### PR DESCRIPTION
**Pull request by fessehaye**
Closes #7770 

In order to test the changes, you might need to go to admin/cms and edit one of the products to toggle the dings

Also fixes #7824

### CODE REVIEW

**Comment by kristinashu** [comment]
I added all the dings here https://foundation-s-7770-ding-zz53aub.mofostaging.net/en/privacynotincluded/general-percy-product/ and it looks good! 

image

**Review by danielfmiranda — APPROVED** [review]
Hey Simon! Just checked this out and it looks great. Approving 👍

**Comment by kristinashu** [comment]
Also tested for #7824 and it also looks good!

image

**Review by kristinashu — APPROVED** [review]
Yay, design looks good!

**Pull request merged**
