### PR TITLE
Participate P2 Revisions

### PR DESCRIPTION
**Pull request by gvn**
Related issue: #1749

### CODE REVIEW

**Comment by gvn** [comment]
@kristinashu We're having problems uploading images to staged PRs right now, so I took screenshots of 3 breakpoints for your design review:

localhost_8000_cms_pages_38_edit_preview_320
localhost_8000_cms_pages_38_edit_preview_780
localhost_8000_cms_pages_38_edit_preview_1200

**Comment by kristinashu** [comment]
Thanks for the screen caps! The only thing that looks slightly off is the Donate/Share cta on mobile. I like that the image is on top of the text but the gap between the two (below the image and above the text "If you can, will you give today?") seems a little too big so it takes up more vertical space than needed. Is it possible to reduce that gap? Otherwise, everything else is looking good!

Screen cap of the screen cap:

image

**Comment by gvn** [comment]
How's this?

localhost_8000_cms_pages_38_edit_preview_

**Comment by kristinashu** [comment]
🚢 it!

**Pull request merged**
