### PR TITLE
Fix the frame offset for the creepiness scroll emoji

### PR DESCRIPTION
**Pull request by Pomax**
closes https://github.com/mozilla/foundation.mozilla.org/issues/2143

### CODE REVIEW

**Comment by kristinashu** [comment]
`View deployment` doesn't seem to be working for me. 

https://foundation-mofostaging-pr-2152.herokuapp.com/en/ is completely blank

and https://foundation-mofostaging-pr-2152.herokuapp.com/en/privacynotincluded/ has no products

image

**Comment by mmmavis** [comment]
I'm getting the same issues. Let me see if there's anything on Heroku I can fix.

**Comment by mmmavis** [comment]
Review app is getting this error on Heroku

image

**Comment by Pomax** [comment]
we can conclude heroku is broken today. More luck next week I guess.

**Comment by kristinashu** [comment]
😱

**Comment by beccaklam** [comment]
This appears fixed! @kristinashu

**Comment by beccaklam** [comment]
Hmm, this still appears broken. Do I just need to wait or ... ?

**Comment by kristinashu** [comment]
@Pomax did this was good in this PR but it isn't working on staging or prod?

**Pull request merged**
